slogo_team10: gui.nonbuttonfeatures.TurtleScreenFeature Class Reference
gui.nonbuttonfeatures.TurtleScreenFeature Class Reference
Public Member Functions
TurtleScreenFeature (TurtleScreenDrawer parentDrawer, WorkspaceScreenParameters screenParams)
Static Private Attributes
static final String COLOR = SavedWorkspaceXMLReader.COLOR
static final String TOGGLE_GRID = SavedWorkspaceXMLReader.TOGGLE_GRID
Detailed Description
This is the turtle screen. The reason it is a feature is that we may make it interactive in the future - for instance click to draw another turtle
Author
Austin Kyker
Definition at line 18 of file TurtleScreenFeature.java.
Constructor & Destructor Documentation
gui.nonbuttonfeatures.TurtleScreenFeature.TurtleScreenFeature (TurtleScreenDrawer parentDrawer, WorkspaceScreenParameters screenParams)
Constructor
Parameters
parentDrawer
screenParams - parameters used to set up the screen. Will be null unless an xml file was loaded containing screen parameters.
Definition at line 29 of file TurtleScreenFeature.java.
References gui.componentdrawers.TurtleScreenDrawer.changeScreenColor(), XML.workspaceparams.WorkspaceScreenParameters.extractParams(), gui.componentdrawers.TurtleScreenDrawer.GRID_HEIGHT, gui.componentdrawers.TurtleScreenDrawer.GRID_WIDTH, XML.workspaceparams.WorkspaceScreenParameters.hasParam(), gui.componentdrawers.TurtleScreenDrawer.setTurtleScreenFeature(), and gui.componentdrawers.TurtleScreenDrawer.toggleGrid().
Member Data Documentation
final String gui.nonbuttonfeatures.TurtleScreenFeature.COLOR = SavedWorkspaceXMLReader.COLOR static private
Definition at line 20 of file TurtleScreenFeature.java.
final String gui.nonbuttonfeatures.TurtleScreenFeature.TOGGLE_GRID = SavedWorkspaceXMLReader.TOGGLE_GRID static private
Definition at line 21 of file TurtleScreenFeature.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/nonbuttonfeatures/TurtleScreenFeature.java