slogo_team10: gui.factories.turtlefactory.TurtleNode Class Reference
gui.factories.turtlefactory.TurtleNode Class Reference
Public Member Functions
TurtleNode (Map< String, String > params, Workspace workspace) throws FileNotFoundException
TurtleNode[] updatePosition (Map< String, String > params)
boolean isSelected ()
String getTurtleID ()
Protected Member Functions
void updateImage (String imagePath) throws FileNotFoundException
Private Member Functions
double[] parseStringToPoints (String point)
void selectTurtle ()
Private Attributes
boolean isSelected
Workspace myWorkspace
String myID
Static Private Attributes
static final String SELECTED_TURTLE_IMAGEPATH
static final String DESELECTED_TURTLE_IMAGEPATH
static final double TURTLE_IMAGE_WIDTH_RATIO = 0.06
static final double TURTLE_IMAGE_WIDTH
static final double TURTLE_IMAGE_HEIGHT_RATIO = 0.06
static final double TURTLE_IMAGE_HEIGHT
Detailed Description
Represents a turtle node on the screen. Turtles nodes can be selected by the user by clicking on them and their position on the screen can be updated by incoming drawable objects (the result of user commands).
Author
Austin Kyker
Definition at line 24 of file TurtleNode.java.
Constructor & Destructor Documentation
gui.factories.turtlefactory.TurtleNode.TurtleNode (Map< String, String > params, Workspace workspace) throws FileNotFoundException
Definition at line 42 of file TurtleNode.java.
References gui.factories.turtlefactory.TurtleNode.selectTurtle(), gui.factories.turtlefactory.TurtleFactory.TURTLE_ID, gui.factories.turtlefactory.TurtleNode.updateImage(), and gui.factories.turtlefactory.TurtleNode.updatePosition().
Member Function Documentation
String gui.factories.turtlefactory.TurtleNode.getTurtleID ()
Returns the id of the turtle
Returns
String
Definition at line 135 of file TurtleNode.java.
References gui.factories.turtlefactory.TurtleNode.myID.
boolean gui.factories.turtlefactory.TurtleNode.isSelected ()
Returns true if the turtle is selected (green) and false otherwise.
Returns
Boolean
Definition at line 127 of file TurtleNode.java.
Referenced by gui.factories.turtlefactory.TurtleNodes.getActiveNodes(), and gui.factories.turtlefactory.TurtleNode.selectTurtle().
double [] gui.factories.turtlefactory.TurtleNode.parseStringToPoints (String point) private
Converts the location string to a double array of points.
Parameters
point
Returns
Definition at line 82 of file TurtleNode.java.
Referenced by gui.factories.turtlefactory.TurtleNode.updatePosition().
void gui.factories.turtlefactory.TurtleNode.selectTurtle () private
This method is called when a turtle is clicked. The image of the turtle changes to make the user aware that the turtle is selected and can be moved interactively using the arrow keys on the keyboard.
Definition at line 93 of file TurtleNode.java.
References gui.factories.turtlefactory.TurtleNode.isSelected(), gui.mainclasses.workspace.Workspace.notifyOfTurtleSelectionChange(), and gui.factories.turtlefactory.TurtleNode.updateImage().
Referenced by gui.factories.turtlefactory.TurtleNode.TurtleNode().
void gui.factories.turtlefactory.TurtleNode.updateImage (String imagePath) throws FileNotFoundException protected
Updates the image of the turtle to be the image located at the input imagePath
Parameters
imagePath
Exceptions
FileNotFoundException
Definition at line 117 of file TurtleNode.java.
Referenced by gui.factories.turtlefactory.TurtleNode.selectTurtle(), and gui.factories.turtlefactory.TurtleNode.TurtleNode().
TurtleNode [] gui.factories.turtlefactory.TurtleNode.updatePosition (Map< String, String > params)
Updates the position of a turtle based on the location parameters specified by the params map delivered in the drawable object.
Parameters
params
Returns
Definition at line 59 of file TurtleNode.java.
References gui.turtlescreenwrap.CoordinateChanger.convX(), gui.turtlescreenwrap.CoordinateChanger.convY(), gui.factories.turtlefactory.TurtleFactory.HEADING, gui.factories.turtlefactory.TurtleFactory.LOCATION, gui.turtlescreenwrap.TesselationMapper.map(), gui.factories.turtlefactory.TurtleFactory.OPACITY, and gui.factories.turtlefactory.TurtleNode.parseStringToPoints().
Referenced by gui.factories.turtlefactory.TurtleFactory.generateObject(), and gui.factories.turtlefactory.TurtleNode.TurtleNode().
Member Data Documentation
final String gui.factories.turtlefactory.TurtleNode.DESELECTED_TURTLE_IMAGEPATH static private
Initial value:
=
            "./src/resources/guiResources/turtleImages/deselected_turtle.png"
Definition at line 28 of file TurtleNode.java.
boolean gui.factories.turtlefactory.TurtleNode.isSelected private
Definition at line 38 of file TurtleNode.java.
String gui.factories.turtlefactory.TurtleNode.myID private
Definition at line 40 of file TurtleNode.java.
Referenced by gui.factories.turtlefactory.TurtleNode.getTurtleID().
Workspace gui.factories.turtlefactory.TurtleNode.myWorkspace private
Definition at line 39 of file TurtleNode.java.
final String gui.factories.turtlefactory.TurtleNode.SELECTED_TURTLE_IMAGEPATH static private
Initial value:
=
            "./src/resources/guiResources/turtleImages/selected_turtle.png"
Definition at line 26 of file TurtleNode.java.
final double gui.factories.turtlefactory.TurtleNode.TURTLE_IMAGE_HEIGHT static private
Initial value:
= TurtleScreenDrawer.GRID_HEIGHT *
            TURTLE_IMAGE_HEIGHT_RATIO
Definition at line 35 of file TurtleNode.java.
final double gui.factories.turtlefactory.TurtleNode.TURTLE_IMAGE_HEIGHT_RATIO = 0.06 static private
Definition at line 34 of file TurtleNode.java.
final double gui.factories.turtlefactory.TurtleNode.TURTLE_IMAGE_WIDTH static private
Initial value:
= TurtleScreenDrawer.GRID_WIDTH *
            TURTLE_IMAGE_WIDTH_RATIO
Definition at line 32 of file TurtleNode.java.
final double gui.factories.turtlefactory.TurtleNode.TURTLE_IMAGE_WIDTH_RATIO = 0.06 static private
Definition at line 31 of file TurtleNode.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/factories/turtlefactory/TurtleNode.java