slogo_team10: gui.mainclasses.DrawableObjectParser Class Reference
gui.mainclasses.DrawableObjectParser Class Reference
Static Public Member Functions
static void parseDrawableObject (DrawableObject object, Map< String, ComponentDrawer > drawerMap, ObjectFactory[] factories)
Static Private Member Functions
static Node[] parseNodeToDraw (DrawableObject object, ObjectFactory[] factories)
static ComponentDrawer parseComponentDrawer (String parent, Map< String, ComponentDrawer > drawerMap)
Detailed Description
Class parses a DrawableObject and calls the respective drawer and factory classes with parameters
Author
akyker20, allankiplagat
Definition at line 14 of file DrawableObjectParser.java.
Member Function Documentation
static ComponentDrawer gui.mainclasses.DrawableObjectParser.parseComponentDrawer (String parent, Map< String, ComponentDrawer > drawerMap) static private
Definition at line 39 of file DrawableObjectParser.java.
Referenced by gui.mainclasses.DrawableObjectParser.parseDrawableObject().
static void gui.mainclasses.DrawableObjectParser.parseDrawableObject (DrawableObject object, Map< String, ComponentDrawer > drawerMap, ObjectFactory[] factories) static
Definition at line 16 of file DrawableObjectParser.java.
References gui.componentdrawers.ComponentDrawer.drawShape(), gui.mainclasses.DrawableObjectParser.parseComponentDrawer(), and gui.mainclasses.DrawableObjectParser.parseNodeToDraw().
Referenced by gui.mainclasses.workspace.Workspace.parseDrawableObject().
static Node [] gui.mainclasses.DrawableObjectParser.parseNodeToDraw (DrawableObject object, ObjectFactory[] factories) static private
Definition at line 24 of file DrawableObjectParser.java.
References gui.factories.ObjectFactory.generateObject().
Referenced by gui.mainclasses.DrawableObjectParser.parseDrawableObject().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/mainclasses/DrawableObjectParser.java