slogo_team10: gui.buttonfeatures.SaveCommandButtonFeature Class Reference
gui.buttonfeatures.SaveCommandButtonFeature Class Reference
Public Member Functions
SaveCommandButtonFeature (OptionsHolderDrawer parent, CommandLineDrawer commandLine, PreviousCommandsFeature previousCommands, SavedCommandsFeature savedCommands)
Public Member Functions inherited from gui.buttonfeatures.ButtonFeature
ButtonFeature (String text, OptionsHolderDrawer component)
Private Member Functions
void saveCommand ()
Private Attributes
CommandLineDrawer myCommandLine
PreviousCommandsFeature myPreviousCommands
SavedCommandsFeature mySavedCommands
Additional Inherited Members
Static Public Attributes inherited from gui.buttonfeatures.ButtonFeature
static final int BUTTON_WIDTH = 120
static final int BUTTON_HEIGHT = 40
Detailed Description
This class allows the user to save a command for future use. Commands can be saved from the command line or from the previous commands list view.
Author
Austin Kyker
Definition at line 17 of file SaveCommandButtonFeature.java.
Constructor & Destructor Documentation
gui.buttonfeatures.SaveCommandButtonFeature.SaveCommandButtonFeature (OptionsHolderDrawer parent, CommandLineDrawer commandLine, PreviousCommandsFeature previousCommands, SavedCommandsFeature savedCommands)
Definition at line 23 of file SaveCommandButtonFeature.java.
References gui.mainclasses.TextGenerator.SAVE_COMMAND, and gui.buttonfeatures.SaveCommandButtonFeature.saveCommand().
Member Function Documentation
void gui.buttonfeatures.SaveCommandButtonFeature.saveCommand () private
First, checks to see if the user is trying to select a command from the previous command line (this is the case if one of the previous commands list view items is selected). Otherwise, the command to be saved is taken from the commandline.
Definition at line 39 of file SaveCommandButtonFeature.java.
References gui.nonbuttonfeatures.SavedCommandsFeature.addCommand(), and gui.componentdrawers.CommandLineDrawer.getCurrentCommand().
Referenced by gui.buttonfeatures.SaveCommandButtonFeature.SaveCommandButtonFeature().
Member Data Documentation
CommandLineDrawer gui.buttonfeatures.SaveCommandButtonFeature.myCommandLine private
Definition at line 19 of file SaveCommandButtonFeature.java.
PreviousCommandsFeature gui.buttonfeatures.SaveCommandButtonFeature.myPreviousCommands private
Definition at line 20 of file SaveCommandButtonFeature.java.
SavedCommandsFeature gui.buttonfeatures.SaveCommandButtonFeature.mySavedCommands private
Definition at line 21 of file SaveCommandButtonFeature.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/buttonfeatures/SaveCommandButtonFeature.java