slogo_team10: Control.SlogoGraphics Interface Reference
Control.SlogoGraphics Interface Reference
Public Member Functions
Queue< DrawableObject > parseCommandString (String command) throws IOException, CompileTimeParsingException, RunTimeDivideByZeroException, RunTimeNullPointerException
void createWorkspaceState (int workspaceID)
void setActiveWorkspaceState (int workspaceID)
Detailed Description
Class defines methods accessible to the GUIController
Author
akyker20, allankiplagat
Definition at line 17 of file SlogoGraphics.java.
Member Function Documentation
void Control.SlogoGraphics.createWorkspaceState (int workspaceID)
Creates a new workspace state.
Parameters
workspaceID
Implemented in Control.SlogoControl.
Referenced by gui.mainclasses.workspace.WorkspaceManager.addWorkspace().
Queue<DrawableObject> Control.SlogoGraphics.parseCommandString (String command) throws IOException, CompileTimeParsingException, RunTimeDivideByZeroException, RunTimeNullPointerException
Methods delivers a String command to the back-end to be parsed into a Queue of DrawableObjects that can be translated in to shapes that are displayed on the screen
Parameters
command
Returns
Exceptions
IOException
RunTimeNullPointerException
RunTimeDivideByZeroException
CompileTimeParsingException
Implemented in Control.SlogoControl.
Referenced by gui.mainclasses.workspace.Workspace.moveActiveTurtles(), and gui.mainclasses.workspace.Workspace.parseCommandString().
void Control.SlogoGraphics.setActiveWorkspaceState (int workspaceID)
Lets the backend know which workspace is currently selected (which workspace is being viewed by the user).
Parameters
workspaceID
Implemented in Control.SlogoControl.
Referenced by gui.mainclasses.workspace.WorkspaceManager.addWorkspace(), and gui.mainclasses.workspace.WorkspaceManager.initializeTabPane().
The documentation for this interface was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/Control/SlogoGraphics.java