slogo_team10: workspaceState.Turtle Class Reference
workspaceState.Turtle Class Reference
Public Member Functions
Turtle ()
Turtle (double x, double y)
Turtle (int ID)
Turtle (Turtle turtle)
void showTurtle ()
void hideTurtle ()
boolean isTurtleShowing ()
void setOpacity (double opacity)
double getOpacity ()
double getHeading ()
void setHeading (double myHeading)
void move (double amount)
void rotate (double amount)
Location getLocation ()
double getTurtleXLocation ()
double getTurtleYLocation ()
void setLocation (Location myLocation)
void setID (int ID)
int getID ()
void setShape (Shape fromPalette)
Shape getShape ()
Public Attributes
Pen pen = new Pen()
Private Member Functions
double roundToHundredths (double number)
Private Attributes
double myHeading
Location myLocation
double myOpacity = 100
boolean turtleShowing = true
int myID
Shape shape
Static Private Attributes
static final double DEFAULT_TURTLE_HEADING = 0.0
Detailed Description
This class is the Turtle class that contains all of the information for each Turtle.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 10 of file Turtle.java.
Constructor & Destructor Documentation
workspaceState.Turtle.Turtle ()
Definition at line 21 of file Turtle.java.
workspaceState.Turtle.Turtle (double x, double y)
Definition at line 25 of file Turtle.java.
References workspaceState.Turtle.DEFAULT_TURTLE_HEADING.
workspaceState.Turtle.Turtle (int ID)
Definition at line 31 of file Turtle.java.
References workspaceState.Turtle.setID().
workspaceState.Turtle.Turtle (Turtle turtle)
Definition at line 36 of file Turtle.java.
References workspaceState.Shape.getPath(), workspaceState.Turtle.myHeading, workspaceState.Turtle.myID, workspaceState.Turtle.myLocation, workspaceState.Turtle.myOpacity, workspaceState.Turtle.pen, workspaceState.Turtle.shape, and workspaceState.Turtle.turtleShowing.
Member Function Documentation
double workspaceState.Turtle.getHeading ()
Definition at line 69 of file Turtle.java.
References workspaceState.Turtle.myHeading.
Referenced by commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtle(), commandParsing.turtleCommandParsing.turtleMovement.Home.getDestinationHeading(), and commandParsing.turtleQueryParsing.Heading.parse().
int workspaceState.Turtle.getID ()
Definition at line 112 of file Turtle.java.
References workspaceState.Turtle.myID.
Referenced by workspaceState.TurtleCollection.addStamp(), commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtle(), commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtleDeletion(), workspaceState.TurtleCollection.getLastActiveTurtle(), and commandParsing.turtleQueryParsing.ID.parse().
Location workspaceState.Turtle.getLocation ()
Definition at line 92 of file Turtle.java.
References workspaceState.Turtle.myLocation.
Referenced by commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtle().
double workspaceState.Turtle.getOpacity ()
Definition at line 65 of file Turtle.java.
References workspaceState.Turtle.myOpacity.
Referenced by commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtle().
Shape workspaceState.Turtle.getShape ()
Definition at line 120 of file Turtle.java.
References workspaceState.Turtle.shape.
Referenced by commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtle(), and tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest().
double workspaceState.Turtle.getTurtleXLocation ()
Definition at line 96 of file Turtle.java.
References workspaceState.Location.getX().
Referenced by commandParsing.turtleQueryParsing.XCoordinate.parse().
double workspaceState.Turtle.getTurtleYLocation ()
Definition at line 100 of file Turtle.java.
References workspaceState.Location.getY().
Referenced by commandParsing.turtleQueryParsing.YCoordinate.parse().
void workspaceState.Turtle.hideTurtle ()
Definition at line 52 of file Turtle.java.
References workspaceState.Turtle.setOpacity().
boolean workspaceState.Turtle.isTurtleShowing ()
Definition at line 57 of file Turtle.java.
References workspaceState.Turtle.turtleShowing.
Referenced by tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), commandParsing.turtleQueryParsing.IsShowing.parse(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingAfterHideTest(), and tests.commandTests.turtleQueryTests.IsShowingTests.ShowingTest().
void workspaceState.Turtle.move (double amount)
Definition at line 77 of file Turtle.java.
References workspaceState.Location.add(), workspaceState.Turtle.myHeading, and workspaceState.Turtle.roundToHundredths().
void workspaceState.Turtle.rotate (double amount)
Definition at line 88 of file Turtle.java.
References workspaceState.Turtle.setHeading().
double workspaceState.Turtle.roundToHundredths (double number) private
Definition at line 84 of file Turtle.java.
Referenced by workspaceState.Turtle.move().
void workspaceState.Turtle.setHeading (double myHeading)
Definition at line 73 of file Turtle.java.
References workspaceState.Turtle.myHeading.
Referenced by workspaceState.Turtle.rotate().
void workspaceState.Turtle.setID (int ID)
Definition at line 108 of file Turtle.java.
Referenced by workspaceState.Turtle.Turtle().
void workspaceState.Turtle.setLocation (Location myLocation)
Definition at line 104 of file Turtle.java.
References workspaceState.Turtle.myLocation.
void workspaceState.Turtle.setOpacity (double opacity)
Definition at line 61 of file Turtle.java.
Referenced by workspaceState.Turtle.hideTurtle(), and workspaceState.Turtle.showTurtle().
void workspaceState.Turtle.setShape (Shape fromPalette)
Definition at line 116 of file Turtle.java.
void workspaceState.Turtle.showTurtle ()
Definition at line 47 of file Turtle.java.
References workspaceState.Turtle.setOpacity().
Member Data Documentation
final double workspaceState.Turtle.DEFAULT_TURTLE_HEADING = 0.0 static private
Definition at line 12 of file Turtle.java.
Referenced by workspaceState.Turtle.Turtle().
double workspaceState.Turtle.myHeading private
Definition at line 14 of file Turtle.java.
Referenced by workspaceState.Turtle.getHeading(), workspaceState.Turtle.move(), workspaceState.Turtle.setHeading(), and workspaceState.Turtle.Turtle().
int workspaceState.Turtle.myID private
Definition at line 18 of file Turtle.java.
Referenced by workspaceState.Turtle.getID(), and workspaceState.Turtle.Turtle().
Location workspaceState.Turtle.myLocation private
Definition at line 15 of file Turtle.java.
Referenced by workspaceState.Turtle.getLocation(), workspaceState.Turtle.setLocation(), and workspaceState.Turtle.Turtle().
double workspaceState.Turtle.myOpacity = 100 private
Definition at line 16 of file Turtle.java.
Referenced by workspaceState.Turtle.getOpacity(), and workspaceState.Turtle.Turtle().
Pen workspaceState.Turtle.pen = new Pen()
Definition at line 13 of file Turtle.java.
Referenced by tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), commandParsing.turtleQueryParsing.IsPenDown.parse(), tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest(), and workspaceState.Turtle.Turtle().
Shape workspaceState.Turtle.shape private
Definition at line 19 of file Turtle.java.
Referenced by workspaceState.Turtle.getShape(), and workspaceState.Turtle.Turtle().
boolean workspaceState.Turtle.turtleShowing = true private
Definition at line 17 of file Turtle.java.
Referenced by workspaceState.Turtle.isTurtleShowing(), and workspaceState.Turtle.Turtle().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/workspaceState/Turtle.java