slogo_team10: tests.screenWrapTests.MapperPointPairTests Class Reference
tests.screenWrapTests.MapperPointPairTests Class Reference
Public Member Functions
void testHomeScreen ()
void testRightScreen ()
void testTopRightDiagonalScreen ()
void testTopScreen ()
void testTopLeftDiagonalScreen ()
void testLeftScreen ()
void testBottomLeftDiagonalScreen ()
void testBottomScreen ()
void testBottomRightDiagonalScreen ()
Static Public Attributes
static final float XMAX = TurtleScreenWrap.XMAX
static final float YMAX = TurtleScreenWrap.YMAX
static final double THRESH = 0.00001
Private Member Functions
void test (Point2D origin, Point2D dest)
void testDiagonal (Point2DPair pointPair)
Private Attributes
float origx = -XMAX / 2
float origy = -XMAX / 2
float destx = -XMAX * 2
float desty = -YMAX * 2
Detailed Description
Definition at line 11 of file MapperPointPairTests.java.
Member Function Documentation
void tests.screenWrapTests.MapperPointPairTests.test (Point2D origin, Point2D dest) private
Definition at line 79 of file MapperPointPairTests.java.
References tests.screenWrapTests.MapperPointPairTests.testDiagonal().
Referenced by tests.screenWrapTests.MapperPointPairTests.testBottomLeftDiagonalScreen(), tests.screenWrapTests.MapperPointPairTests.testBottomRightDiagonalScreen(), tests.screenWrapTests.MapperPointPairTests.testBottomScreen(), tests.screenWrapTests.MapperPointPairTests.testLeftScreen(), tests.screenWrapTests.MapperPointPairTests.testRightScreen(), tests.screenWrapTests.MapperPointPairTests.testTopLeftDiagonalScreen(), tests.screenWrapTests.MapperPointPairTests.testTopRightDiagonalScreen(), and tests.screenWrapTests.MapperPointPairTests.testTopScreen().
void tests.screenWrapTests.MapperPointPairTests.testBottomLeftDiagonalScreen ()
Definition at line 62 of file MapperPointPairTests.java.
References tests.screenWrapTests.MapperPointPairTests.test().
void tests.screenWrapTests.MapperPointPairTests.testBottomRightDiagonalScreen ()
Definition at line 74 of file MapperPointPairTests.java.
References tests.screenWrapTests.MapperPointPairTests.test().
void tests.screenWrapTests.MapperPointPairTests.testBottomScreen ()
Definition at line 68 of file MapperPointPairTests.java.
References tests.screenWrapTests.MapperPointPairTests.test().
void tests.screenWrapTests.MapperPointPairTests.testDiagonal (Point2DPair pointPair) private
Definition at line 84 of file MapperPointPairTests.java.
References gui.turtlescreenwrap.Point2DPair.dest, gui.turtlescreenwrap.TesselationMapper.map(), gui.turtlescreenwrap.Point2DPair.origin, and tests.screenWrapTests.MapperPointPairTests.THRESH.
Referenced by tests.screenWrapTests.MapperPointPairTests.test().
void tests.screenWrapTests.MapperPointPairTests.testHomeScreen ()
Definition at line 24 of file MapperPointPairTests.java.
References gui.turtlescreenwrap.TesselationMapper.map().
void tests.screenWrapTests.MapperPointPairTests.testLeftScreen ()
Definition at line 56 of file MapperPointPairTests.java.
References tests.screenWrapTests.MapperPointPairTests.test().
void tests.screenWrapTests.MapperPointPairTests.testRightScreen ()
Definition at line 32 of file MapperPointPairTests.java.
References tests.screenWrapTests.MapperPointPairTests.test().
void tests.screenWrapTests.MapperPointPairTests.testTopLeftDiagonalScreen ()
Definition at line 50 of file MapperPointPairTests.java.
References tests.screenWrapTests.MapperPointPairTests.test().
void tests.screenWrapTests.MapperPointPairTests.testTopRightDiagonalScreen ()
Definition at line 38 of file MapperPointPairTests.java.
References tests.screenWrapTests.MapperPointPairTests.test().
void tests.screenWrapTests.MapperPointPairTests.testTopScreen ()
Definition at line 44 of file MapperPointPairTests.java.
References tests.screenWrapTests.MapperPointPairTests.test().
Member Data Documentation
float tests.screenWrapTests.MapperPointPairTests.destx = -XMAX * 2 private
Definition at line 20 of file MapperPointPairTests.java.
float tests.screenWrapTests.MapperPointPairTests.desty = -YMAX * 2 private
Definition at line 21 of file MapperPointPairTests.java.
float tests.screenWrapTests.MapperPointPairTests.origx = -XMAX / 2 private
Definition at line 17 of file MapperPointPairTests.java.
float tests.screenWrapTests.MapperPointPairTests.origy = -XMAX / 2 private
Definition at line 18 of file MapperPointPairTests.java.
final double tests.screenWrapTests.MapperPointPairTests.THRESH = 0.00001 static
Definition at line 14 of file MapperPointPairTests.java.
Referenced by tests.screenWrapTests.MapperPointPairTests.testDiagonal().
final float tests.screenWrapTests.MapperPointPairTests.XMAX = TurtleScreenWrap.XMAX static
Definition at line 12 of file MapperPointPairTests.java.
final float tests.screenWrapTests.MapperPointPairTests.YMAX = TurtleScreenWrap.YMAX static
Definition at line 13 of file MapperPointPairTests.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/tests/screenWrapTests/MapperPointPairTests.java