slogo_team10: gui.nonbuttonfeatures.PreviousCommandsFeature Class Reference
gui.nonbuttonfeatures.PreviousCommandsFeature Class Reference
Public Member Functions
PreviousCommandsFeature (PreviousCommandsDrawer parentDrawer, CommandLineDrawer commandLineDrawer, ObservableList< String > previousCommands)
Private Member Functions
void displayPreviousCommandInCommandLineOnDblClick (MouseEvent event)
Private Attributes
ObservableList< String > myPreviousCommandsList
CommandLineDrawer myCommandLineDrawer
Static Private Attributes
static final int HEIGHT = 100
static final int LAYOUT = 20
Detailed Description
This class is a list view used to store previous commands. All commands that are entered are put into this list (including commands that raise exceptions - thats how its done in Matlab and other IDEs). The user can run a previous command by double clicking on a list item.
Author
Austin Kyker
Definition at line 20 of file PreviousCommandsFeature.java.
Constructor & Destructor Documentation
gui.nonbuttonfeatures.PreviousCommandsFeature.PreviousCommandsFeature (PreviousCommandsDrawer parentDrawer, CommandLineDrawer commandLineDrawer, ObservableList< String > previousCommands)
Definition at line 27 of file PreviousCommandsFeature.java.
References gui.nonbuttonfeatures.PreviousCommandsFeature.displayPreviousCommandInCommandLineOnDblClick(), and gui.componentdrawers.ComponentDrawer.drawShape().
Member Function Documentation
void gui.nonbuttonfeatures.PreviousCommandsFeature.displayPreviousCommandInCommandLineOnDblClick (MouseEvent event) private
When the user double clicks on a previous command that command will be displayed in the command line so the user can quickly run it by hitting enter.
Parameters
event
Definition at line 47 of file PreviousCommandsFeature.java.
References gui.componentdrawers.CommandLineDrawer.setCommandLine().
Referenced by gui.nonbuttonfeatures.PreviousCommandsFeature.PreviousCommandsFeature().
Member Data Documentation
final int gui.nonbuttonfeatures.PreviousCommandsFeature.HEIGHT = 100 static private
Definition at line 24 of file PreviousCommandsFeature.java.
final int gui.nonbuttonfeatures.PreviousCommandsFeature.LAYOUT = 20 static private
Definition at line 25 of file PreviousCommandsFeature.java.
CommandLineDrawer gui.nonbuttonfeatures.PreviousCommandsFeature.myCommandLineDrawer private
Definition at line 23 of file PreviousCommandsFeature.java.
ObservableList<String> gui.nonbuttonfeatures.PreviousCommandsFeature.myPreviousCommandsList private
Definition at line 22 of file PreviousCommandsFeature.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/nonbuttonfeatures/PreviousCommandsFeature.java