slogo_team10: gui.nonbuttonfeatures.tableviews.variables.EditingCell Class Reference
gui.nonbuttonfeatures.tableviews.variables.EditingCell Class Reference
Public Member Functions
EditingCell (Workspace workspace)
void startEdit ()
void createTextField ()
void updateItem (Double item, boolean empty)
Protected Member Functions
String getString ()
Private Attributes
TextField textField
Workspace myWorkspace
Detailed Description
This class allows the user to edit the value column of a workspace variable. When an edit is made, a call to the backend is made to make it aware of the change.
Author
Austin Kyker
Definition at line 19 of file EditingCell.java.
Constructor & Destructor Documentation
gui.nonbuttonfeatures.tableviews.variables.EditingCell.EditingCell (Workspace workspace)
Definition at line 24 of file EditingCell.java.
Member Function Documentation
void gui.nonbuttonfeatures.tableviews.variables.EditingCell.createTextField ()
A text box is created with a key listener. When the user hits enter the contents of the text box are committed and the observable list is edited! To let the back-end know of the variable change, a command is sent to the control representing the change in the value of the variable.
Definition at line 50 of file EditingCell.java.
References gui.variableslist.WorkspaceVariable.getMyName(), gui.nonbuttonfeatures.tableviews.variables.EditingCell.getString(), and gui.mainclasses.workspace.Workspace.parseCommandString().
Referenced by gui.nonbuttonfeatures.tableviews.variables.EditingCell.startEdit().
String gui.nonbuttonfeatures.tableviews.variables.EditingCell.getString () protected
Method to return the item as a string. If the item is null (an empty cell), an empty string is returned.
Returns
String representing item
Definition at line 88 of file EditingCell.java.
Referenced by gui.nonbuttonfeatures.tableviews.variables.EditingCell.createTextField(), and gui.nonbuttonfeatures.tableviews.variables.EditingCell.updateItem().
void gui.nonbuttonfeatures.tableviews.variables.EditingCell.startEdit ()
When the user clicks on a cell, the editing process begins. A Textbox is created that gives the user the ability to edit the value of the variable.
Definition at line 35 of file EditingCell.java.
References gui.nonbuttonfeatures.tableviews.variables.EditingCell.createTextField().
void gui.nonbuttonfeatures.tableviews.variables.EditingCell.updateItem (Double item, boolean empty)
When the user edits a cell and presses enter in the text box, the item is updated and the textbox is removed.
Definition at line 74 of file EditingCell.java.
References gui.nonbuttonfeatures.tableviews.variables.EditingCell.getString().
Member Data Documentation
Workspace gui.nonbuttonfeatures.tableviews.variables.EditingCell.myWorkspace private
Definition at line 22 of file EditingCell.java.
TextField gui.nonbuttonfeatures.tableviews.variables.EditingCell.textField private
Definition at line 21 of file EditingCell.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/nonbuttonfeatures/tableviews/variables/EditingCell.java