slogo_team10: workspaceState.TurtleCollection Class Reference
workspaceState.TurtleCollection Class Reference
Public Member Functions
void addTurtle () throws RunTimeNullPointerException
void addTurtle (int ID) throws RunTimeNullPointerException
void activateTurtle (int ID) throws RunTimeNullPointerException
void clearActiveTurtles ()
List< Turtle > getActiveTurtles ()
List< Turtle > getAllTurtles ()
Turtle getLastActiveTurtle ()
void addStamp (Turtle stamp)
List< Turtle > getStamps ()
void removeAllStamps ()
Turtle getTurtleWithID (Integer ID)
boolean hasTurtleWithID (Integer ID)
Turtle getLastAddedTurtle ()
Protected Member Functions
void generateValidTurtleID ()
Private Attributes
Map< Integer, Turtle > turtles = new HashMap<Integer, Turtle>()
Map< Integer, Turtle > activeTurtles = new HashMap<Integer, Turtle>()
Map< Integer, Turtle > turtleStamps = new HashMap<Integer, Turtle>()
int IDCounter = 1
int lastAddedID = 1
Detailed Description
This class contains all of the turtles, all of the active turtles, and all of the stamps. This class is for the most part where any kind of interactions with turtles happen.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 19 of file TurtleCollection.java.
Member Function Documentation
void workspaceState.TurtleCollection.activateTurtle (int ID) throws RunTimeNullPointerException
Definition at line 45 of file TurtleCollection.java.
Referenced by workspaceState.TurtleCollection.addTurtle(), commandParsing.structuralCommandParsing.AskWith.determineIfTurtleIsValidRecipient(), commandParsing.structuralCommandParsing.MultipleTurtleCommand.makeAndActivateGivenTurtles(), and commandParsing.structuralCommandParsing.MultipleTurtleCommand.restoreActiveTurtles().
void workspaceState.TurtleCollection.addStamp (Turtle stamp)
Definition at line 75 of file TurtleCollection.java.
References workspaceState.Turtle.getID().
Referenced by commandParsing.turtleCommandParsing.Stamp.parse().
void workspaceState.TurtleCollection.addTurtle () throws RunTimeNullPointerException
Definition at line 26 of file TurtleCollection.java.
References workspaceState.TurtleCollection.generateValidTurtleID().
Referenced by commandParsing.structuralCommandParsing.MultipleTurtleCommand.makeAndActivateGivenTurtles(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), commandParsing.turtleCommandParsing.MakeTurtle.parse(), and tests.commandTests.CommandTester.setUpStateBeforeTesting().
void workspaceState.TurtleCollection.addTurtle (int ID) throws RunTimeNullPointerException
Definition at line 32 of file TurtleCollection.java.
References workspaceState.TurtleCollection.activateTurtle().
void workspaceState.TurtleCollection.clearActiveTurtles ()
Definition at line 53 of file TurtleCollection.java.
Referenced by commandParsing.structuralCommandParsing.AskWith.determineIfTurtleIsValidRecipient(), commandParsing.structuralCommandParsing.Tell.parse(), commandParsing.structuralCommandParsing.Ask.parse(), and commandParsing.structuralCommandParsing.AskWith.parse().
void workspaceState.TurtleCollection.generateValidTurtleID () protected
Definition at line 39 of file TurtleCollection.java.
Referenced by workspaceState.TurtleCollection.addTurtle().
List<Turtle> workspaceState.TurtleCollection.getActiveTurtles ()
Definition at line 57 of file TurtleCollection.java.
Referenced by tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetPenColor.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetPenSize.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetHeading.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetShape.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.Rotate.operateOnComponents(), commandParsing.turtleCommandParsing.ClearScreen.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetTowards.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.Move.operateOnComponents(), commandParsing.turtleQueryParsing.Turtles.parse(), commandParsing.turtleQueryParsing.GetPenColor.parse(), commandParsing.turtleCommandParsing.turtleAttributeSetters.HideTurtle.parse(), commandParsing.turtleCommandParsing.turtleAttributeSetters.PenDown.parse(), commandParsing.turtleCommandParsing.turtleAttributeSetters.PenUp.parse(), commandParsing.turtleCommandParsing.turtleAttributeSetters.ShowTurtle.parse(), commandParsing.turtleQueryParsing.GetShape.parse(), commandParsing.turtleCommandParsing.Stamp.parse(), commandParsing.structuralCommandParsing.MultipleTurtleCommand.saveCurrentActiveTurtles(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), and tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests().
List<Turtle> workspaceState.TurtleCollection.getAllTurtles ()
Definition at line 61 of file TurtleCollection.java.
Referenced by commandParsing.structuralCommandParsing.AskWith.parse().
Turtle workspaceState.TurtleCollection.getLastActiveTurtle ()
Definition at line 65 of file TurtleCollection.java.
References workspaceState.Turtle.getID().
Referenced by tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), commandParsing.turtleCommandParsing.turtleMovement.Home.getDestinationHeading(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest(), tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), commandParsing.turtleQueryParsing.Heading.parse(), commandParsing.turtleQueryParsing.IsPenDown.parse(), commandParsing.turtleQueryParsing.IsShowing.parse(), commandParsing.turtleQueryParsing.ID.parse(), commandParsing.turtleQueryParsing.XCoordinate.parse(), commandParsing.turtleQueryParsing.YCoordinate.parse(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingAfterHideTest(), and tests.commandTests.turtleQueryTests.IsShowingTests.ShowingTest().
Turtle workspaceState.TurtleCollection.getLastAddedTurtle ()
Definition at line 95 of file TurtleCollection.java.
Referenced by commandParsing.structuralCommandParsing.MultipleTurtleCommand.makeAndActivateGivenTurtles(), and commandParsing.turtleCommandParsing.MakeTurtle.parse().
List<Turtle> workspaceState.TurtleCollection.getStamps ()
Definition at line 79 of file TurtleCollection.java.
Referenced by commandParsing.turtleCommandParsing.ClearStamps.parse(), and tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest().
Turtle workspaceState.TurtleCollection.getTurtleWithID (Integer ID)
Definition at line 87 of file TurtleCollection.java.
Referenced by tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), and tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests().
boolean workspaceState.TurtleCollection.hasTurtleWithID (Integer ID)
Definition at line 91 of file TurtleCollection.java.
Referenced by commandParsing.structuralCommandParsing.MultipleTurtleCommand.makeAndActivateGivenTurtles().
void workspaceState.TurtleCollection.removeAllStamps ()
Definition at line 83 of file TurtleCollection.java.
Referenced by commandParsing.turtleCommandParsing.ClearStamps.parse().
Member Data Documentation
Map<Integer, Turtle> workspaceState.TurtleCollection.activeTurtles = new HashMap<Integer, Turtle>() private
Definition at line 21 of file TurtleCollection.java.
int workspaceState.TurtleCollection.IDCounter = 1 private
Definition at line 23 of file TurtleCollection.java.
int workspaceState.TurtleCollection.lastAddedID = 1 private
Definition at line 24 of file TurtleCollection.java.
Map<Integer, Turtle> workspaceState.TurtleCollection.turtles = new HashMap<Integer, Turtle>() private
Definition at line 20 of file TurtleCollection.java.
Map<Integer, Turtle> workspaceState.TurtleCollection.turtleStamps = new HashMap<Integer, Turtle>() private
Definition at line 22 of file TurtleCollection.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/workspaceState/TurtleCollection.java