slogo_team10: gui.turtlescreenwrap.TesselationMapper Class Reference
gui.turtlescreenwrap.TesselationMapper Class Reference
Static Public Member Functions
static Point2DPair map (Point2DPair pointPair)
static Point2D map (Point2D point)
static Point2D getDummyOrigin (Point2D point)
static boolean checkOffScreen (Point2D point)
Static Public Attributes
static final float XMAX = TurtleScreenWrap.XMAX
static final float YMAX = TurtleScreenWrap.YMAX
Detailed Description
Class maps a Point2D pair to the TurtleScreen's visible coordinates such that any Point2DPair is within (or at least its origin) starts within the visible TurtleScreen
Author
allankiplagat
Definition at line 11 of file TesselationMapper.java.
Member Function Documentation
static boolean gui.turtlescreenwrap.TesselationMapper.checkOffScreen (Point2D point) static
Method checks whether a point is off the screen
Parameters
point
Returns
Definition at line 78 of file TesselationMapper.java.
References gui.turtlescreenwrap.TesselationMapper.YMAX.
Referenced by gui.turtlescreenwrap.HorizontalTurtleScreenWrap.fragmentPoint2DPair(), gui.turtlescreenwrap.VerticalTurtleScreenWrap.fragmentPoint2DPair(), gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), gui.turtlescreenwrap.TurtleScreenWrap.getExitEdge(), gui.turtlescreenwrap.TesselationMapper.map(), and tests.screenWrapTests.MapperRandomPointTests.testRandom().
static Point2D gui.turtlescreenwrap.TesselationMapper.getDummyOrigin (Point2D point) static
Method gets dummy origin for point's tesselated screen
Returns
Definition at line 55 of file TesselationMapper.java.
References gui.turtlescreenwrap.TesselationMapper.XMAX, and gui.turtlescreenwrap.TesselationMapper.YMAX.
Referenced by gui.turtlescreenwrap.TesselationMapper.map().
static Point2DPair gui.turtlescreenwrap.TesselationMapper.map (Point2DPair pointPair) static
Method returns a mapped tesselated pair, based on the origin of the point2DPair
Parameters
point
Returns
Definition at line 21 of file TesselationMapper.java.
References gui.turtlescreenwrap.TesselationMapper.checkOffScreen(), gui.turtlescreenwrap.Point2DPair.dest, gui.turtlescreenwrap.TesselationMapper.getDummyOrigin(), and gui.turtlescreenwrap.Point2DPair.origin.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.MapperPointPairTests.testDiagonal(), tests.screenWrapTests.MapperPointPairTests.testHomeScreen(), tests.screenWrapTests.MapperRandomPointTests.testRandom(), and gui.factories.turtlefactory.TurtleNode.updatePosition().
static Point2D gui.turtlescreenwrap.TesselationMapper.map (Point2D point) static
Method returns a mapped Point2D
Parameters
point
Returns
Definition at line 41 of file TesselationMapper.java.
References gui.turtlescreenwrap.TesselationMapper.checkOffScreen(), and gui.turtlescreenwrap.TesselationMapper.getDummyOrigin().
Member Data Documentation
final float gui.turtlescreenwrap.TesselationMapper.XMAX = TurtleScreenWrap.XMAX static
Definition at line 12 of file TesselationMapper.java.
Referenced by gui.turtlescreenwrap.TesselationMapper.getDummyOrigin().
final float gui.turtlescreenwrap.TesselationMapper.YMAX = TurtleScreenWrap.YMAX static
Definition at line 13 of file TesselationMapper.java.
Referenced by gui.turtlescreenwrap.TesselationMapper.checkOffScreen(), and gui.turtlescreenwrap.TesselationMapper.getDummyOrigin().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/turtlescreenwrap/TesselationMapper.java