slogo_team10: commandParsing.CommandParser Class Reference
commandParsing.CommandParser Class Reference abstract
Public Member Functions
CommandParser (WorkspaceState someWorkspace)
abstract double parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Static Public Member Functions
static CommandParser createParser (String commandName, WorkspaceState workspace) throws CompileTimeParsingException
Protected Member Functions
void accumulateComponents (Iterator< String > commandStringIterator, int numberToAccumulate, Queue< DrawableObject > objectQueue) throws SLOGOException
boolean isStringParsableAsCommand (String string)
Protected Attributes
List< Double > expressionComponents = new ArrayList<Double>()
Static Protected Attributes
static WorkspaceState workspace
Detailed Description
This is the broad CommandParser class, the superclass for every parser class.
Author
Steve Kuznetsov
Definition at line 20 of file CommandParser.java.
Constructor & Destructor Documentation
commandParsing.CommandParser.CommandParser (WorkspaceState someWorkspace)
Definition at line 25 of file CommandParser.java.
Member Function Documentation
void commandParsing.CommandParser.accumulateComponents (Iterator< String > commandStringIterator, int numberToAccumulate, Queue< DrawableObject > objectQueue) throws SLOGOException protected
Definition at line 33 of file CommandParser.java.
References commandParsing.CommandParser.createParser(), commandParsing.CommandParser.isStringParsableAsCommand(), and commandParsing.CommandParser.parse().
Referenced by commandParsing.structuralCommandParsing.RecurringCommand.basicLoopVariableInitialization(), commandParsing.structuralCommandParsing.For.initializeLoopVariableParameters(), commandParsing.structuralCommandParsing.If.parse(), commandParsing.structuralCommandParsing.IfElse.parse(), commandParsing.colorCommandparsing.SetShapePalette.parse(), commandParsing.floatCommandParsing.FloatInputCommandParser.parse(), and commandParsing.variableCommandParsing.MakeVariable.parse().
static CommandParser commandParsing.CommandParser.createParser (String commandName, WorkspaceState workspace) throws CompileTimeParsingException static
Definition at line 58 of file CommandParser.java.
Referenced by commandParsing.CommandParser.accumulateComponents(), commandParsing.userCommandParsing.UserInstruction.accumulateComponents(), tests.commandTests.CommandTester.createCommand(), commandParsing.structuralCommandParsing.AskWith.determineIfTurtleIsValidRecipient(), commandParsing.structuralCommandParsing.MultipleTurtleCommand.determineTurtlesToActivate(), commandParsing.structuralCommandParsing.StructuralCommand.getVariable(), commandParsing.variableCommandParsing.MakeVariable.parse(), commandParsing.userCommandParsing.UserInstruction.parse(), commandParsing.userCommandParsing.MakeUserInstruction.parse(), commandParsing.structuralCommandParsing.StructuralCommand.parseCommandsBetweenBraces(), and Control.SlogoControl.parseCommandString().
boolean commandParsing.CommandParser.isStringParsableAsCommand (String string) protected
Definition at line 53 of file CommandParser.java.
References translator.Translator.matchesCommandPattern(), and workspaceState.WorkspaceState.translator.
Referenced by commandParsing.CommandParser.accumulateComponents(), commandParsing.userCommandParsing.UserInstruction.accumulateComponents(), and commandParsing.userCommandParsing.MakeUserInstruction.parse().
abstract double commandParsing.CommandParser.parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException abstract
Referenced by commandParsing.CommandParser.accumulateComponents(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOHomeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOTest(), tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest(), tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), commandParsing.structuralCommandParsing.AskWith.determineIfTurtleIsValidRecipient(), commandParsing.structuralCommandParsing.MultipleTurtleCommand.determineTurtlesToActivate(), tests.commandTests.recurringCommandTests.DoTimesTests.DoTimesTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.FalseTest(), tests.commandTests.booleanConditionalCommands.IfTests.FalseTest(), tests.commandTests.booleanCommandTests.NotTests.FloatParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.EqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.OrTests.FloatParseTest(), tests.commandTests.booleanCommandTests.AndTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.FloatParseTest(), tests.commandTests.recurringCommandTests.ForTests.ForTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenDownTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenUpTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerParseTest(), tests.commandTests.turtleQueryTests.YCoordinateTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.RightTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.LeftTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.ForwardTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.BackwardTests.IntegerParsingTest(), tests.commandTests.turtleQueryTests.IsPenDownTests.IsPenDownTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), commandParsing.userCommandParsing.UserInstruction.parse(), commandParsing.structuralCommandParsing.StructuralCommand.parseCommandsBetweenBraces(), Control.SlogoControl.parseCommandString(), tests.commandTests.turtleQueryTests.IsPenDownTests.PenDownAfterPenUp(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.recurringCommandTests.RepeatTests.RepeatTest(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingNoInitialHeading(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingWithPreviousHeading(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteAfterSetPaletteTest(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteAfterSetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingAfterHideTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), tests.commandTests.inputlessCommandTests.StampTests.StampTest(), tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest(), tests.commandTests.booleanCommandTests.NotEqualTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.NotTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.EqualTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.AndTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.OrTests.SyntaxErrorParseTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.TrueTest(), tests.commandTests.booleanConditionalCommands.IfTests.TrueTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorAfterMoveTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorTest(), and tests.commandTests.turtleQueryTests.YCoordinateTests.YCorAfterMoveTest().
Member Data Documentation
List<Double> commandParsing.CommandParser.expressionComponents = new ArrayList<Double>() protected
Definition at line 23 of file CommandParser.java.
Referenced by commandParsing.userCommandParsing.UserInstruction.accumulateComponents(), commandParsing.structuralCommandParsing.RecurringCommand.basicLoopVariableInitialization(), commandParsing.structuralCommandParsing.StructuralCommandOnBooleanSwitch.evaluateBooleanExpression(), commandParsing.structuralCommandParsing.For.initializeLoopVariableParameters(), commandParsing.turtleCommandParsing.turtleMovement.Rotate.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.Move.operateOnComponents(), commandParsing.colorCommandparsing.SetShapePalette.parse(), commandParsing.floatCommandParsing.FloatInputCommandParser.parse(), commandParsing.variableCommandParsing.MakeVariable.parse(), and commandParsing.userCommandParsing.UserInstruction.parse().
WorkspaceState commandParsing.CommandParser.workspace static protected
Definition at line 22 of file CommandParser.java.
Referenced by commandParsing.userCommandParsing.UserInstruction.accumulateComponents(), commandParsing.structuralCommandParsing.RecurringCommand.basicLoopVariableInitialization(), commandParsing.structuralCommandParsing.StructuralCommand.checkForClosingBrace(), commandParsing.structuralCommandParsing.StructuralCommand.checkForOpeningBrace(), commandParsing.structuralCommandParsing.AskWith.determineIfTurtleIsValidRecipient(), commandParsing.structuralCommandParsing.MultipleTurtleCommand.determineTurtlesToActivate(), commandParsing.structuralCommandParsing.StructuralCommand.extractCommandsBetweenBraces(), commandParsing.structuralCommandParsing.StructuralCommand.findBrace(), commandParsing.structuralCommandParsing.StructuralCommand.getVariable(), commandParsing.structuralCommandParsing.RecurringCommand.incrementLoopVariable(), commandParsing.structuralCommandParsing.For.initializeLoopVariableParameters(), commandParsing.structuralCommandParsing.DoTimes.initializeLoopVariableParameters(), commandParsing.structuralCommandParsing.RecurringCommand.loopVariableIsIncrementable(), commandParsing.structuralCommandParsing.MultipleTurtleCommand.makeAndActivateGivenTurtles(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetPenColor.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetPenSize.operateOnComponents(), commandParsing.colorCommandparsing.SetBackground.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetShape.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.Rotate.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetHeading.operateOnComponents(), commandParsing.turtleCommandParsing.ClearScreen.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetTowards.operateOnComponents(), commandParsing.colorCommandparsing.SetPalette.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.Move.operateOnComponents(), commandParsing.SetLanguage.parse(), commandParsing.structuralCommandParsing.Ask.parse(), commandParsing.structuralCommandParsing.Tell.parse(), commandParsing.turtleQueryParsing.ID.parse(), commandParsing.turtleQueryParsing.Turtles.parse(), commandParsing.turtleQueryParsing.Heading.parse(), commandParsing.turtleQueryParsing.XCoordinate.parse(), commandParsing.turtleQueryParsing.IsPenDown.parse(), commandParsing.turtleQueryParsing.YCoordinate.parse(), commandParsing.turtleQueryParsing.IsShowing.parse(), commandParsing.turtleQueryParsing.GetShape.parse(), commandParsing.turtleCommandParsing.turtleAttributeSetters.ShowTurtle.parse(), commandParsing.turtleQueryParsing.GetPenColor.parse(), commandParsing.turtleCommandParsing.turtleAttributeSetters.HideTurtle.parse(), commandParsing.turtleCommandParsing.turtleAttributeSetters.PenDown.parse(), commandParsing.structuralCommandParsing.AskWith.parse(), commandParsing.turtleCommandParsing.turtleAttributeSetters.PenUp.parse(), commandParsing.turtleCommandParsing.ClearStamps.parse(), commandParsing.turtleCommandParsing.Stamp.parse(), commandParsing.turtleCommandParsing.MakeTurtle.parse(), commandParsing.colorCommandparsing.SetShapePalette.parse(), commandParsing.variableCommandParsing.Variable.parse(), commandParsing.variableCommandParsing.MakeVariable.parse(), commandParsing.userCommandParsing.UserInstruction.parse(), commandParsing.userCommandParsing.MakeUserInstruction.parse(), commandParsing.structuralCommandParsing.StructuralCommand.parseCommandsBetweenBraces(), commandParsing.structuralCommandParsing.MultipleTurtleCommand.restoreActiveTurtles(), and commandParsing.structuralCommandParsing.MultipleTurtleCommand.saveCurrentActiveTurtles().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/commandParsing/CommandParser.java