slogo_team10: workspaceState.Pen Class Reference
workspaceState.Pen Class Reference
Public Member Functions
Pen ()
Pen (Pen pen)
void togglePenDown ()
void togglePenUp ()
boolean isPenDown ()
Color getPenColor ()
void setPenColor (Color myPenColor)
void setPenSize (double size)
double getPenSize ()
Private Attributes
boolean isPenDown
Color myPenColor
double thickness
Detailed Description
This class is the Pen class that contains all of the information about the Pen.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 12 of file Pen.java.
Constructor & Destructor Documentation
workspaceState.Pen.Pen ()
Definition at line 18 of file Pen.java.
workspaceState.Pen.Pen (Pen pen)
Definition at line 24 of file Pen.java.
References workspaceState.Pen.isPenDown, workspaceState.Pen.myPenColor, and workspaceState.Pen.thickness.
Member Function Documentation
Color workspaceState.Pen.getPenColor ()
Definition at line 42 of file Pen.java.
References workspaceState.Pen.myPenColor.
Referenced by commandParsing.drawableObectGenerationInterfaces.LineGenerator.generateDrawableObjectRepresentingLine(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), and tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest().
double workspaceState.Pen.getPenSize ()
Definition at line 54 of file Pen.java.
References workspaceState.Pen.thickness.
Referenced by commandParsing.drawableObectGenerationInterfaces.LineGenerator.generateDrawableObjectRepresentingLine(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), and tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest().
boolean workspaceState.Pen.isPenDown ()
Definition at line 38 of file Pen.java.
void workspaceState.Pen.setPenColor (Color myPenColor)
Definition at line 46 of file Pen.java.
References workspaceState.Pen.myPenColor.
void workspaceState.Pen.setPenSize (double size)
Definition at line 50 of file Pen.java.
void workspaceState.Pen.togglePenDown ()
Definition at line 30 of file Pen.java.
void workspaceState.Pen.togglePenUp ()
Definition at line 34 of file Pen.java.
Member Data Documentation
boolean workspaceState.Pen.isPenDown private
Definition at line 14 of file Pen.java.
Referenced by tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), commandParsing.turtleQueryParsing.IsPenDown.parse(), workspaceState.Pen.Pen(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), and tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest().
Color workspaceState.Pen.myPenColor private
Definition at line 15 of file Pen.java.
Referenced by workspaceState.Pen.getPenColor(), workspaceState.Pen.Pen(), and workspaceState.Pen.setPenColor().
double workspaceState.Pen.thickness private
Definition at line 16 of file Pen.java.
Referenced by workspaceState.Pen.getPenSize(), and workspaceState.Pen.Pen().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/workspaceState/Pen.java