slogo_team10: Control.SlogoControl Class Reference
Control.SlogoControl Class Reference
Public Member Functions
SlogoControl (Stage stage)
void createWorkspaceState (int workspaceID)
void setActiveWorkspaceState (int workspaceID)
Queue< DrawableObject > parseCommandString (String command)
void drawDrawableObjects (Queue< DrawableObject > objects)
Static Public Attributes
static final String NEW_TURTLE_COMMAND = "mk"
Private Member Functions
String sanitize (String command)
Private Attributes
GUIController myGUI
WorkspaceState activeState
Map< Integer, WorkspaceState > myWorkspaceStates
Detailed Description
Class sets up the control that separates the front-end and the back-end The class implements both SlogoGraphics and SlogoBackend interfaces and delivers an instance of itself to the GUIController and BackEndController
Author
akyker20, steven, stanley, allankiplagat
Definition at line 36 of file SlogoControl.java.
Constructor & Destructor Documentation
Control.SlogoControl.SlogoControl (Stage stage)
Initializes the GUIController and BackEndController, providing a SlogoGraphics instance of itself to the front-end and a SlogoBackEnd instance of itself to the back-end
Parameters
stage
Exceptions
RunTimeNullPointerException
RunTimeDivideByZeroException
CompileTimeParsingException
IOException
SAXException
ParserConfigurationException
Definition at line 58 of file SlogoControl.java.
References Control.SlogoControl.parseCommandString().
Member Function Documentation
void Control.SlogoControl.createWorkspaceState (int workspaceID)
Creates a new workspace state.
Parameters
workspaceID
Implements Control.SlogoGraphics.
Definition at line 65 of file SlogoControl.java.
void Control.SlogoControl.drawDrawableObjects (Queue< DrawableObject > objects)
This method delivers the Queue of DrawableObjects to the front-end, that have been created after parsing of String commands
Parameters
objects
Implements Control.SlogoBackend.
Definition at line 117 of file SlogoControl.java.
References gui.mainclasses.GUIController.drawDrawableObjects().
Referenced by Control.SlogoControl.parseCommandString().
Queue<DrawableObject> Control.SlogoControl.parseCommandString (String command)
Methods delivers a String command to the back-end to be parsed into a Queue of DrawableObjects that can be translated in to shapes that are displayed on the screen
Parameters
command
Returns
Exceptions
IOException
RunTimeNullPointerException
RunTimeDivideByZeroException
CompileTimeParsingException
Implements Control.SlogoGraphics.
Definition at line 81 of file SlogoControl.java.
References Control.SlogoControl.activeState, gui.mainclasses.workspace.Workspace.addPreviousCommand(), commandParsing.CommandParser.createParser(), Control.SlogoControl.drawDrawableObjects(), commandParsing.exceptions.CompileTimeParsingException.generateErrorMessage(), commandParsing.exceptions.SLOGOException.generateErrorMessage(), gui.mainclasses.workspace.WorkspaceManager.getActiveWorkspace(), gui.mainclasses.GUIController.getWorkspaceManager(), commandParsing.CommandParser.parse(), Control.SlogoControl.sanitize(), translator.Translator.translate(), and workspaceState.WorkspaceState.translator.
Referenced by Control.SlogoControl.SlogoControl().
String Control.SlogoControl.sanitize (String command) private
Definition at line 110 of file SlogoControl.java.
Referenced by Control.SlogoControl.parseCommandString().
void Control.SlogoControl.setActiveWorkspaceState (int workspaceID)
Lets the backend know which workspace is currently selected (which workspace is being viewed by the user).
Parameters
workspaceID
Implements Control.SlogoGraphics.
Definition at line 76 of file SlogoControl.java.
Member Data Documentation
WorkspaceState Control.SlogoControl.activeState private
Definition at line 41 of file SlogoControl.java.
Referenced by Control.SlogoControl.parseCommandString().
GUIController Control.SlogoControl.myGUI private
Definition at line 40 of file SlogoControl.java.
Map<Integer, WorkspaceState> Control.SlogoControl.myWorkspaceStates private
Definition at line 42 of file SlogoControl.java.
final String Control.SlogoControl.NEW_TURTLE_COMMAND = "mk" static
Definition at line 38 of file SlogoControl.java.
Referenced by gui.menus.FileMenu.addTurtleToWorkspace().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/Control/SlogoControl.java