slogo_team10: commandParsing.drawableObectGenerationInterfaces.LineGenerator Interface Reference
commandParsing.drawableObectGenerationInterfaces.LineGenerator Interface Reference
Public Member Functions
default DrawableObject generateDrawableObjectRepresentingLine (Location initialLocation, Location finalLocation, Pen pen)
Detailed Description
This class generates the actual Line drawableObjects to give to the GUI.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 17 of file LineGenerator.java.
Member Function Documentation
default DrawableObject commandParsing.drawableObectGenerationInterfaces.LineGenerator.generateDrawableObjectRepresentingLine (Location initialLocation, Location finalLocation, Pen pen)
Definition at line 19 of file LineGenerator.java.
References gui.factories.LineFactory.DESTINATION, workspaceState.Location.generateLocationString(), workspaceState.Pen.getPenColor(), workspaceState.Pen.getPenSize(), gui.factories.LineFactory.LINE_COLOR, gui.factories.LineFactory.LINE_WIDTH, gui.factories.LineFactory.ORIGIN, gui.factories.LineFactory.PARENT, and gui.factories.LineFactory.TYPE.
Referenced by commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.operateOnComponents(), and commandParsing.turtleCommandParsing.turtleMovement.Move.operateOnComponents().
The documentation for this interface was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/commandParsing/drawableObectGenerationInterfaces/LineGenerator.java