slogo_team10: commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation Class Reference
commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation Class Reference abstract
Public Member Functions
MoveToLocation (WorkspaceState someWorkspace)
Public Member Functions inherited from commandParsing.floatCommandParsing.TwoInputFloatCommandParser
TwoInputFloatCommandParser (WorkspaceState someWorkspace)
Public Member Functions inherited from commandParsing.floatCommandParsing.FloatInputCommandParser
FloatInputCommandParser (WorkspaceState someWorkspace)
double parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Public Member Functions inherited from commandParsing.CommandParser
CommandParser (WorkspaceState someWorkspace)
abstract double parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Public Member Functions inherited from commandParsing.drawableObectGenerationInterfaces.LineGenerator
default DrawableObject generateDrawableObjectRepresentingLine (Location initialLocation, Location finalLocation, Pen pen)
Public Member Functions inherited from commandParsing.drawableObectGenerationInterfaces.TurtleGenerator
default DrawableObject generateDrawableObjectRepresentingTurtle (Turtle turtle)
default DrawableObject generateDrawableObjectRepresentingTurtleDeletion (Turtle turtle)
Protected Member Functions
double operateOnComponents (List< Double > components, Queue< DrawableObject > objectQueue) throws RunTimeDivideByZeroException
abstract Location getDestinationLocation (List< Double > components)
abstract double getDestinationHeading (WorkspaceState workspace)
Protected Member Functions inherited from commandParsing.floatCommandParsing.TwoInputFloatCommandParser
int getNumberOfArguments ()
abstract double operateOnComponents (List< Double > components, Queue< DrawableObject > objectQueue) throws RunTimeDivideByZeroException
Protected Member Functions inherited from commandParsing.floatCommandParsing.FloatInputCommandParser
abstract int getNumberOfArguments ()
abstract double operateOnComponents (List< Double > components, Queue< DrawableObject > objectQueue) throws RunTimeDivideByZeroException
Protected Member Functions inherited from commandParsing.CommandParser
void accumulateComponents (Iterator< String > commandStringIterator, int numberToAccumulate, Queue< DrawableObject > objectQueue) throws SLOGOException
boolean isStringParsableAsCommand (String string)
Private Member Functions
double distanceBetweenPoints (Location firstPoint, Location secondPoint)
Additional Inherited Members
Static Public Member Functions inherited from commandParsing.CommandParser
static CommandParser createParser (String commandName, WorkspaceState workspace) throws CompileTimeParsingException
Protected Attributes inherited from commandParsing.CommandParser
List< Double > expressionComponents = new ArrayList<Double>()
Static Protected Attributes inherited from commandParsing.CommandParser
static WorkspaceState workspace
Detailed Description
Definition at line 15 of file MoveToLocation.java.
Constructor & Destructor Documentation
commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.MoveToLocation (WorkspaceState someWorkspace)
Definition at line 18 of file MoveToLocation.java.
Member Function Documentation
double commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.distanceBetweenPoints (Location firstPoint, Location secondPoint) private
Definition at line 45 of file MoveToLocation.java.
References workspaceState.Location.getX(), and workspaceState.Location.getY().
Referenced by commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.operateOnComponents().
abstract double commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.getDestinationHeading (WorkspaceState workspace) abstract protected
Referenced by commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.operateOnComponents().
abstract Location commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.getDestinationLocation (List< Double > components) abstract protected
Referenced by commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.operateOnComponents().
double commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.operateOnComponents (List< Double > components, Queue< DrawableObject > objectQueue) throws RunTimeDivideByZeroException protected
Definition at line 23 of file MoveToLocation.java.
References workspaceState.Location.add(), commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.distanceBetweenPoints(), commandParsing.drawableObectGenerationInterfaces.LineGenerator.generateDrawableObjectRepresentingLine(), commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtle(), workspaceState.TurtleCollection.getActiveTurtles(), commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.getDestinationHeading(), commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.getDestinationLocation(), workspaceState.WorkspaceState.turtles, and commandParsing.CommandParser.workspace.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/commandParsing/turtleCommandParsing/turtleMovement/MoveToLocation.java