slogo_team10: workspaceState.UserDefinedCommandCollection Class Reference
workspaceState.UserDefinedCommandCollection Class Reference
Classes
class Command
Public Member Functions
void storeUserDefinedCommand (String name, int numArgs, List< String > commands, List< String > parameters)
Command fetchUserDefinedCommand (String name) throws RunTimeNullPointerException
Private Attributes
Map< String, Command > commandMap = new HashMap<String, Command>()
Detailed Description
This class contains all of the information for the user-defined Commands, and is where we edit or modify them.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 17 of file UserDefinedCommandCollection.java.
Member Function Documentation
Command workspaceState.UserDefinedCommandCollection.fetchUserDefinedCommand (String name) throws RunTimeNullPointerException
Definition at line 25 of file UserDefinedCommandCollection.java.
Referenced by tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), commandParsing.userCommandParsing.UserInstruction.parse(), and commandParsing.userCommandParsing.MakeUserInstruction.parse().
void workspaceState.UserDefinedCommandCollection.storeUserDefinedCommand (String name, int numArgs, List< String > commands, List< String > parameters)
Definition at line 20 of file UserDefinedCommandCollection.java.
Referenced by commandParsing.userCommandParsing.MakeUserInstruction.parse().
Member Data Documentation
Map<String, Command> workspaceState.UserDefinedCommandCollection.commandMap = new HashMap<String, Command>() private
Definition at line 18 of file UserDefinedCommandCollection.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/workspaceState/UserDefinedCommandCollection.java