slogo_team10: workspaceState.Location Class Reference
workspaceState.Location Class Reference
Public Member Functions
Location (double x, double y)
Location (Location location)
void add (double x, double y)
double getX ()
double getY ()
void add (Location loc)
String generateLocationString ()
Private Attributes
double xLocation
double yLocation
Detailed Description
This class is the Location class.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 14 of file Location.java.
Constructor & Destructor Documentation
workspaceState.Location.Location (double x, double y)
Definition at line 19 of file Location.java.
workspaceState.Location.Location (Location location)
Definition at line 24 of file Location.java.
References workspaceState.Location.getX(), and workspaceState.Location.getY().
Member Function Documentation
void workspaceState.Location.add (double x, double y)
Definition at line 29 of file Location.java.
Referenced by workspaceState.Location.generateLocationString(), workspaceState.Turtle.move(), commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.operateOnComponents(), and commandParsing.turtleCommandParsing.turtleMovement.Move.operateOnComponents().
void workspaceState.Location.add (Location loc)
Definition at line 42 of file Location.java.
References workspaceState.Location.xLocation, and workspaceState.Location.yLocation.
String workspaceState.Location.generateLocationString ()
Definition at line 47 of file Location.java.
References workspaceState.Location.add().
Referenced by commandParsing.drawableObectGenerationInterfaces.LineGenerator.generateDrawableObjectRepresentingLine(), and commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtle().
double workspaceState.Location.getX ()
Definition at line 34 of file Location.java.
References workspaceState.Location.xLocation.
Referenced by commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.distanceBetweenPoints(), workspaceState.Turtle.getTurtleXLocation(), workspaceState.Location.Location(), and commandParsing.turtleCommandParsing.turtleAttributeSetters.SetTowards.vectorFromTwoPoints().
double workspaceState.Location.getY ()
Definition at line 38 of file Location.java.
References workspaceState.Location.yLocation.
Referenced by commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.distanceBetweenPoints(), workspaceState.Turtle.getTurtleYLocation(), workspaceState.Location.Location(), and commandParsing.turtleCommandParsing.turtleAttributeSetters.SetTowards.vectorFromTwoPoints().
Member Data Documentation
double workspaceState.Location.xLocation private
Definition at line 16 of file Location.java.
Referenced by workspaceState.Location.add(), and workspaceState.Location.getX().
double workspaceState.Location.yLocation private
Definition at line 17 of file Location.java.
Referenced by workspaceState.Location.add(), and workspaceState.Location.getY().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/workspaceState/Location.java