slogo_team10: gui.mainclasses.TextGenerator Class Reference
gui.mainclasses.TextGenerator Class Reference
Static Public Member Functions
static String get (String text)
static void setLanguage (String language)
Static Public Attributes
static final String SLOGO = "slogo"
static final String FILE = "file"
static final String LOAD_WORKSPACE = "loadWorkspace"
static final String SAVE_WORKSPACE = "saveWorkspace"
static final String NEW_WORKSPACE = "newWorkspace"
static final String SELECT_XMLFILE = "selectXMLFile"
static final String EDIT = "edit"
static final String PREFERENCES = "preferences"
static final String HELP = "help"
static final String GETTING_STARTED = "gettingStarted"
static final String BASIC_COMMANDS = "basicCommands"
static final String COMPLEX_COMMANDS = "complexCommands"
static final String WORKSPACE_LABEL = "workspace"
static final String TURTLE_SCREEN = "turtleScreen"
static final String PREVIOUS_COMMANDS = "previousCommands"
static final String COMMAND_LINE = "commandLine"
static final String ERRORS = "errors"
static final String WORKSPACE_VARIABLES = "workspaceVariables"
static final String VARIABLE = "variable"
static final String VALUE = "value"
static final String COMMANDS = "commands"
static final String SAVED = "saved"
static final String USER_DEFINED = "userDefined"
static final String NAME = "name"
static final String PARAMETERS = "parameters"
static final String OPTIONS = "options"
static final String GENERAL = "general"
static final String PEN = "pen"
static final String COLORS = "colors"
static final String IMAGES = "images"
static final String TOGGLE_GRID = "toggleGrid"
static final String SAVE_COMMAND = "saveCommand"
static final String CLEAR_WORKSPACE = "clearWorkspace"
static final String IMAGE_DROP_AREA = "imageDropArea"
static final String UP = "up"
static final String DOWN = "down"
static final String INDEX = "index"
static final String COLOR = "color"
static final String IMAGE = "image"
static final String CHINESE = "Chinese"
static final String ENGLISH = "English"
static final String FRENCH = "French"
static final String ITALIAN = "Italian"
Static Package Functions
[static initializer]
Static Private Member Functions
static ResourceBundle getResourceBundle (String language)
Static Private Attributes
static Map< String, Locale > supportedLocales = new HashMap<String, Locale>()
static ResourceBundle myLanguagesBundle = getResourceBundle(ENGLISH)
Detailed Description
Class generates the text to be displayed on the GUI using resource bundles
Author
allankiplagat
Definition at line 13 of file TextGenerator.java.
Member Function Documentation
gui.mainclasses.TextGenerator.[static initializer] () static package
static String gui.mainclasses.TextGenerator.get (String text) static
Definition at line 85 of file TextGenerator.java.
Referenced by gui.mainclasses.workspace.WorkspaceManager.addWorkspace(), gui.buttonfeatures.ButtonFeature.ButtonFeature(), gui.nonbuttonfeatures.tableviews.colorindex.ColorIndexFeature.ColorIndexFeature(), gui.componentdrawers.optionsholder.tabs.ColorIndexTab.ColorIndexTab(), gui.componentdrawers.CommandLineDrawer.CommandLineDrawer(), gui.menus.FileMenu.createFileChooser(), gui.componentdrawers.ErrorDrawer.ErrorDrawer(), gui.menus.FileMenu.FileMenu(), gui.componentdrawers.optionsholder.tabs.GeneralOptionsTab.GeneralOptionsTab(), gui.menus.HelpMenu.HelpMenu(), gui.nonbuttonfeatures.tableviews.imageindex.ImageIndexFeature.ImageIndexFeature(), gui.componentdrawers.optionsholder.tabs.ImageIndexTab.ImageIndexTab(), gui.mainclasses.StageInitializer.init(), gui.componentdrawers.optionsholder.OptionsHolderDrawer.OptionsHolderDrawer(), gui.componentdrawers.optionsholder.tabs.PenOptionsTab.PenOptionsTab(), gui.nonbuttonfeatures.pen.PenUpOrDownFeature.PenUpOrDownFeature(), gui.componentdrawers.PreviousCommandsDrawer.PreviousCommandsDrawer(), gui.componentdrawers.significantcommands.tabs.SavedCommandsTab.SavedCommandsTab(), gui.componentdrawers.significantcommands.SignificantCommandsDrawer.SignificantCommandsDrawer(), gui.nonbuttonfeatures.TurtleImageFeature.TurtleImageFeature(), gui.componentdrawers.TurtleScreenDrawer.TurtleScreenDrawer(), gui.nonbuttonfeatures.tableviews.UserDefinedCommandsFeature.UserDefinedCommandsFeature(), gui.componentdrawers.significantcommands.tabs.UserDefinedCommandsTab.UserDefinedCommandsTab(), gui.componentdrawers.WorkspaceVariablesDrawer.WorkspaceVariablesDrawer(), and gui.nonbuttonfeatures.tableviews.variables.WorkspaceVariablesFeature.WorkspaceVariablesFeature().
static ResourceBundle gui.mainclasses.TextGenerator.getResourceBundle (String language) static private
Definition at line 80 of file TextGenerator.java.
Referenced by gui.mainclasses.TextGenerator.setLanguage().
static void gui.mainclasses.TextGenerator.setLanguage (String language) static
Definition at line 89 of file TextGenerator.java.
References gui.mainclasses.TextGenerator.getResourceBundle().
Referenced by gui.menus.FileMenu.FileMenu().
Member Data Documentation
final String gui.mainclasses.TextGenerator.BASIC_COMMANDS = "basicCommands" static
Definition at line 28 of file TextGenerator.java.
Referenced by gui.menus.HelpMenu.HelpMenu().
final String gui.mainclasses.TextGenerator.CHINESE = "Chinese" static
Definition at line 64 of file TextGenerator.java.
Referenced by gui.menus.FileMenu.FileMenu().
final String gui.mainclasses.TextGenerator.CLEAR_WORKSPACE = "clearWorkspace" static
Definition at line 56 of file TextGenerator.java.
Referenced by gui.buttonfeatures.ClearWorkspaceButtonFeature.ClearWorkspaceButtonFeature().
final String gui.mainclasses.TextGenerator.COLOR = "color" static
Definition at line 61 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.tableviews.colorindex.ColorIndexFeature.ColorIndexFeature().
final String gui.mainclasses.TextGenerator.COLORS = "colors" static
Definition at line 52 of file TextGenerator.java.
Referenced by gui.componentdrawers.optionsholder.tabs.ColorIndexTab.ColorIndexTab().
final String gui.mainclasses.TextGenerator.COMMAND_LINE = "commandLine" static
Definition at line 35 of file TextGenerator.java.
Referenced by gui.componentdrawers.CommandLineDrawer.CommandLineDrawer().
final String gui.mainclasses.TextGenerator.COMMANDS = "commands" static
Definition at line 43 of file TextGenerator.java.
Referenced by gui.componentdrawers.significantcommands.SignificantCommandsDrawer.SignificantCommandsDrawer().
final String gui.mainclasses.TextGenerator.COMPLEX_COMMANDS = "complexCommands" static
Definition at line 29 of file TextGenerator.java.
Referenced by gui.menus.HelpMenu.HelpMenu().
final String gui.mainclasses.TextGenerator.DOWN = "down" static
Definition at line 59 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.pen.PenUpOrDownFeature.PenUpOrDownFeature().
final String gui.mainclasses.TextGenerator.EDIT = "edit" static
Definition at line 23 of file TextGenerator.java.
final String gui.mainclasses.TextGenerator.ENGLISH = "English" static
Definition at line 65 of file TextGenerator.java.
Referenced by gui.menus.FileMenu.FileMenu().
final String gui.mainclasses.TextGenerator.ERRORS = "errors" static
Definition at line 37 of file TextGenerator.java.
Referenced by gui.componentdrawers.ErrorDrawer.ErrorDrawer().
final String gui.mainclasses.TextGenerator.FILE = "file" static
Definition at line 17 of file TextGenerator.java.
Referenced by gui.menus.FileMenu.FileMenu().
final String gui.mainclasses.TextGenerator.FRENCH = "French" static
Definition at line 66 of file TextGenerator.java.
Referenced by gui.menus.FileMenu.FileMenu().
final String gui.mainclasses.TextGenerator.GENERAL = "general" static
Definition at line 50 of file TextGenerator.java.
Referenced by gui.componentdrawers.optionsholder.tabs.GeneralOptionsTab.GeneralOptionsTab().
final String gui.mainclasses.TextGenerator.GETTING_STARTED = "gettingStarted" static
Definition at line 27 of file TextGenerator.java.
Referenced by gui.menus.HelpMenu.HelpMenu().
final String gui.mainclasses.TextGenerator.HELP = "help" static
Definition at line 26 of file TextGenerator.java.
Referenced by gui.menus.HelpMenu.HelpMenu().
final String gui.mainclasses.TextGenerator.IMAGE = "image" static
Definition at line 62 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.tableviews.imageindex.ImageIndexFeature.ImageIndexFeature().
final String gui.mainclasses.TextGenerator.IMAGE_DROP_AREA = "imageDropArea" static
Definition at line 57 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.TurtleImageFeature.TurtleImageFeature().
final String gui.mainclasses.TextGenerator.IMAGES = "images" static
Definition at line 53 of file TextGenerator.java.
Referenced by gui.componentdrawers.optionsholder.tabs.ImageIndexTab.ImageIndexTab().
final String gui.mainclasses.TextGenerator.INDEX = "index" static
Definition at line 60 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.tableviews.colorindex.ColorIndexFeature.ColorIndexFeature(), and gui.nonbuttonfeatures.tableviews.imageindex.ImageIndexFeature.ImageIndexFeature().
final String gui.mainclasses.TextGenerator.ITALIAN = "Italian" static
Definition at line 67 of file TextGenerator.java.
final String gui.mainclasses.TextGenerator.LOAD_WORKSPACE = "loadWorkspace" static
Definition at line 18 of file TextGenerator.java.
Referenced by gui.menus.FileMenu.FileMenu().
ResourceBundle gui.mainclasses.TextGenerator.myLanguagesBundle = getResourceBundle(ENGLISH) static private
Definition at line 78 of file TextGenerator.java.
final String gui.mainclasses.TextGenerator.NAME = "name" static
Definition at line 46 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.tableviews.UserDefinedCommandsFeature.UserDefinedCommandsFeature().
final String gui.mainclasses.TextGenerator.NEW_WORKSPACE = "newWorkspace" static
Definition at line 20 of file TextGenerator.java.
Referenced by gui.menus.FileMenu.FileMenu().
final String gui.mainclasses.TextGenerator.OPTIONS = "options" static
Definition at line 49 of file TextGenerator.java.
Referenced by gui.componentdrawers.optionsholder.OptionsHolderDrawer.OptionsHolderDrawer().
final String gui.mainclasses.TextGenerator.PARAMETERS = "parameters" static
Definition at line 47 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.tableviews.UserDefinedCommandsFeature.UserDefinedCommandsFeature().
final String gui.mainclasses.TextGenerator.PEN = "pen" static
Definition at line 51 of file TextGenerator.java.
Referenced by gui.componentdrawers.optionsholder.tabs.PenOptionsTab.PenOptionsTab().
final String gui.mainclasses.TextGenerator.PREFERENCES = "preferences" static
Definition at line 24 of file TextGenerator.java.
final String gui.mainclasses.TextGenerator.PREVIOUS_COMMANDS = "previousCommands" static
Definition at line 34 of file TextGenerator.java.
Referenced by gui.componentdrawers.PreviousCommandsDrawer.PreviousCommandsDrawer().
final String gui.mainclasses.TextGenerator.SAVE_COMMAND = "saveCommand" static
Definition at line 55 of file TextGenerator.java.
Referenced by gui.buttonfeatures.SaveCommandButtonFeature.SaveCommandButtonFeature().
final String gui.mainclasses.TextGenerator.SAVE_WORKSPACE = "saveWorkspace" static
Definition at line 19 of file TextGenerator.java.
Referenced by gui.menus.FileMenu.FileMenu().
final String gui.mainclasses.TextGenerator.SAVED = "saved" static
Definition at line 44 of file TextGenerator.java.
Referenced by gui.componentdrawers.significantcommands.tabs.SavedCommandsTab.SavedCommandsTab().
final String gui.mainclasses.TextGenerator.SELECT_XMLFILE = "selectXMLFile" static
Definition at line 21 of file TextGenerator.java.
Referenced by gui.menus.FileMenu.createFileChooser().
final String gui.mainclasses.TextGenerator.SLOGO = "slogo" static
Definition at line 15 of file TextGenerator.java.
Referenced by gui.mainclasses.StageInitializer.init().
Map<String, Locale> gui.mainclasses.TextGenerator.supportedLocales = new HashMap<String, Locale>() static private
Definition at line 69 of file TextGenerator.java.
final String gui.mainclasses.TextGenerator.TOGGLE_GRID = "toggleGrid" static
Definition at line 54 of file TextGenerator.java.
Referenced by gui.buttonfeatures.ToggleGridButtonFeature.ToggleGridButtonFeature().
final String gui.mainclasses.TextGenerator.TURTLE_SCREEN = "turtleScreen" static
Definition at line 33 of file TextGenerator.java.
Referenced by gui.componentdrawers.TurtleScreenDrawer.TurtleScreenDrawer().
final String gui.mainclasses.TextGenerator.UP = "up" static
Definition at line 58 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.pen.PenUpOrDownFeature.PenUpOrDownFeature().
final String gui.mainclasses.TextGenerator.USER_DEFINED = "userDefined" static
Definition at line 45 of file TextGenerator.java.
Referenced by gui.componentdrawers.significantcommands.tabs.UserDefinedCommandsTab.UserDefinedCommandsTab().
final String gui.mainclasses.TextGenerator.VALUE = "value" static
Definition at line 41 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.tableviews.variables.WorkspaceVariablesFeature.WorkspaceVariablesFeature().
final String gui.mainclasses.TextGenerator.VARIABLE = "variable" static
Definition at line 40 of file TextGenerator.java.
Referenced by gui.nonbuttonfeatures.tableviews.variables.WorkspaceVariablesFeature.WorkspaceVariablesFeature().
final String gui.mainclasses.TextGenerator.WORKSPACE_LABEL = "workspace" static
Definition at line 31 of file TextGenerator.java.
Referenced by gui.mainclasses.workspace.WorkspaceManager.addWorkspace().
final String gui.mainclasses.TextGenerator.WORKSPACE_VARIABLES = "workspaceVariables" static
Definition at line 39 of file TextGenerator.java.
Referenced by gui.componentdrawers.WorkspaceVariablesDrawer.WorkspaceVariablesDrawer().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/mainclasses/TextGenerator.java