slogo_team10: gui.mainclasses.workspace.WorkspaceDataHolder Class Reference
gui.mainclasses.workspace.WorkspaceDataHolder Class Reference
Public Member Functions
WorkspaceDataHolder ()
WorkspaceDataHolder (ObservableList< WorkspaceVariable > myVariablesList, ObservableList< String > myPreviousCommandsList, ObservableList< DisplayedUserCommand > myUserDefinedCommandList, ObservableList< String > mySavedCommandsList, ObservableList< ColorIndex > myColorIndexList, ObservableList< ImageIndex > myImageIndexList)
ObservableList< WorkspaceVariable > getMyVariablesList ()
ObservableList< String > getMyPreviousCommandsList ()
ObservableList< DisplayedUserCommand > getMyUserDefinedCommandList ()
ObservableList< String > getMySavedCommandsList ()
ObservableList< ColorIndex > getMyColorIndexList ()
ObservableList< ImageIndex > getMyImageIndexList ()
void clear ()
Private Attributes
ObservableList< WorkspaceVariable > myVariablesList
ObservableList< String > myPreviousCommandsList
ObservableList< DisplayedUserCommand > myUserDefinedCommandList
ObservableList< String > mySavedCommandsList
ObservableList< ColorIndex > myColorIndexList
ObservableList< ImageIndex > myImageIndexList
Detailed Description
Class hosts the data for a workspace
Author
akyker20, allankiplagat
Definition at line 15 of file WorkspaceDataHolder.java.
Constructor & Destructor Documentation
gui.mainclasses.workspace.WorkspaceDataHolder.WorkspaceDataHolder ()
Default constructor
Definition at line 26 of file WorkspaceDataHolder.java.
gui.mainclasses.workspace.WorkspaceDataHolder.WorkspaceDataHolder (ObservableList< WorkspaceVariable > myVariablesList, ObservableList< String > myPreviousCommandsList, ObservableList< DisplayedUserCommand > myUserDefinedCommandList, ObservableList< String > mySavedCommandsList, ObservableList< ColorIndex > myColorIndexList, ObservableList< ImageIndex > myImageIndexList)
Parameters
myVariablesList
myPreviousCommandsList
myUserDefinedCommandList
mySavedCommandsList
myColorIndexList
Definition at line 43 of file WorkspaceDataHolder.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.myColorIndexList, gui.mainclasses.workspace.WorkspaceDataHolder.myImageIndexList, gui.mainclasses.workspace.WorkspaceDataHolder.myPreviousCommandsList, gui.mainclasses.workspace.WorkspaceDataHolder.mySavedCommandsList, gui.mainclasses.workspace.WorkspaceDataHolder.myUserDefinedCommandList, and gui.mainclasses.workspace.WorkspaceDataHolder.myVariablesList.
Member Function Documentation
void gui.mainclasses.workspace.WorkspaceDataHolder.clear ()
Definition at line 81 of file WorkspaceDataHolder.java.
Referenced by gui.mainclasses.workspace.Workspace.clear().
ObservableList<ColorIndex> gui.mainclasses.workspace.WorkspaceDataHolder.getMyColorIndexList ()
Definition at line 73 of file WorkspaceDataHolder.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.myColorIndexList.
Referenced by gui.mainclasses.FactoryBuilder.init(), and gui.mainclasses.FeatureBuilder.init().
ObservableList<ImageIndex> gui.mainclasses.workspace.WorkspaceDataHolder.getMyImageIndexList ()
Definition at line 77 of file WorkspaceDataHolder.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.myImageIndexList.
Referenced by gui.mainclasses.FactoryBuilder.init(), and gui.mainclasses.FeatureBuilder.init().
ObservableList<String> gui.mainclasses.workspace.WorkspaceDataHolder.getMyPreviousCommandsList ()
Definition at line 61 of file WorkspaceDataHolder.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.myPreviousCommandsList.
Referenced by gui.mainclasses.workspace.Workspace.addPreviousCommand(), and gui.mainclasses.FeatureBuilder.init().
ObservableList<String> gui.mainclasses.workspace.WorkspaceDataHolder.getMySavedCommandsList ()
Definition at line 69 of file WorkspaceDataHolder.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.mySavedCommandsList.
Referenced by gui.mainclasses.FeatureBuilder.init().
ObservableList<DisplayedUserCommand> gui.mainclasses.workspace.WorkspaceDataHolder.getMyUserDefinedCommandList ()
Definition at line 65 of file WorkspaceDataHolder.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.myUserDefinedCommandList.
Referenced by gui.mainclasses.FactoryBuilder.init().
ObservableList<WorkspaceVariable> gui.mainclasses.workspace.WorkspaceDataHolder.getMyVariablesList ()
Definition at line 57 of file WorkspaceDataHolder.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.myVariablesList.
Referenced by gui.mainclasses.FactoryBuilder.init(), and gui.mainclasses.FeatureBuilder.init().
Member Data Documentation
ObservableList<ColorIndex> gui.mainclasses.workspace.WorkspaceDataHolder.myColorIndexList private
Definition at line 20 of file WorkspaceDataHolder.java.
Referenced by gui.mainclasses.workspace.WorkspaceDataHolder.getMyColorIndexList(), and gui.mainclasses.workspace.WorkspaceDataHolder.WorkspaceDataHolder().
ObservableList<ImageIndex> gui.mainclasses.workspace.WorkspaceDataHolder.myImageIndexList private
Definition at line 21 of file WorkspaceDataHolder.java.
Referenced by gui.mainclasses.workspace.WorkspaceDataHolder.getMyImageIndexList(), and gui.mainclasses.workspace.WorkspaceDataHolder.WorkspaceDataHolder().
ObservableList<String> gui.mainclasses.workspace.WorkspaceDataHolder.myPreviousCommandsList private
Definition at line 17 of file WorkspaceDataHolder.java.
Referenced by gui.mainclasses.workspace.WorkspaceDataHolder.getMyPreviousCommandsList(), and gui.mainclasses.workspace.WorkspaceDataHolder.WorkspaceDataHolder().
ObservableList<String> gui.mainclasses.workspace.WorkspaceDataHolder.mySavedCommandsList private
Definition at line 19 of file WorkspaceDataHolder.java.
Referenced by gui.mainclasses.workspace.WorkspaceDataHolder.getMySavedCommandsList(), and gui.mainclasses.workspace.WorkspaceDataHolder.WorkspaceDataHolder().
ObservableList<DisplayedUserCommand> gui.mainclasses.workspace.WorkspaceDataHolder.myUserDefinedCommandList private
Definition at line 18 of file WorkspaceDataHolder.java.
Referenced by gui.mainclasses.workspace.WorkspaceDataHolder.getMyUserDefinedCommandList(), and gui.mainclasses.workspace.WorkspaceDataHolder.WorkspaceDataHolder().
ObservableList<WorkspaceVariable> gui.mainclasses.workspace.WorkspaceDataHolder.myVariablesList private
Definition at line 16 of file WorkspaceDataHolder.java.
Referenced by gui.mainclasses.workspace.WorkspaceDataHolder.getMyVariablesList(), and gui.mainclasses.workspace.WorkspaceDataHolder.WorkspaceDataHolder().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/mainclasses/workspace/WorkspaceDataHolder.java