slogo_team10: gui.mainclasses.workspace.Workspace Class Reference
gui.mainclasses.workspace.Workspace Class Reference
Public Member Functions
Workspace (SlogoGraphics control, WorkspaceScreenParameters screenParams, WorkspaceDataHolder dataHolder, int id)
void parseCommandString (String command)
void moveActiveTurtles (KeyEvent event)
void addPreviousCommand (String command)
void clear ()
void parseDrawableObject (DrawableObject poll)
void notifyOfTurtleSelectionChange ()
int getWorkspaceID ()
WorkspaceDataHolder getDataHolder ()
WorkspaceScreenParameters getScreenParams ()
Private Member Functions
BorderPane createPane ()
Private Attributes
SlogoGraphics myControl
TurtleNodes myTurtleNodes
Map< String, ComponentDrawer > myComponentDrawers
ObjectFactory[] myObjectFactories
WorkspaceDataHolder myDataHolder
TurtleScreenDrawer myTurtleScreenDrawer
BorderPane myPane
int myID
Static Private Attributes
static String FORWARD_COMMAND = "fd 10"
static String BACK_COMMAND = "bk 10"
static String RIGHT_COMMAND = "right 90"
static String LEFT_COMMAND = "left 90"
Detailed Description
Class manages a single workspace that hosts
Author
akyker20, allankiplagat
Definition at line 30 of file Workspace.java.
Constructor & Destructor Documentation
gui.mainclasses.workspace.Workspace.Workspace (SlogoGraphics control, WorkspaceScreenParameters screenParams, WorkspaceDataHolder dataHolder, int id)
Definition at line 46 of file Workspace.java.
References gui.componentdrawers.ComponentBuilder.build(), gui.mainclasses.workspace.Workspace.createPane(), gui.mainclasses.FactoryBuilder.init(), gui.mainclasses.FeatureBuilder.init(), and gui.componentdrawers.ComponentBuilder.SCREEN_DRAWER.
Member Function Documentation
void gui.mainclasses.workspace.Workspace.addPreviousCommand (String command)
Adds a command to the previous commands list view. Adds the command to the front of the list so it will be displayed first in the view.
Parameters
command
Definition at line 115 of file Workspace.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.getMyPreviousCommandsList().
Referenced by Control.SlogoControl.parseCommandString().
void gui.mainclasses.workspace.Workspace.clear ()
Clears the current workspace by removing the workspace variables as well as the previous command log. This is called when the user clicks the ClearWorkspace button feature in the options TabPane.
Definition at line 124 of file Workspace.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.clear().
Referenced by gui.buttonfeatures.ClearWorkspaceButtonFeature.ClearWorkspaceButtonFeature().
BorderPane gui.mainclasses.workspace.Workspace.createPane () private
Definition at line 63 of file Workspace.java.
References gui.mainclasses.StageInitializer.SCREEN_HEIGHT, and gui.mainclasses.StageInitializer.SCREEN_WIDTH.
Referenced by gui.mainclasses.workspace.Workspace.Workspace().
WorkspaceDataHolder gui.mainclasses.workspace.Workspace.getDataHolder ()
Returns the data holder. Used by the xml writer to write the workspace configuration to a file for later use.
Returns
Definition at line 162 of file Workspace.java.
References gui.mainclasses.workspace.Workspace.myDataHolder.
Referenced by gui.menus.FileMenu.FileMenu().
WorkspaceScreenParameters gui.mainclasses.workspace.Workspace.getScreenParams ()
Definition at line 166 of file Workspace.java.
References gui.componentdrawers.TurtleScreenDrawer.getScreenParams().
Referenced by gui.menus.FileMenu.FileMenu().
int gui.mainclasses.workspace.Workspace.getWorkspaceID ()
Returns the workspace id of the workspace. This is necessary for the back-end to know which workspace is selected.
Returns
Definition at line 153 of file Workspace.java.
References gui.mainclasses.workspace.Workspace.myID.
void gui.mainclasses.workspace.Workspace.moveActiveTurtles (KeyEvent event)
Definition at line 80 of file Workspace.java.
References gui.mainclasses.workspace.Workspace.BACK_COMMAND, gui.mainclasses.workspace.Workspace.FORWARD_COMMAND, gui.factories.turtlefactory.TurtleNodes.getActiveNodes(), gui.mainclasses.workspace.Workspace.LEFT_COMMAND, Control.SlogoGraphics.parseCommandString(), and gui.mainclasses.workspace.Workspace.RIGHT_COMMAND.
Referenced by gui.mainclasses.GUIController.moveActiveTurtlesInActiveWorkspace().
void gui.mainclasses.workspace.Workspace.notifyOfTurtleSelectionChange ()
When a turtle is selected, the back-end is made aware of the change.
Definition at line 140 of file Workspace.java.
References gui.factories.turtlefactory.TurtleNodes.getActiveNodes(), and gui.mainclasses.workspace.Workspace.parseCommandString().
Referenced by gui.factories.turtlefactory.TurtleNode.selectTurtle().
void gui.mainclasses.workspace.Workspace.parseCommandString (String command)
Definition at line 69 of file Workspace.java.
References Control.SlogoGraphics.parseCommandString().
Referenced by gui.menus.FileMenu.addTurtleToWorkspace(), gui.nonbuttonfeatures.pen.PenColorPickerFeature.changePenColor(), gui.nonbuttonfeatures.CommandLineFeature.CommandLineFeature(), gui.nonbuttonfeatures.tableviews.variables.EditingCell.createTextField(), gui.menus.FileMenu.FileMenu(), gui.mainclasses.workspace.Workspace.notifyOfTurtleSelectionChange(), gui.nonbuttonfeatures.pen.PenUpOrDownFeature.PenUpOrDownFeature(), gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.setPenSize(), and gui.nonbuttonfeatures.TurtleImageFeature.TurtleImageFeature().
void gui.mainclasses.workspace.Workspace.parseDrawableObject (DrawableObject poll)
Method to convert a DrawableObject queue into shapes that can be drawn on the screen
Parameters
objectQueue
Definition at line 133 of file Workspace.java.
References gui.mainclasses.DrawableObjectParser.parseDrawableObject().
Referenced by gui.mainclasses.GUIController.drawDrawableObjects().
Member Data Documentation
String gui.mainclasses.workspace.Workspace.BACK_COMMAND = "bk 10" static private
Definition at line 42 of file Workspace.java.
Referenced by gui.mainclasses.workspace.Workspace.moveActiveTurtles().
String gui.mainclasses.workspace.Workspace.FORWARD_COMMAND = "fd 10" static private
Definition at line 41 of file Workspace.java.
Referenced by gui.mainclasses.workspace.Workspace.moveActiveTurtles().
String gui.mainclasses.workspace.Workspace.LEFT_COMMAND = "left 90" static private
Definition at line 44 of file Workspace.java.
Referenced by gui.mainclasses.workspace.Workspace.moveActiveTurtles().
Map<String, ComponentDrawer> gui.mainclasses.workspace.Workspace.myComponentDrawers private
Definition at line 34 of file Workspace.java.
SlogoGraphics gui.mainclasses.workspace.Workspace.myControl private
Definition at line 32 of file Workspace.java.
WorkspaceDataHolder gui.mainclasses.workspace.Workspace.myDataHolder private
Definition at line 36 of file Workspace.java.
Referenced by gui.mainclasses.workspace.Workspace.getDataHolder().
int gui.mainclasses.workspace.Workspace.myID private
Definition at line 39 of file Workspace.java.
Referenced by gui.mainclasses.workspace.Workspace.getWorkspaceID().
ObjectFactory [] gui.mainclasses.workspace.Workspace.myObjectFactories private
Definition at line 35 of file Workspace.java.
BorderPane gui.mainclasses.workspace.Workspace.myPane private
Definition at line 38 of file Workspace.java.
TurtleNodes gui.mainclasses.workspace.Workspace.myTurtleNodes private
Definition at line 33 of file Workspace.java.
TurtleScreenDrawer gui.mainclasses.workspace.Workspace.myTurtleScreenDrawer private
Definition at line 37 of file Workspace.java.
String gui.mainclasses.workspace.Workspace.RIGHT_COMMAND = "right 90" static private
Definition at line 43 of file Workspace.java.
Referenced by gui.mainclasses.workspace.Workspace.moveActiveTurtles().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/mainclasses/workspace/Workspace.java