slogo_team10: gui.mainclasses.workspace.WorkspaceManager Class Reference
gui.mainclasses.workspace.WorkspaceManager Class Reference
Public Member Functions
WorkspaceManager (SlogoGraphics control)
void addWorkspace (WorkspaceScreenParameters screenParams, WorkspaceDataHolder dataHolder)
Workspace getActiveWorkspace ()
Static Public Attributes
static Workspace myActiveWorkspace
Private Member Functions
void initializeTabPane ()
Private Attributes
SlogoGraphics myControl
Static Private Attributes
static int workspaceID = 0
Detailed Description
Class manages the workspace components that are presented in the GUI as tabs within this TabPane
Author
allankiplagat, akyker20
Definition at line 20 of file WorkspaceManager.java.
Constructor & Destructor Documentation
gui.mainclasses.workspace.WorkspaceManager.WorkspaceManager (SlogoGraphics control)
Definition at line 27 of file WorkspaceManager.java.
References gui.mainclasses.workspace.WorkspaceManager.addWorkspace(), and gui.mainclasses.workspace.WorkspaceManager.initializeTabPane().
Member Function Documentation
void gui.mainclasses.workspace.WorkspaceManager.addWorkspace (WorkspaceScreenParameters screenParams, WorkspaceDataHolder dataHolder)
Definition at line 50 of file WorkspaceManager.java.
References Control.SlogoGraphics.createWorkspaceState(), gui.mainclasses.TextGenerator.get(), Control.SlogoGraphics.setActiveWorkspaceState(), gui.mainclasses.TextGenerator.WORKSPACE_LABEL, and gui.mainclasses.workspace.WorkspaceManager.workspaceID.
Referenced by gui.menus.FileMenu.FileMenu(), and gui.mainclasses.workspace.WorkspaceManager.WorkspaceManager().
Workspace gui.mainclasses.workspace.WorkspaceManager.getActiveWorkspace ()
Definition at line 62 of file WorkspaceManager.java.
References gui.mainclasses.workspace.WorkspaceManager.myActiveWorkspace.
Referenced by gui.menus.FileMenu.addTurtleToWorkspace(), gui.mainclasses.GUIController.drawDrawableObjects(), gui.menus.FileMenu.FileMenu(), gui.mainclasses.GUIController.moveActiveTurtlesInActiveWorkspace(), and Control.SlogoControl.parseCommandString().
void gui.mainclasses.workspace.WorkspaceManager.initializeTabPane () private
Definition at line 33 of file WorkspaceManager.java.
References Control.SlogoGraphics.setActiveWorkspaceState().
Referenced by gui.mainclasses.workspace.WorkspaceManager.WorkspaceManager().
Member Data Documentation
Workspace gui.mainclasses.workspace.WorkspaceManager.myActiveWorkspace static
Definition at line 22 of file WorkspaceManager.java.
Referenced by gui.mainclasses.workspace.WorkspaceManager.getActiveWorkspace().
SlogoGraphics gui.mainclasses.workspace.WorkspaceManager.myControl private
Definition at line 25 of file WorkspaceManager.java.
int gui.mainclasses.workspace.WorkspaceManager.workspaceID = 0 static private
Definition at line 23 of file WorkspaceManager.java.
Referenced by gui.mainclasses.workspace.WorkspaceManager.addWorkspace().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/mainclasses/workspace/WorkspaceManager.java