slogo_team10: commandParsing.drawableObectGenerationInterfaces.UserDefinedVariableGenerator Interface Reference
commandParsing.drawableObectGenerationInterfaces.UserDefinedVariableGenerator Interface Reference
Public Member Functions
default DrawableObject generateDrawableObjectRepresentingVariable (WorkspaceVariable variable)
Detailed Description
This class generates the actual UserDefinedVariable drawableObjects to give to the GUI.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 16 of file UserDefinedVariableGenerator.java.
Member Function Documentation
default DrawableObject commandParsing.drawableObectGenerationInterfaces.UserDefinedVariableGenerator.generateDrawableObjectRepresentingVariable (WorkspaceVariable variable)
Definition at line 17 of file UserDefinedVariableGenerator.java.
References gui.variableslist.WorkspaceVariable.getMyName(), gui.variableslist.WorkspaceVariable.getMyValue(), gui.factories.WorkspaceVariableFactory.NAME, gui.factories.WorkspaceVariableFactory.PARENT, gui.factories.WorkspaceVariableFactory.TYPE, and gui.factories.WorkspaceVariableFactory.VALUE.
Referenced by commandParsing.structuralCommandParsing.RecurringCommand.basicLoopVariableInitialization(), commandParsing.structuralCommandParsing.RecurringCommand.incrementLoopVariable(), commandParsing.structuralCommandParsing.For.initializeLoopVariableParameters(), commandParsing.variableCommandParsing.MakeVariable.parse(), and commandParsing.userCommandParsing.MakeUserInstruction.parse().
The documentation for this interface was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/commandParsing/drawableObectGenerationInterfaces/UserDefinedVariableGenerator.java