slogo_team10: drawableobject.DrawableObject Class Reference
drawableobject.DrawableObject Class Reference
Public Member Functions
DrawableObject (String someParent, String someType, Map< String, String > rawParameters)
String getParent ()
String getType ()
Map< String, String > getParameters ()
String toString ()
Private Attributes
String parent
String type
Map< String, String > parameters
Detailed Description
Class encapsulates a data type that specifies how to draw something on the screen
Author
Austin Kyker, Steve Kuznetsov, Stanley Yuan, Allan Kiplagat
Definition at line 13 of file DrawableObject.java.
Constructor & Destructor Documentation
drawableobject.DrawableObject.DrawableObject (String someParent, String someType, Map< String, String > rawParameters)
Parameters
someParent
someType
rawParameters
Definition at line 25 of file DrawableObject.java.
Member Function Documentation
Map<String, String> drawableobject.DrawableObject.getParameters ()
These parameters are used by the factories to build certain nodes. Each different factory will receive different parameters depending on what it needs to know to draw the object it creates.
Returns
Definition at line 57 of file DrawableObject.java.
References drawableobject.DrawableObject.parameters.
Referenced by tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOHomeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOTest(), tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest(), tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.recurringCommandTests.DoTimesTests.DoTimesTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.FalseTest(), tests.commandTests.recurringCommandTests.ForTests.ForTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenDownTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenUpTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest(), tests.commandTests.singleInputFloatTests.LeftTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.RightTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.BackwardTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.ForwardTests.IntegerParsingTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.recurringCommandTests.RepeatTests.RepeatTest(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingNoInitialHeading(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingWithPreviousHeading(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteAfterSetPaletteTest(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteAfterSetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), tests.commandTests.inputlessCommandTests.StampTests.StampTest(), tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest(), tests.commandTests.booleanCommandTests.NotTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.EqualTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.OrTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.AndTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.SyntaxErrorParseTest(), tests.commandTests.booleanConditionalCommands.IfTests.TrueTest(), and tests.commandTests.booleanConditionalCommands.IfElseTests.TrueTest().
String drawableobject.DrawableObject.getParent ()
The parent represents the drawable component where the drawable object will be drawn.
Returns
String
Definition at line 38 of file DrawableObject.java.
References drawableobject.DrawableObject.parent.
Referenced by tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOHomeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOTest(), tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest(), tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.recurringCommandTests.DoTimesTests.DoTimesTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.FalseTest(), tests.commandTests.recurringCommandTests.ForTests.ForTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenDownTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenUpTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest(), tests.commandTests.singleInputFloatTests.RightTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.LeftTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.ForwardTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.BackwardTests.IntegerParsingTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.recurringCommandTests.RepeatTests.RepeatTest(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingNoInitialHeading(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingWithPreviousHeading(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest(), tests.commandTests.inputlessCommandTests.StampTests.StampTest(), tests.commandTests.booleanConditionalCommands.IfTests.TrueTest(), and tests.commandTests.booleanConditionalCommands.IfElseTests.TrueTest().
String drawableobject.DrawableObject.getType ()
The type represents the type of factory that will be used to draw the drawable object.
Returns
Definition at line 47 of file DrawableObject.java.
References drawableobject.DrawableObject.type.
Referenced by tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOHomeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOTest(), tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest(), tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.recurringCommandTests.DoTimesTests.DoTimesTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.FalseTest(), tests.commandTests.recurringCommandTests.ForTests.ForTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenDownTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenUpTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest(), tests.commandTests.singleInputFloatTests.RightTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.LeftTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.ForwardTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.BackwardTests.IntegerParsingTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.recurringCommandTests.RepeatTests.RepeatTest(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingNoInitialHeading(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingWithPreviousHeading(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest(), tests.commandTests.inputlessCommandTests.StampTests.StampTest(), tests.commandTests.booleanConditionalCommands.IfTests.TrueTest(), and tests.commandTests.booleanConditionalCommands.IfElseTests.TrueTest().
String drawableobject.DrawableObject.toString ()
Definition at line 62 of file DrawableObject.java.
Member Data Documentation
Map<String, String> drawableobject.DrawableObject.parameters private
Definition at line 17 of file DrawableObject.java.
Referenced by drawableobject.DrawableObject.getParameters().
String drawableobject.DrawableObject.parent private
Definition at line 15 of file DrawableObject.java.
Referenced by drawableobject.DrawableObject.getParent().
String drawableobject.DrawableObject.type private
Definition at line 16 of file DrawableObject.java.
Referenced by drawableobject.DrawableObject.getType().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/drawableobject/DrawableObject.java