slogo_team10: tests.TranslatorTests Class Reference
tests.TranslatorTests Class Reference
Public Member Functions
void TranslatorRegExTest () throws LanguageFileNotFoundException, PropertyFileAccessException
void EnglishTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
void ChineseTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
void RussianTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
void FrenchTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
void ItalianTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
void PortugueseTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
Detailed Description
Definition at line 13 of file TranslatorTests.java.
Member Function Documentation
void tests.TranslatorTests.ChineseTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
Definition at line 75 of file TranslatorTests.java.
References translator.Translator.translate().
void tests.TranslatorTests.EnglishTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
Definition at line 43 of file TranslatorTests.java.
References translator.Translator.translate().
void tests.TranslatorTests.FrenchTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
Definition at line 139 of file TranslatorTests.java.
References translator.Translator.translate().
void tests.TranslatorTests.ItalianTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
Definition at line 171 of file TranslatorTests.java.
References translator.Translator.translate().
void tests.TranslatorTests.PortugueseTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
Definition at line 203 of file TranslatorTests.java.
References translator.Translator.translate().
void tests.TranslatorTests.RussianTranslationTest () throws LanguageFileNotFoundException, PropertyFileAccessException
Definition at line 107 of file TranslatorTests.java.
References translator.Translator.translate().
void tests.TranslatorTests.TranslatorRegExTest () throws LanguageFileNotFoundException, PropertyFileAccessException
Definition at line 16 of file TranslatorTests.java.
References translator.Translator.matchesCommandPattern(), translator.Translator.matchesConstantPattern(), and translator.Translator.matchesVariablePattern().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/tests/TranslatorTests.java