slogo_team10: workspaceState.UserDefinedCommandCollection.Command Class Reference
workspaceState.UserDefinedCommandCollection.Command Class Reference
Public Member Functions
Command (String aName, int numArgs, List< String > toDo, List< String > parameters)
List< String > getCommands ()
Iterator< String > getCommandIterator ()
int getNumArguments ()
String getName ()
List< String > getParameters ()
boolean equals (Object o)
Private Attributes
String name
int numberOfArguments
List< String > commandStrings
List< String > parameterList
Detailed Description
Definition at line 30 of file UserDefinedCommandCollection.java.
Constructor & Destructor Documentation
workspaceState.UserDefinedCommandCollection.Command.Command (String aName, int numArgs, List< String > toDo, List< String > parameters)
Definition at line 36 of file UserDefinedCommandCollection.java.
Referenced by workspaceState.UserDefinedCommandCollection.Command.equals().
Member Function Documentation
boolean workspaceState.UserDefinedCommandCollection.Command.equals (Object o)
Definition at line 64 of file UserDefinedCommandCollection.java.
References workspaceState.UserDefinedCommandCollection.Command.Command(), workspaceState.UserDefinedCommandCollection.Command.commandStrings, workspaceState.UserDefinedCommandCollection.Command.name, and workspaceState.UserDefinedCommandCollection.Command.numberOfArguments.
Referenced by tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), and tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables().
Iterator<String> workspaceState.UserDefinedCommandCollection.Command.getCommandIterator ()
Definition at line 47 of file UserDefinedCommandCollection.java.
Referenced by commandParsing.userCommandParsing.UserInstruction.parse().
List<String> workspaceState.UserDefinedCommandCollection.Command.getCommands ()
Definition at line 43 of file UserDefinedCommandCollection.java.
References workspaceState.UserDefinedCommandCollection.Command.commandStrings.
Referenced by commandParsing.drawableObectGenerationInterfaces.UserDefinedCommandGenerator.generateDrawableObjectRepresentingCommand().
String workspaceState.UserDefinedCommandCollection.Command.getName ()
Definition at line 55 of file UserDefinedCommandCollection.java.
References workspaceState.UserDefinedCommandCollection.Command.name.
Referenced by commandParsing.drawableObectGenerationInterfaces.UserDefinedCommandGenerator.generateDrawableObjectRepresentingCommand().
int workspaceState.UserDefinedCommandCollection.Command.getNumArguments ()
Definition at line 51 of file UserDefinedCommandCollection.java.
References workspaceState.UserDefinedCommandCollection.Command.numberOfArguments.
Referenced by commandParsing.userCommandParsing.UserInstruction.parse().
List<String> workspaceState.UserDefinedCommandCollection.Command.getParameters ()
Definition at line 59 of file UserDefinedCommandCollection.java.
References workspaceState.UserDefinedCommandCollection.Command.parameterList.
Referenced by commandParsing.userCommandParsing.UserInstruction.accumulateComponents(), commandParsing.drawableObectGenerationInterfaces.UserDefinedCommandGenerator.generateDrawableObjectRepresentingCommand(), and commandParsing.userCommandParsing.UserInstruction.parse().
Member Data Documentation
List<String> workspaceState.UserDefinedCommandCollection.Command.commandStrings private
Definition at line 33 of file UserDefinedCommandCollection.java.
Referenced by workspaceState.UserDefinedCommandCollection.Command.equals(), and workspaceState.UserDefinedCommandCollection.Command.getCommands().
String workspaceState.UserDefinedCommandCollection.Command.name private
Definition at line 31 of file UserDefinedCommandCollection.java.
Referenced by workspaceState.UserDefinedCommandCollection.Command.equals(), and workspaceState.UserDefinedCommandCollection.Command.getName().
int workspaceState.UserDefinedCommandCollection.Command.numberOfArguments private
Definition at line 32 of file UserDefinedCommandCollection.java.
Referenced by workspaceState.UserDefinedCommandCollection.Command.equals(), and workspaceState.UserDefinedCommandCollection.Command.getNumArguments().
List<String> workspaceState.UserDefinedCommandCollection.Command.parameterList private
Definition at line 34 of file UserDefinedCommandCollection.java.
Referenced by workspaceState.UserDefinedCommandCollection.Command.getParameters().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/workspaceState/UserDefinedCommandCollection.java