slogo_team10: commandParsing.structuralCommandParsing.Tell Class Reference
commandParsing.structuralCommandParsing.Tell Class Reference
Public Member Functions
Tell (WorkspaceState someWorkspace)
double parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Public Member Functions inherited from commandParsing.structuralCommandParsing.MultipleTurtleCommand
MultipleTurtleCommand (WorkspaceState someWorkspace)
abstract double parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Public Member Functions inherited from commandParsing.structuralCommandParsing.StructuralCommand
StructuralCommand (WorkspaceState someWorkspace)
Public Member Functions inherited from commandParsing.CommandParser
CommandParser (WorkspaceState someWorkspace)
abstract double parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Public Member Functions inherited from commandParsing.drawableObectGenerationInterfaces.TurtleGenerator
default DrawableObject generateDrawableObjectRepresentingTurtle (Turtle turtle)
default DrawableObject generateDrawableObjectRepresentingTurtleDeletion (Turtle turtle)
Additional Inherited Members
Static Public Member Functions inherited from commandParsing.CommandParser
static CommandParser createParser (String commandName, WorkspaceState workspace) throws CompileTimeParsingException
Protected Member Functions inherited from commandParsing.structuralCommandParsing.MultipleTurtleCommand
void determineTurtlesToActivate (Iterator< String > commands, Queue< DrawableObject > objectQueue) throws SLOGOException
int makeAndActivateGivenTurtles (Queue< DrawableObject > objectQueue) throws RunTimeNullPointerException
void saveCurrentActiveTurtles ()
void restoreActiveTurtles () throws RunTimeNullPointerException
Protected Member Functions inherited from commandParsing.structuralCommandParsing.StructuralCommand
void checkForOpeningBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException
void checkForClosingBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException
void extractCommandsBetweenBraces (Iterator< String > commandStringIterator) throws CompileTimeParsingException, RunTimeDivideByZeroException, RunTimeNullPointerException
void parseCommandsBetweenBraces (Iterator< String > commands, Queue< DrawableObject > objectQueue) throws SLOGOException
void setEnclosedCommandsToEmptyList ()
void ignoreUntilClosingBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException
String getVariable (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Protected Member Functions inherited from commandParsing.CommandParser
void accumulateComponents (Iterator< String > commandStringIterator, int numberToAccumulate, Queue< DrawableObject > objectQueue) throws SLOGOException
boolean isStringParsableAsCommand (String string)
Protected Attributes inherited from commandParsing.structuralCommandParsing.StructuralCommand
List< String > enclosedCommands
double returnValue
Protected Attributes inherited from commandParsing.CommandParser
List< Double > expressionComponents = new ArrayList<Double>()
Static Protected Attributes inherited from commandParsing.CommandParser
static WorkspaceState workspace
Package Attributes inherited from commandParsing.structuralCommandParsing.MultipleTurtleCommand
List< Turtle > savedListOfTurtles = new ArrayList<Turtle>()
List< Integer > activeTurtleIDList = new ArrayList<Integer>()
Detailed Description
Definition at line 10 of file Tell.java.
Constructor & Destructor Documentation
commandParsing.structuralCommandParsing.Tell.Tell (WorkspaceState someWorkspace)
Definition at line 12 of file Tell.java.
Member Function Documentation
double commandParsing.structuralCommandParsing.Tell.parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Definition at line 17 of file Tell.java.
References workspaceState.TurtleCollection.clearActiveTurtles(), commandParsing.structuralCommandParsing.MultipleTurtleCommand.determineTurtlesToActivate(), commandParsing.structuralCommandParsing.StructuralCommand.enclosedCommands, commandParsing.structuralCommandParsing.StructuralCommand.extractCommandsBetweenBraces(), commandParsing.structuralCommandParsing.MultipleTurtleCommand.makeAndActivateGivenTurtles(), workspaceState.WorkspaceState.turtles, and commandParsing.CommandParser.workspace.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/commandParsing/structuralCommandParsing/Tell.java