slogo_team10: commandParsing.userCommandParsing.MakeUserInstruction Class Reference
commandParsing.userCommandParsing.MakeUserInstruction Class Reference
Public Member Functions
MakeUserInstruction (WorkspaceState someWorkspace)
double parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Public Member Functions inherited from commandParsing.structuralCommandParsing.StructuralCommand
StructuralCommand (WorkspaceState someWorkspace)
Public Member Functions inherited from commandParsing.CommandParser
CommandParser (WorkspaceState someWorkspace)
abstract double parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Public Member Functions inherited from commandParsing.drawableObectGenerationInterfaces.UserDefinedCommandGenerator
default DrawableObject generateDrawableObjectRepresentingCommand (Command command, Translator translator)
Public Member Functions inherited from commandParsing.drawableObectGenerationInterfaces.UserDefinedVariableGenerator
default DrawableObject generateDrawableObjectRepresentingVariable (WorkspaceVariable variable)
Private Attributes
List< String > parameters = new ArrayList<String>()
Additional Inherited Members
Static Public Member Functions inherited from commandParsing.CommandParser
static CommandParser createParser (String commandName, WorkspaceState workspace) throws CompileTimeParsingException
Protected Member Functions inherited from commandParsing.structuralCommandParsing.StructuralCommand
void checkForOpeningBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException
void checkForClosingBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException
void extractCommandsBetweenBraces (Iterator< String > commandStringIterator) throws CompileTimeParsingException, RunTimeDivideByZeroException, RunTimeNullPointerException
void parseCommandsBetweenBraces (Iterator< String > commands, Queue< DrawableObject > objectQueue) throws SLOGOException
void setEnclosedCommandsToEmptyList ()
void ignoreUntilClosingBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException
String getVariable (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Protected Member Functions inherited from commandParsing.CommandParser
void accumulateComponents (Iterator< String > commandStringIterator, int numberToAccumulate, Queue< DrawableObject > objectQueue) throws SLOGOException
boolean isStringParsableAsCommand (String string)
Protected Attributes inherited from commandParsing.structuralCommandParsing.StructuralCommand
List< String > enclosedCommands
double returnValue
Protected Attributes inherited from commandParsing.CommandParser
List< Double > expressionComponents = new ArrayList<Double>()
Static Protected Attributes inherited from commandParsing.CommandParser
static WorkspaceState workspace
Detailed Description
This class is the MakeUserInstruction class that contains the information for actually creating and defining new user instructions.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 24 of file MakeUserInstruction.java.
Constructor & Destructor Documentation
commandParsing.userCommandParsing.MakeUserInstruction.MakeUserInstruction (WorkspaceState someWorkspace)
Definition at line 27 of file MakeUserInstruction.java.
Member Function Documentation
double commandParsing.userCommandParsing.MakeUserInstruction.parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Definition at line 34 of file MakeUserInstruction.java.
References workspaceState.WorkspaceState.commands, commandParsing.CommandParser.createParser(), commandParsing.structuralCommandParsing.StructuralCommand.enclosedCommands, commandParsing.structuralCommandParsing.StructuralCommand.extractCommandsBetweenBraces(), workspaceState.UserDefinedCommandCollection.fetchUserDefinedCommand(), workspaceState.UserDefinedVariableCollection.fetchWorkspaceVariable(), commandParsing.drawableObectGenerationInterfaces.UserDefinedCommandGenerator.generateDrawableObjectRepresentingCommand(), commandParsing.drawableObectGenerationInterfaces.UserDefinedVariableGenerator.generateDrawableObjectRepresentingVariable(), commandParsing.structuralCommandParsing.StructuralCommand.getVariable(), commandParsing.CommandParser.isStringParsableAsCommand(), commandParsing.structuralCommandParsing.StructuralCommand.parseCommandsBetweenBraces(), workspaceState.UserDefinedCommandCollection.storeUserDefinedCommand(), workspaceState.UserDefinedVariableCollection.storeVariable(), workspaceState.WorkspaceState.translator, workspaceState.UserDefinedVariableCollection.variableExists(), workspaceState.WorkspaceState.variables, and commandParsing.CommandParser.workspace.
Member Data Documentation
List<String> commandParsing.userCommandParsing.MakeUserInstruction.parameters = new ArrayList<String>() private
Definition at line 31 of file MakeUserInstruction.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/commandParsing/userCommandParsing/MakeUserInstruction.java