slogo_team10: gui.componentdrawers.significantcommands.tabs.SavedCommandsTab Class Reference
gui.componentdrawers.significantcommands.tabs.SavedCommandsTab Class Reference
Public Member Functions
SavedCommandsTab (SavedCommandsFeature feature)
void loadCommands (List< String > savedCommands)
List< String > getCommands ()
Private Attributes
SavedCommandsFeature myFeature
Detailed Description
This tab allows the user to see saved commands. The user can double click on these commands and they will appear in the command line without the user having to type them again.
Author
akyker20
Definition at line 17 of file SavedCommandsTab.java.
Constructor & Destructor Documentation
gui.componentdrawers.significantcommands.tabs.SavedCommandsTab.SavedCommandsTab (SavedCommandsFeature feature)
Definition at line 21 of file SavedCommandsTab.java.
References gui.mainclasses.TextGenerator.get(), and gui.mainclasses.TextGenerator.SAVED.
Member Function Documentation
List<String> gui.componentdrawers.significantcommands.tabs.SavedCommandsTab.getCommands ()
Definition at line 32 of file SavedCommandsTab.java.
References gui.nonbuttonfeatures.SavedCommandsFeature.getCommands().
void gui.componentdrawers.significantcommands.tabs.SavedCommandsTab.loadCommands (List< String > savedCommands)
Definition at line 28 of file SavedCommandsTab.java.
References gui.nonbuttonfeatures.SavedCommandsFeature.loadCommands().
Member Data Documentation
SavedCommandsFeature gui.componentdrawers.significantcommands.tabs.SavedCommandsTab.myFeature private
Definition at line 19 of file SavedCommandsTab.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/componentdrawers/significantcommands/tabs/SavedCommandsTab.java