slogo_team10: gui.turtlescreenwrap.VerticalTurtleScreenWrap Class Reference
gui.turtlescreenwrap.VerticalTurtleScreenWrap Class Reference
Static Public Member Functions
static List< Point2DPair > fragmentPoint2DPair (Point2DPair pointPair)
Detailed Description
Class handles screen wrapping when the turtle is moving vertically
Author
allankiplagat
Definition at line 12 of file VerticalTurtleScreenWrap.java.
Member Function Documentation
static List<Point2DPair> gui.turtlescreenwrap.VerticalTurtleScreenWrap.fragmentPoint2DPair (Point2DPair pointPair) static
Definition at line 13 of file VerticalTurtleScreenWrap.java.
References gui.turtlescreenwrap.TesselationMapper.checkOffScreen(), gui.turtlescreenwrap.Point2DPair.dest, gui.turtlescreenwrap.TurtleScreenWrap.getYmovement(), gui.turtlescreenwrap.Point2DPair.origin, gui.turtlescreenwrap.TurtleScreenWrap.YMAX, and gui.turtlescreenwrap.TurtleScreenWrap.YPOS_MOVE.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/turtlescreenwrap/VerticalTurtleScreenWrap.java