slogo_team10: gui.menus.FileMenu Class Reference
gui.menus.FileMenu Class Reference
Public Member Functions
FileMenu (WorkspaceManager workspaceManager)
Static Protected Attributes
static final String SAVED_WORKSPACE_FILES_DIR = "./WorkspaceFiles"
Private Member Functions
void addTurtleToWorkspace ()
File createFileChooser (String defaultDir)
Private Attributes
WorkspaceManager myWorkspaceManager
Static Private Attributes
static final String XML_FILE_EXTENSION_DESCRIPTION = "XML files (*.xml)"
static final String XML_FILE_EXTENSION = "*.xml"
Detailed Description
Class offers the user three major features. 1) The user can load an xml file to load a workspace (variables, screen parameters, pen parameters, etc.) 2) The user can save the workspace to an xml file for later retrieval 3) The user can create a new workspace - the user can do this in several different languages to allow globalization.
Author
akyker20
Definition at line 36 of file FileMenu.java.
Constructor & Destructor Documentation
gui.menus.FileMenu.FileMenu (WorkspaceManager workspaceManager)
Definition at line 44 of file FileMenu.java.
References gui.menus.FileMenu.addTurtleToWorkspace(), gui.mainclasses.workspace.WorkspaceManager.addWorkspace(), gui.mainclasses.TextGenerator.CHINESE, gui.menus.FileMenu.createFileChooser(), gui.mainclasses.TextGenerator.ENGLISH, gui.mainclasses.TextGenerator.FILE, gui.mainclasses.TextGenerator.FRENCH, gui.mainclasses.TextGenerator.get(), gui.mainclasses.workspace.WorkspaceManager.getActiveWorkspace(), gui.mainclasses.workspace.Workspace.getDataHolder(), XML.readers.SavedWorkspaceXMLReader.getInitialPenCommands(), XML.readers.SavedWorkspaceXMLReader.getScreenParameters(), gui.mainclasses.workspace.Workspace.getScreenParams(), XML.readers.SavedWorkspaceXMLReader.getUserDefinedCommands(), XML.readers.SavedWorkspaceXMLReader.getWorkspaceDataHolder(), XML.readers.SavedWorkspaceXMLReader.getWorkspaceVariables(), gui.mainclasses.TextGenerator.LOAD_WORKSPACE, gui.mainclasses.TextGenerator.NEW_WORKSPACE, gui.mainclasses.workspace.Workspace.parseCommandString(), gui.mainclasses.TextGenerator.SAVE_WORKSPACE, gui.mainclasses.TextGenerator.setLanguage(), and XML.writers.SavedWorkspaceXMLWriter.writeFile().
Member Function Documentation
void gui.menus.FileMenu.addTurtleToWorkspace () private
Definition at line 124 of file FileMenu.java.
References gui.mainclasses.workspace.WorkspaceManager.getActiveWorkspace(), Control.SlogoControl.NEW_TURTLE_COMMAND, and gui.mainclasses.workspace.Workspace.parseCommandString().
Referenced by gui.menus.FileMenu.FileMenu().
File gui.menus.FileMenu.createFileChooser (String defaultDir) private
Creates the button used to select the XML file to run a simulation. This will be the only button not disabled to start the simulation.
Returns
Definition at line 134 of file FileMenu.java.
References gui.mainclasses.TextGenerator.get(), and gui.mainclasses.TextGenerator.SELECT_XMLFILE.
Referenced by gui.menus.FileMenu.FileMenu().
Member Data Documentation
WorkspaceManager gui.menus.FileMenu.myWorkspaceManager private
Definition at line 42 of file FileMenu.java.
final String gui.menus.FileMenu.SAVED_WORKSPACE_FILES_DIR = "./WorkspaceFiles" static protected
Definition at line 38 of file FileMenu.java.
final String gui.menus.FileMenu.XML_FILE_EXTENSION = "*.xml" static private
Definition at line 40 of file FileMenu.java.
final String gui.menus.FileMenu.XML_FILE_EXTENSION_DESCRIPTION = "XML files (*.xml)" static private
Definition at line 39 of file FileMenu.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/menus/FileMenu.java