slogo_team10: gui.nonbuttonfeatures.SavedCommandsFeature Class Reference
gui.nonbuttonfeatures.SavedCommandsFeature Class Reference
Public Member Functions
SavedCommandsFeature (CommandLineDrawer commandLineDrawer, ObservableList< String > savedCommands)
void addCommand (String currentCommand)
void loadCommands (List< String > savedCommands)
List< String > getCommands ()
Private Attributes
ObservableList< String > myCommands
Static Private Attributes
static final int HEIGHT = 168
static final int LAYOUT = 20
Detailed Description
Class is a ListView used to display the commands saved by the user.
Author
akyker20
Definition at line 16 of file SavedCommandsFeature.java.
Constructor & Destructor Documentation
gui.nonbuttonfeatures.SavedCommandsFeature.SavedCommandsFeature (CommandLineDrawer commandLineDrawer, ObservableList< String > savedCommands)
If the user double clicks on a previous command, that command is run.
Definition at line 22 of file SavedCommandsFeature.java.
References gui.componentdrawers.CommandLineDrawer.setCommandLine().
Member Function Documentation
void gui.nonbuttonfeatures.SavedCommandsFeature.addCommand (String currentCommand)
Adds the command in the command line to the list view. This method is called when the SaveCommand button is clicked in the ButtonHolder component. Does not add the command if command line is empty or command has already been saved.
Parameters
currentCommand
Definition at line 53 of file SavedCommandsFeature.java.
Referenced by gui.buttonfeatures.SaveCommandButtonFeature.saveCommand().
List<String> gui.nonbuttonfeatures.SavedCommandsFeature.getCommands ()
Returns the list of saved commands.
Returns
Definition at line 80 of file SavedCommandsFeature.java.
References gui.nonbuttonfeatures.SavedCommandsFeature.myCommands.
Referenced by gui.componentdrawers.significantcommands.tabs.SavedCommandsTab.getCommands().
void gui.nonbuttonfeatures.SavedCommandsFeature.loadCommands (List< String > savedCommands)
Loads commands when user loads previously saved commands from an xml parser. This is called when the user clicks file -> Load saved commands.
Parameters
savedCommands
Definition at line 68 of file SavedCommandsFeature.java.
Referenced by gui.componentdrawers.significantcommands.tabs.SavedCommandsTab.loadCommands().
Member Data Documentation
final int gui.nonbuttonfeatures.SavedCommandsFeature.HEIGHT = 168 static private
Definition at line 19 of file SavedCommandsFeature.java.
final int gui.nonbuttonfeatures.SavedCommandsFeature.LAYOUT = 20 static private
Definition at line 20 of file SavedCommandsFeature.java.
ObservableList<String> gui.nonbuttonfeatures.SavedCommandsFeature.myCommands private
Definition at line 18 of file SavedCommandsFeature.java.
Referenced by gui.nonbuttonfeatures.SavedCommandsFeature.getCommands().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/nonbuttonfeatures/SavedCommandsFeature.java