slogo_team10: gui.mainclasses.FactoryBuilder Class Reference
gui.mainclasses.FactoryBuilder Class Reference
Static Public Member Functions
static ObjectFactory[] init (WorkspaceDataHolder holder, TurtleScreenDrawer drawer, TurtleNodes turtleNodes)
Static Public Attributes
static final String LINE_FACTORY = "LineFactory"
static final String TURTLE_FACTORY = "TurtleFactory"
static final String ERROR_FACTORY = "ErrorFactory"
static final String CLEAR_GRID_FACTORY = "ClearGridFactory"
static final String WORKSPACE_VARIABLE_FACTORY = "WorkspaceVariableFactory"
static final String USER_DEFINED_COMMAND_FACTORY = "UserDefinedCommandFactory"
static final String SCREEN_COLOR_FACTORY = "ScreenColorFactory"
static final String COLOR_INDEX_FACTORY = "ColorIndexFactory"
static final String SHAPE_PALETTE_INDEX_FACTORY = "ShapePaletteEntryFactory"
Detailed Description
Definition at line 17 of file FactoryBuilder.java.
Member Function Documentation
static ObjectFactory [] gui.mainclasses.FactoryBuilder.init (WorkspaceDataHolder holder, TurtleScreenDrawer drawer, TurtleNodes turtleNodes) static
Makes the object factories
Returns
an array of object factories
Definition at line 34 of file FactoryBuilder.java.
References gui.mainclasses.workspace.WorkspaceDataHolder.getMyColorIndexList(), gui.mainclasses.workspace.WorkspaceDataHolder.getMyImageIndexList(), gui.mainclasses.workspace.WorkspaceDataHolder.getMyUserDefinedCommandList(), and gui.mainclasses.workspace.WorkspaceDataHolder.getMyVariablesList().
Referenced by gui.mainclasses.workspace.Workspace.Workspace().
Member Data Documentation
final String gui.mainclasses.FactoryBuilder.CLEAR_GRID_FACTORY = "ClearGridFactory" static
Definition at line 22 of file FactoryBuilder.java.
Referenced by tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), and tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest().
final String gui.mainclasses.FactoryBuilder.COLOR_INDEX_FACTORY = "ColorIndexFactory" static
Definition at line 26 of file FactoryBuilder.java.
final String gui.mainclasses.FactoryBuilder.ERROR_FACTORY = "ErrorFactory" static
Definition at line 21 of file FactoryBuilder.java.
final String gui.mainclasses.FactoryBuilder.LINE_FACTORY = "LineFactory" static
Definition at line 19 of file FactoryBuilder.java.
final String gui.mainclasses.FactoryBuilder.SCREEN_COLOR_FACTORY = "ScreenColorFactory" static
Definition at line 25 of file FactoryBuilder.java.
final String gui.mainclasses.FactoryBuilder.SHAPE_PALETTE_INDEX_FACTORY = "ShapePaletteEntryFactory" static
Definition at line 27 of file FactoryBuilder.java.
final String gui.mainclasses.FactoryBuilder.TURTLE_FACTORY = "TurtleFactory" static
Definition at line 20 of file FactoryBuilder.java.
final String gui.mainclasses.FactoryBuilder.USER_DEFINED_COMMAND_FACTORY = "UserDefinedCommandFactory" static
Definition at line 24 of file FactoryBuilder.java.
final String gui.mainclasses.FactoryBuilder.WORKSPACE_VARIABLE_FACTORY = "WorkspaceVariableFactory" static
Definition at line 23 of file FactoryBuilder.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/mainclasses/FactoryBuilder.java