slogo_team10: gui.factories.turtlefactory.TurtleNodes Class Reference
gui.factories.turtlefactory.TurtleNodes Class Reference
Public Member Functions
TurtleNodes (Workspace workspace)
TurtleNode getTurtleWithID (String imageID)
Node[] addTurtleNode (Map< String, String > params) throws FileNotFoundException
void clearTurtleNodes ()
List< TurtleNode > getActiveNodes ()
Private Attributes
List< TurtleNode > myTurtleNodes = new ArrayList<TurtleNode>()
Workspace myWorkspace
Detailed Description
Class represents a collection of TurtleNode objects.
Author
akyker20
Definition at line 17 of file TurtleNodes.java.
Constructor & Destructor Documentation
gui.factories.turtlefactory.TurtleNodes.TurtleNodes (Workspace workspace)
Definition at line 22 of file TurtleNodes.java.
Member Function Documentation
Node [] gui.factories.turtlefactory.TurtleNodes.addTurtleNode (Map< String, String > params) throws FileNotFoundException
Adds a new turtle node. This is called when a new turtle is created.
Parameters
params
Returns
Exceptions
FileNotFoundException
Definition at line 46 of file TurtleNodes.java.
Referenced by gui.factories.turtlefactory.TurtleFactory.generateObject().
void gui.factories.turtlefactory.TurtleNodes.clearTurtleNodes ()
Removes all the turtle nodes from the list. This method is called when a clear screen drawable object arrives.
Definition at line 56 of file TurtleNodes.java.
Referenced by gui.componentdrawers.TurtleScreenDrawer.resetScreen().
List<TurtleNode> gui.factories.turtlefactory.TurtleNodes.getActiveNodes ()
Returns the active nodes. This is used in the stage initializer class to set up the key listener that will allow the user to move the active turtles.
Returns
List of active turtle nodes.
Definition at line 66 of file TurtleNodes.java.
References gui.factories.turtlefactory.TurtleNode.isSelected().
Referenced by gui.mainclasses.workspace.Workspace.moveActiveTurtles(), and gui.mainclasses.workspace.Workspace.notifyOfTurtleSelectionChange().
TurtleNode gui.factories.turtlefactory.TurtleNodes.getTurtleWithID (String imageID)
Looks for a turtle with an id of imageID. If it finds the turtle, it returns it. Otherwise, it returns null.
Parameters
imageID
Returns
Definition at line 32 of file TurtleNodes.java.
Referenced by gui.factories.turtlefactory.TurtleFactory.generateObject().
Member Data Documentation
List<TurtleNode> gui.factories.turtlefactory.TurtleNodes.myTurtleNodes = new ArrayList<TurtleNode>() private
Definition at line 19 of file TurtleNodes.java.
Workspace gui.factories.turtlefactory.TurtleNodes.myWorkspace private
Definition at line 20 of file TurtleNodes.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/factories/turtlefactory/TurtleNodes.java