slogo_team10: tests.commandTests.CommandTester Class Reference
tests.commandTests.CommandTester Class Reference abstract
Public Member Functions
void setUp () throws Exception
void setUpTranslator (String language) throws IOException
void setUpStateBeforeTesting (String language) throws IOException
void setUpCommands (String input)
void resetTesterVariables ()
CommandParser createCommand () throws RunTimeNullPointerException, CompileTimeParsingException
Protected Attributes
WorkspaceState workspace
Iterator< String > commands
Queue< DrawableObject > objectQueue = new LinkedList<DrawableObject>()
Detailed Description
This is the base for almost all of the tests, with the methods for setting up being almost universally used to initialize the language and start the tests.
Author
Steve Kuznetsov
Definition at line 24 of file CommandTester.java.
Member Function Documentation
CommandParser tests.commandTests.CommandTester.createCommand () throws RunTimeNullPointerException, CompileTimeParsingException
Definition at line 71 of file CommandTester.java.
References commandParsing.CommandParser.createParser(), and tests.commandTests.CommandTester.workspace.
Referenced by tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOHomeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOTest(), tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest(), tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.recurringCommandTests.DoTimesTests.DoTimesTest(), tests.commandTests.booleanConditionalCommands.IfTests.FalseTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.FalseTest(), tests.commandTests.booleanCommandTests.LessThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotTests.FloatParseTest(), tests.commandTests.booleanCommandTests.EqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.OrTests.FloatParseTest(), tests.commandTests.booleanCommandTests.AndTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.FloatParseTest(), tests.commandTests.recurringCommandTests.ForTests.ForTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenDownTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenUpTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerParseTest(), tests.commandTests.turtleQueryTests.YCoordinateTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.RightTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.LeftTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.ForwardTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.BackwardTests.IntegerParsingTest(), tests.commandTests.turtleQueryTests.IsPenDownTests.IsPenDownTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.turtleQueryTests.IsPenDownTests.PenDownAfterPenUp(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.recurringCommandTests.RepeatTests.RepeatTest(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingNoInitialHeading(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingWithPreviousHeading(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteAfterSetPaletteTest(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteAfterSetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingAfterHideTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), tests.commandTests.inputlessCommandTests.StampTests.StampTest(), tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest(), tests.commandTests.booleanCommandTests.NotEqualTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.NotTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.EqualTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.OrTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.AndTests.SyntaxErrorParseTest(), tests.commandTests.booleanConditionalCommands.IfTests.TrueTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.TrueTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorAfterMoveTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorTest(), and tests.commandTests.turtleQueryTests.YCoordinateTests.YCorAfterMoveTest().
void tests.commandTests.CommandTester.resetTesterVariables ()
Definition at line 60 of file CommandTester.java.
References tests.commandTests.CommandTester.setUpStateBeforeTesting().
Referenced by tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOHomeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOTest(), tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest(), tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.recurringCommandTests.DoTimesTests.DoTimesTest(), tests.commandTests.booleanConditionalCommands.IfTests.FalseTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.FalseTest(), tests.commandTests.booleanCommandTests.LessThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotTests.FloatParseTest(), tests.commandTests.booleanCommandTests.EqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.OrTests.FloatParseTest(), tests.commandTests.booleanCommandTests.AndTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.FloatParseTest(), tests.commandTests.recurringCommandTests.ForTests.ForTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenDownTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenUpTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerParseTest(), tests.commandTests.turtleQueryTests.YCoordinateTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.RightTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.LeftTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.ForwardTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.BackwardTests.IntegerParsingTest(), tests.commandTests.turtleQueryTests.IsPenDownTests.IsPenDownTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.turtleQueryTests.IsPenDownTests.PenDownAfterPenUp(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.recurringCommandTests.RepeatTests.RepeatTest(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingNoInitialHeading(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingWithPreviousHeading(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteAfterSetPaletteTest(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteAfterSetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingAfterHideTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), tests.commandTests.inputlessCommandTests.StampTests.StampTest(), tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest(), tests.commandTests.booleanCommandTests.NotEqualTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.NotTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.EqualTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.OrTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.AndTests.SyntaxErrorParseTest(), tests.commandTests.booleanConditionalCommands.IfTests.TrueTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.TrueTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorAfterMoveTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorTest(), and tests.commandTests.turtleQueryTests.YCoordinateTests.YCorAfterMoveTest().
void tests.commandTests.CommandTester.setUp () throws Exception
Definition at line 31 of file CommandTester.java.
References tests.commandTests.CommandTester.setUpStateBeforeTesting().
void tests.commandTests.CommandTester.setUpCommands (String input)
Definition at line 56 of file CommandTester.java.
References translator.Translator.translate(), and workspaceState.WorkspaceState.translator.
Referenced by tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOHomeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOTest(), tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest(), tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.recurringCommandTests.DoTimesTests.DoTimesTest(), tests.commandTests.booleanConditionalCommands.IfTests.FalseTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.FalseTest(), tests.commandTests.booleanCommandTests.LessThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotTests.FloatParseTest(), tests.commandTests.booleanCommandTests.EqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.OrTests.FloatParseTest(), tests.commandTests.booleanCommandTests.AndTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.FloatParseTest(), tests.commandTests.recurringCommandTests.ForTests.ForTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenDownTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenUpTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerParseTest(), tests.commandTests.turtleQueryTests.YCoordinateTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.RightTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.LeftTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.ForwardTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.BackwardTests.IntegerParsingTest(), tests.commandTests.turtleQueryTests.IsPenDownTests.IsPenDownTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.turtleQueryTests.IsPenDownTests.PenDownAfterPenUp(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.recurringCommandTests.RepeatTests.RepeatTest(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingNoInitialHeading(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingWithPreviousHeading(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteAfterSetPaletteTest(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteAfterSetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingAfterHideTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), tests.commandTests.inputlessCommandTests.StampTests.StampTest(), tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest(), tests.commandTests.booleanCommandTests.NotEqualTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.NotTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.EqualTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.OrTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.AndTests.SyntaxErrorParseTest(), tests.commandTests.booleanConditionalCommands.IfTests.TrueTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.TrueTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorAfterMoveTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorTest(), and tests.commandTests.turtleQueryTests.YCoordinateTests.YCorAfterMoveTest().
void tests.commandTests.CommandTester.setUpStateBeforeTesting (String language) throws IOException
Definition at line 45 of file CommandTester.java.
References workspaceState.TurtleCollection.addTurtle(), and workspaceState.WorkspaceState.turtles.
Referenced by tests.commandTests.CommandTester.resetTesterVariables(), and tests.commandTests.CommandTester.setUp().
void tests.commandTests.CommandTester.setUpTranslator (String language) throws IOException
Definition at line 35 of file CommandTester.java.
References translator.Translator.createMappingsGivenLanguage(), and workspaceState.WorkspaceState.translator.
Member Data Documentation
Iterator<String> tests.commandTests.CommandTester.commands protected
Definition at line 27 of file CommandTester.java.
Referenced by tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOHomeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOTest(), tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest(), tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.recurringCommandTests.DoTimesTests.DoTimesTest(), tests.commandTests.booleanConditionalCommands.IfTests.FalseTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.FalseTest(), tests.commandTests.booleanCommandTests.LessThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotTests.FloatParseTest(), tests.commandTests.booleanCommandTests.EqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.OrTests.FloatParseTest(), tests.commandTests.booleanCommandTests.AndTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.FloatParseTest(), tests.commandTests.recurringCommandTests.ForTests.ForTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenDownTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenUpTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerParseTest(), tests.commandTests.turtleQueryTests.YCoordinateTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.RightTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.LeftTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.ForwardTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.BackwardTests.IntegerParsingTest(), tests.commandTests.turtleQueryTests.IsPenDownTests.IsPenDownTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.turtleQueryTests.IsPenDownTests.PenDownAfterPenUp(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.recurringCommandTests.RepeatTests.RepeatTest(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingNoInitialHeading(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingWithPreviousHeading(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteAfterSetPaletteTest(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteAfterSetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingAfterHideTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), tests.commandTests.inputlessCommandTests.StampTests.StampTest(), tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest(), tests.commandTests.booleanCommandTests.NotEqualTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.NotTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.EqualTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.OrTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.AndTests.SyntaxErrorParseTest(), tests.commandTests.booleanConditionalCommands.IfTests.TrueTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.TrueTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorAfterMoveTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorTest(), and tests.commandTests.turtleQueryTests.YCoordinateTests.YCorAfterMoveTest().
Queue<DrawableObject> tests.commandTests.CommandTester.objectQueue = new LinkedList<DrawableObject>() protected
Definition at line 28 of file CommandTester.java.
Referenced by tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOHomeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.BasicGOTOTest(), tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest(), tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.recurringCommandTests.DoTimesTests.DoTimesTest(), tests.commandTests.booleanConditionalCommands.IfTests.FalseTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.FalseTest(), tests.commandTests.booleanCommandTests.LessThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.NotTests.FloatParseTest(), tests.commandTests.booleanCommandTests.EqualTests.FloatParseTest(), tests.commandTests.booleanCommandTests.OrTests.FloatParseTest(), tests.commandTests.booleanCommandTests.AndTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.FloatParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.FloatParseTest(), tests.commandTests.recurringCommandTests.ForTests.ForTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenDownTest(), tests.commandTests.doubleInputFloatTests.SetPositionTests.GOTOAfterMovingAndRotatingPenUpTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), tests.commandTests.turtleQueryTests.HeadingTests.HeadingTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest(), tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongerParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerLongParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerLongParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotEqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.NotTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.OrTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.EqualTests.IntegerParseTest(), tests.commandTests.booleanCommandTests.AndTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.IntegerParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.IntegerParseTest(), tests.commandTests.turtleQueryTests.YCoordinateTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.RightTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.LeftTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.ForwardTests.IntegerParsingTest(), tests.commandTests.singleInputFloatTests.BackwardTests.IntegerParsingTest(), tests.commandTests.turtleQueryTests.IsPenDownTests.IsPenDownTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.turtleQueryTests.IsPenDownTests.PenDownAfterPenUp(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.recurringCommandTests.RepeatTests.RepeatTest(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingNoInitialHeading(), tests.commandTests.singleInputFloatTests.SetHeading.SetHeadingWithPreviousHeading(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteAfterSetPaletteTest(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteAfterSetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingAfterHideTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), tests.commandTests.inputlessCommandTests.StampTests.StampTest(), tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest(), tests.commandTests.booleanCommandTests.NotEqualTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.GreaterThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.LessThanTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.NotTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.QuotientTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.EqualTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.PowerTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.RemainderTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.SumTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.ProductTests.SyntaxErrorParseTest(), tests.commandTests.doubleInputFloatTests.DifferenceTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.OrTests.SyntaxErrorParseTest(), tests.commandTests.booleanCommandTests.AndTests.SyntaxErrorParseTest(), tests.commandTests.booleanConditionalCommands.IfTests.TrueTest(), tests.commandTests.booleanConditionalCommands.IfElseTests.TrueTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorAfterMoveTest(), tests.commandTests.turtleQueryTests.XCoordinateTests.XCorTest(), and tests.commandTests.turtleQueryTests.YCoordinateTests.YCorAfterMoveTest().
WorkspaceState tests.commandTests.CommandTester.workspace protected
Definition at line 26 of file CommandTester.java.
Referenced by tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), tests.commandTests.variableCommandTests.MakeVariableTests.ComplexMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.ComplicatedAskTests(), tests.commandTests.CommandTester.createCommand(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorAfterSettingPenColorTest(), tests.commandTests.turtleQueryTests.GetPenColorTests.GetPenColorTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest(), tests.commandTests.inputlessCommandTests.PenDownTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.PenUpTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.HeadingAfterMoveTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.HeadingAfterMoveTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), tests.commandTests.variableCommandTests.MakeVariableTests.MakeTest(), tests.commandTests.inputlessCommandTests.MakeTurtleTest.MakeTurtleIncrementsIDTester(), tests.commandTests.variableCommandTests.MakeVariableTests.ManyMakeTest(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.MultipleTurtlesWithConditionAskWithTests(), tests.commandTests.inputlessCommandTests.PenUpTests.PenUpTest(), tests.commandTests.inputlessCommandTests.PenDownTests.PenUpTest(), tests.commandTests.inputlessCommandTests.ShowTurtleTests.PenUpTest(), tests.commandTests.inputlessCommandTests.HideTurtleTests.PenUpTest(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteAfterSetPaletteTest(), tests.commandTests.colorCommandTests.SetPaletteTests.SetPaletteTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorAfterSetPenColorTest(), tests.commandTests.colorCommandTests.SetPenColorTests.SetPenColorTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeAfterSetPenSizeTest(), tests.commandTests.colorCommandTests.SetPenSizeTests.SetPenSizeTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeAfterSetShapeTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteAfterSetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapePaletteTests.SetShapePaletteTest(), tests.commandTests.colorCommandTests.SetShapeTests.SetShapeTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingAfterHideTest(), tests.commandTests.turtleQueryTests.IsShowingTests.ShowingTest(), tests.commandTests.multipleTurtleCommandTests.AskTests.SimpleAskTests(), tests.commandTests.multipleTurtleCommandTests.AskWithTests.SimpleAskWithTests(), tests.commandTests.multipleTurtleCommandTests.TellTests.SimpleTellTests(), and tests.commandTests.inputlessCommandTests.ClearStampsTest.StampTest().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/tests/commandTests/CommandTester.java