slogo_team10: gui.componentdrawers.TurtleScreenDrawer Class Reference
gui.componentdrawers.TurtleScreenDrawer Class Reference
Public Member Functions
TurtleScreenDrawer (String name, TurtleNodes turtleNodes)
void toggleGrid ()
void setTurtleScreenFeature (TurtleScreenFeature grid)
void drawShape (Node[] n)
void changeScreenColor (Color color)
void resetScreen ()
WorkspaceScreenParameters getScreenParams ()
Public Member Functions inherited from gui.componentdrawers.ComponentDrawer
ComponentDrawer (String name)
void drawShape (Node[] node)
String getName ()
Static Public Attributes
static final double GRID_WIDTH_RATIO = .6
static final double GRID_HEIGHT_RATIO = .5
static final double GRID_WIDTH = StageInitializer.SCREEN_WIDTH * GRID_WIDTH_RATIO
static final double GRID_HEIGHT = StageInitializer.SCREEN_HEIGHT * GRID_HEIGHT_RATIO
static final int GRID_NUM_ROWS = 10
static final int GRID_NUM_COLS = 10
static final int GRID_HEIGHT_DEVIATION = 20
Static Public Attributes inherited from gui.componentdrawers.ComponentDrawer
static final String TABPANE_LABEL = "tabPane"
Private Member Functions
Pane initializeGridPane ()
Line makeColLine (int col)
Line makeRowLine (int row)
Private Attributes
Color myScreenColor
TurtleScreenFeature myTurtleScreen
TurtleNodes myTurtleNodes
Pane myGrid
Detailed Description
Class manages the screen area within which the turtle is displayed and draws lines
Author
akyker20, allankiplagat
Definition at line 22 of file TurtleScreenDrawer.java.
Constructor & Destructor Documentation
gui.componentdrawers.TurtleScreenDrawer.TurtleScreenDrawer (String name, TurtleNodes turtleNodes)
Definition at line 42 of file TurtleScreenDrawer.java.
References gui.mainclasses.TextGenerator.get(), gui.componentdrawers.TurtleScreenDrawer.initializeGridPane(), and gui.mainclasses.TextGenerator.TURTLE_SCREEN.
Member Function Documentation
void gui.componentdrawers.TurtleScreenDrawer.changeScreenColor (Color color)
Changes the background color of the grid, this method is called from the SetGridColorFeature
Parameters
style
Definition at line 144 of file TurtleScreenDrawer.java.
Referenced by gui.factories.PaneFactory.generateObject(), and gui.nonbuttonfeatures.TurtleScreenFeature.TurtleScreenFeature().
void gui.componentdrawers.TurtleScreenDrawer.drawShape (Node[] n)
Overrides the super drawShapeMethod - Instead of drawing shapes on the GridDrawer pane (which would have been the default), shapes will be drawn on the grid.
Definition at line 130 of file TurtleScreenDrawer.java.
WorkspaceScreenParameters gui.componentdrawers.TurtleScreenDrawer.getScreenParams ()
Returns screen parameters. This is called by the xml file writer.
Returns
WorkspaceScreenParameters
Definition at line 161 of file TurtleScreenDrawer.java.
References XML.readers.SavedWorkspaceXMLReader.COLOR, XML.workspaceparams.WorkspaceScreenParameters.put(), and XML.readers.SavedWorkspaceXMLReader.TOGGLE_GRID.
Referenced by gui.mainclasses.workspace.Workspace.getScreenParams().
Pane gui.componentdrawers.TurtleScreenDrawer.initializeGridPane () private
Creates the gridpane whose sole purpose is to aid the ToggleRelativeGridFeature
Returns
Definition at line 56 of file TurtleScreenDrawer.java.
References gui.componentdrawers.TurtleScreenDrawer.GRID_NUM_COLS, gui.componentdrawers.TurtleScreenDrawer.GRID_NUM_ROWS, gui.componentdrawers.TurtleScreenDrawer.makeColLine(), and gui.componentdrawers.TurtleScreenDrawer.makeRowLine().
Referenced by gui.componentdrawers.TurtleScreenDrawer.TurtleScreenDrawer().
Line gui.componentdrawers.TurtleScreenDrawer.makeColLine (int col) private
Used to make the column lines of the relative grid that can be displayed when the user hits the toggle grid button.
Parameters
col
Returns
Definition at line 74 of file TurtleScreenDrawer.java.
Referenced by gui.componentdrawers.TurtleScreenDrawer.initializeGridPane().
Line gui.componentdrawers.TurtleScreenDrawer.makeRowLine (int row) private
Used to make the row lines for the relative grid that the user can turn on by hitting toggle grid.
Parameters
row
Returns
Definition at line 90 of file TurtleScreenDrawer.java.
Referenced by gui.componentdrawers.TurtleScreenDrawer.initializeGridPane().
void gui.componentdrawers.TurtleScreenDrawer.resetScreen ()
Resets the screen. This is called when the clear screen command is called.
Definition at line 152 of file TurtleScreenDrawer.java.
References gui.factories.turtlefactory.TurtleNodes.clearTurtleNodes().
Referenced by gui.factories.PaneFactory.generateObject().
void gui.componentdrawers.TurtleScreenDrawer.setTurtleScreenFeature (TurtleScreenFeature grid)
Adds the grid to the GridDrawer pane. Adds the GridPane used for drawing relative grid lines to the grid.
Parameters
grid
Definition at line 119 of file TurtleScreenDrawer.java.
Referenced by gui.nonbuttonfeatures.TurtleScreenFeature.TurtleScreenFeature().
void gui.componentdrawers.TurtleScreenDrawer.toggleGrid ()
If the grid lines are already visible, they are removed. Otherwise, the grid lines are displayed.
Definition at line 104 of file TurtleScreenDrawer.java.
Referenced by gui.buttonfeatures.ToggleGridButtonFeature.ToggleGridButtonFeature(), and gui.nonbuttonfeatures.TurtleScreenFeature.TurtleScreenFeature().
Member Data Documentation
final double gui.componentdrawers.TurtleScreenDrawer.GRID_HEIGHT = StageInitializer.SCREEN_HEIGHT * GRID_HEIGHT_RATIO static
Definition at line 27 of file TurtleScreenDrawer.java.
Referenced by gui.nonbuttonfeatures.TurtleScreenFeature.TurtleScreenFeature().
final int gui.componentdrawers.TurtleScreenDrawer.GRID_HEIGHT_DEVIATION = 20 static
Definition at line 30 of file TurtleScreenDrawer.java.
final double gui.componentdrawers.TurtleScreenDrawer.GRID_HEIGHT_RATIO = .5 static
Definition at line 25 of file TurtleScreenDrawer.java.
final int gui.componentdrawers.TurtleScreenDrawer.GRID_NUM_COLS = 10 static
Definition at line 29 of file TurtleScreenDrawer.java.
Referenced by gui.componentdrawers.TurtleScreenDrawer.initializeGridPane().
final int gui.componentdrawers.TurtleScreenDrawer.GRID_NUM_ROWS = 10 static
Definition at line 28 of file TurtleScreenDrawer.java.
Referenced by gui.componentdrawers.TurtleScreenDrawer.initializeGridPane().
final double gui.componentdrawers.TurtleScreenDrawer.GRID_WIDTH = StageInitializer.SCREEN_WIDTH * GRID_WIDTH_RATIO static
Definition at line 26 of file TurtleScreenDrawer.java.
Referenced by gui.nonbuttonfeatures.TurtleScreenFeature.TurtleScreenFeature().
final double gui.componentdrawers.TurtleScreenDrawer.GRID_WIDTH_RATIO = .6 static
Definition at line 24 of file TurtleScreenDrawer.java.
Referenced by gui.componentdrawers.CommandLineDrawer.CommandLineDrawer(), gui.componentdrawers.ErrorDrawer.ErrorDrawer(), and gui.componentdrawers.PreviousCommandsDrawer.PreviousCommandsDrawer().
Pane gui.componentdrawers.TurtleScreenDrawer.myGrid private
Definition at line 40 of file TurtleScreenDrawer.java.
Color gui.componentdrawers.TurtleScreenDrawer.myScreenColor private
Definition at line 32 of file TurtleScreenDrawer.java.
TurtleNodes gui.componentdrawers.TurtleScreenDrawer.myTurtleNodes private
Definition at line 37 of file TurtleScreenDrawer.java.
TurtleScreenFeature gui.componentdrawers.TurtleScreenDrawer.myTurtleScreen private
Definition at line 35 of file TurtleScreenDrawer.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/componentdrawers/TurtleScreenDrawer.java