slogo_team10: gui.nonbuttonfeatures.pen.PenColorPickerFeature Class Reference
gui.nonbuttonfeatures.pen.PenColorPickerFeature Class Reference
Public Member Functions
PenColorPickerFeature (OptionsHolderDrawer parentDrawer, Workspace workspace)
Public Member Functions inherited from gui.nonbuttonfeatures.ColorPickerFeature
ColorPickerFeature (OptionsHolderDrawer parentDrawer)
Private Member Functions
void changePenColor ()
String getRGBStr ()
Private Attributes
Workspace myWorkspace
Static Private Attributes
static final String SET_PEN_COLOR = "setpencolor 0"
static final String SET_PALETTE = "setpalette"
static final int RGB_CONVERSION = 255
Detailed Description
Feature that allows user to interactively change the color of the pen without using the command line. This feature will be located in the Pen tab in the options TabPane in the lower right hand corner of the IDE.
Author
Austin Kyker
Definition at line 17 of file PenColorPickerFeature.java.
Constructor & Destructor Documentation
gui.nonbuttonfeatures.pen.PenColorPickerFeature.PenColorPickerFeature (OptionsHolderDrawer parentDrawer, Workspace workspace)
Definition at line 25 of file PenColorPickerFeature.java.
References gui.nonbuttonfeatures.pen.PenColorPickerFeature.changePenColor().
Member Function Documentation
void gui.nonbuttonfeatures.pen.PenColorPickerFeature.changePenColor () private
Calls parse command on the control to let the back end know that the color of the pen has been changed.
Definition at line 35 of file PenColorPickerFeature.java.
References gui.nonbuttonfeatures.pen.PenColorPickerFeature.getRGBStr(), and gui.mainclasses.workspace.Workspace.parseCommandString().
Referenced by gui.nonbuttonfeatures.pen.PenColorPickerFeature.PenColorPickerFeature().
String gui.nonbuttonfeatures.pen.PenColorPickerFeature.getRGBStr () private
Definition at line 40 of file PenColorPickerFeature.java.
References gui.nonbuttonfeatures.pen.PenColorPickerFeature.RGB_CONVERSION.
Referenced by gui.nonbuttonfeatures.pen.PenColorPickerFeature.changePenColor().
Member Data Documentation
Workspace gui.nonbuttonfeatures.pen.PenColorPickerFeature.myWorkspace private
Definition at line 23 of file PenColorPickerFeature.java.
final int gui.nonbuttonfeatures.pen.PenColorPickerFeature.RGB_CONVERSION = 255 static private
Definition at line 21 of file PenColorPickerFeature.java.
Referenced by gui.nonbuttonfeatures.pen.PenColorPickerFeature.getRGBStr().
final String gui.nonbuttonfeatures.pen.PenColorPickerFeature.SET_PALETTE = "setpalette" static private
Definition at line 20 of file PenColorPickerFeature.java.
final String gui.nonbuttonfeatures.pen.PenColorPickerFeature.SET_PEN_COLOR = "setpencolor 0" static private
Definition at line 19 of file PenColorPickerFeature.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/nonbuttonfeatures/pen/PenColorPickerFeature.java