slogo_team10: commandParsing.structuralCommandParsing.StructuralCommand Class Reference
commandParsing.structuralCommandParsing.StructuralCommand Class Reference abstract
Public Member Functions
StructuralCommand (WorkspaceState someWorkspace)
Public Member Functions inherited from commandParsing.CommandParser
CommandParser (WorkspaceState someWorkspace)
abstract double parse (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Protected Member Functions
void checkForOpeningBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException
void checkForClosingBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException
void extractCommandsBetweenBraces (Iterator< String > commandStringIterator) throws CompileTimeParsingException, RunTimeDivideByZeroException, RunTimeNullPointerException
void parseCommandsBetweenBraces (Iterator< String > commands, Queue< DrawableObject > objectQueue) throws SLOGOException
void setEnclosedCommandsToEmptyList ()
void ignoreUntilClosingBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException
String getVariable (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException
Protected Member Functions inherited from commandParsing.CommandParser
void accumulateComponents (Iterator< String > commandStringIterator, int numberToAccumulate, Queue< DrawableObject > objectQueue) throws SLOGOException
boolean isStringParsableAsCommand (String string)
Protected Attributes
List< String > enclosedCommands
double returnValue
Protected Attributes inherited from commandParsing.CommandParser
List< Double > expressionComponents = new ArrayList<Double>()
Private Member Functions
boolean findBrace (Iterator< String > commandStringIterator)
Additional Inherited Members
Static Public Member Functions inherited from commandParsing.CommandParser
static CommandParser createParser (String commandName, WorkspaceState workspace) throws CompileTimeParsingException
Static Protected Attributes inherited from commandParsing.CommandParser
static WorkspaceState workspace
Detailed Description
This is the abstract class for all kinds of structural command parsing.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 24 of file StructuralCommand.java.
Constructor & Destructor Documentation
commandParsing.structuralCommandParsing.StructuralCommand.StructuralCommand (WorkspaceState someWorkspace)
Definition at line 26 of file StructuralCommand.java.
Member Function Documentation
void commandParsing.structuralCommandParsing.StructuralCommand.checkForClosingBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException protected
Definition at line 40 of file StructuralCommand.java.
References translator.Translator.matchesListEndPattern(), workspaceState.WorkspaceState.translator, and commandParsing.CommandParser.workspace.
Referenced by commandParsing.structuralCommandParsing.DoTimes.initializeLoopVariableParameters(), and commandParsing.structuralCommandParsing.For.initializeLoopVariableParameters().
void commandParsing.structuralCommandParsing.StructuralCommand.checkForOpeningBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException protected
Definition at line 33 of file StructuralCommand.java.
References translator.Translator.matchesListStartPattern(), workspaceState.WorkspaceState.translator, and commandParsing.CommandParser.workspace.
Referenced by commandParsing.structuralCommandParsing.StructuralCommand.extractCommandsBetweenBraces(), commandParsing.structuralCommandParsing.StructuralCommand.ignoreUntilClosingBrace(), commandParsing.structuralCommandParsing.DoTimes.initializeLoopVariableParameters(), and commandParsing.structuralCommandParsing.For.initializeLoopVariableParameters().
void commandParsing.structuralCommandParsing.StructuralCommand.extractCommandsBetweenBraces (Iterator< String > commandStringIterator) throws CompileTimeParsingException, RunTimeDivideByZeroException, RunTimeNullPointerException protected
Definition at line 47 of file StructuralCommand.java.
References commandParsing.structuralCommandParsing.StructuralCommand.checkForOpeningBrace(), translator.Translator.matchesListEndPattern(), translator.Translator.matchesListStartPattern(), workspaceState.WorkspaceState.translator, and commandParsing.CommandParser.workspace.
Referenced by commandParsing.structuralCommandParsing.Ask.parse(), commandParsing.structuralCommandParsing.IfElse.parse(), commandParsing.structuralCommandParsing.Tell.parse(), commandParsing.structuralCommandParsing.If.parse(), commandParsing.structuralCommandParsing.AskWith.parse(), commandParsing.structuralCommandParsing.RecurringCommand.parse(), and commandParsing.userCommandParsing.MakeUserInstruction.parse().
boolean commandParsing.structuralCommandParsing.StructuralCommand.findBrace (Iterator< String > commandStringIterator) private
Definition at line 102 of file StructuralCommand.java.
References translator.Translator.matchesListEndPattern(), translator.Translator.matchesListStartPattern(), workspaceState.WorkspaceState.translator, and commandParsing.CommandParser.workspace.
Referenced by commandParsing.structuralCommandParsing.StructuralCommand.ignoreUntilClosingBrace().
String commandParsing.structuralCommandParsing.StructuralCommand.getVariable (Iterator< String > commandStringIterator, Queue< DrawableObject > objectQueue) throws SLOGOException protected
Definition at line 115 of file StructuralCommand.java.
References commandParsing.CommandParser.createParser(), commandParsing.variableCommandParsing.Variable.getVariableName(), commandParsing.variableCommandParsing.Variable.parse(), and commandParsing.CommandParser.workspace.
Referenced by commandParsing.structuralCommandParsing.DoTimes.initializeLoopVariableParameters(), commandParsing.structuralCommandParsing.For.initializeLoopVariableParameters(), and commandParsing.userCommandParsing.MakeUserInstruction.parse().
void commandParsing.structuralCommandParsing.StructuralCommand.ignoreUntilClosingBrace (Iterator< String > commandStringIterator) throws CompileTimeParsingException protected
Definition at line 94 of file StructuralCommand.java.
References commandParsing.structuralCommandParsing.StructuralCommand.checkForOpeningBrace(), and commandParsing.structuralCommandParsing.StructuralCommand.findBrace().
Referenced by commandParsing.structuralCommandParsing.If.parse(), and commandParsing.structuralCommandParsing.IfElse.parse().
void commandParsing.structuralCommandParsing.StructuralCommand.parseCommandsBetweenBraces (Iterator< String > commands, Queue< DrawableObject > objectQueue) throws SLOGOException protected
Definition at line 77 of file StructuralCommand.java.
References commandParsing.CommandParser.createParser(), commandParsing.CommandParser.parse(), and commandParsing.CommandParser.workspace.
Referenced by commandParsing.structuralCommandParsing.Ask.parse(), commandParsing.structuralCommandParsing.IfElse.parse(), commandParsing.structuralCommandParsing.If.parse(), commandParsing.structuralCommandParsing.AskWith.parse(), commandParsing.structuralCommandParsing.RecurringCommand.parse(), and commandParsing.userCommandParsing.MakeUserInstruction.parse().
void commandParsing.structuralCommandParsing.StructuralCommand.setEnclosedCommandsToEmptyList () protected
Definition at line 90 of file StructuralCommand.java.
Referenced by commandParsing.structuralCommandParsing.If.parse().
Member Data Documentation
List<String> commandParsing.structuralCommandParsing.StructuralCommand.enclosedCommands protected
Definition at line 30 of file StructuralCommand.java.
Referenced by commandParsing.structuralCommandParsing.Ask.parse(), commandParsing.structuralCommandParsing.IfElse.parse(), commandParsing.structuralCommandParsing.Tell.parse(), commandParsing.structuralCommandParsing.If.parse(), commandParsing.structuralCommandParsing.AskWith.parse(), commandParsing.structuralCommandParsing.RecurringCommand.parse(), and commandParsing.userCommandParsing.MakeUserInstruction.parse().
double commandParsing.structuralCommandParsing.StructuralCommand.returnValue protected
Definition at line 31 of file StructuralCommand.java.
Referenced by commandParsing.structuralCommandParsing.MultipleTurtleCommand.determineTurtlesToActivate(), commandParsing.structuralCommandParsing.Ask.parse(), commandParsing.structuralCommandParsing.IfElse.parse(), commandParsing.structuralCommandParsing.If.parse(), commandParsing.structuralCommandParsing.AskWith.parse(), and commandParsing.structuralCommandParsing.RecurringCommand.parse().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/commandParsing/structuralCommandParsing/StructuralCommand.java