slogo_team10: gui.nonbuttonfeatures.pen.PenThicknessSliderFeature Class Reference
gui.nonbuttonfeatures.pen.PenThicknessSliderFeature Class Reference
Public Member Functions
PenThicknessSliderFeature (OptionsHolderDrawer parentDrawer, Workspace workspace)
Private Member Functions
void setPenSize ()
void setSliderProperties ()
Private Attributes
Workspace myWorkspace
Static Private Attributes
static final String SET_PEN_SIZE = "setpensize"
static final int SLIDER_MIN = 1
static final int SLIDER_MAX = 5
static final int SLIDER_START = 5
static final int SLIDER_TICK_UNIT = 1
Detailed Description
This feature allows the user to change the thickness of the pen in pixels interactively from the Pen tab in the options TabPane. The user simply slides the slider to the thickness of the pixels desired and the back-end is notified of the change so the pen workspace class can be updated.
Author
Austin Kyker
Definition at line 18 of file PenThicknessSliderFeature.java.
Constructor & Destructor Documentation
gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.PenThicknessSliderFeature (OptionsHolderDrawer parentDrawer, Workspace workspace)
Definition at line 28 of file PenThicknessSliderFeature.java.
References gui.componentdrawers.ComponentDrawer.drawShape(), gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.setPenSize(), and gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.setSliderProperties().
Member Function Documentation
void gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.setPenSize () private
Definition at line 35 of file PenThicknessSliderFeature.java.
References gui.mainclasses.workspace.Workspace.parseCommandString().
Referenced by gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.PenThicknessSliderFeature().
void gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.setSliderProperties () private
Sets the properties of the slider.
Definition at line 42 of file PenThicknessSliderFeature.java.
References gui.buttonfeatures.ButtonFeature.BUTTON_WIDTH.
Referenced by gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.PenThicknessSliderFeature().
Member Data Documentation
Workspace gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.myWorkspace private
Definition at line 26 of file PenThicknessSliderFeature.java.
final String gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.SET_PEN_SIZE = "setpensize" static private
Definition at line 20 of file PenThicknessSliderFeature.java.
final int gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.SLIDER_MAX = 5 static private
Definition at line 22 of file PenThicknessSliderFeature.java.
final int gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.SLIDER_MIN = 1 static private
Definition at line 21 of file PenThicknessSliderFeature.java.
final int gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.SLIDER_START = 5 static private
Definition at line 23 of file PenThicknessSliderFeature.java.
final int gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.SLIDER_TICK_UNIT = 1 static private
Definition at line 24 of file PenThicknessSliderFeature.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/nonbuttonfeatures/pen/PenThicknessSliderFeature.java