slogo_team10: gui.menus.HelpMenu Class Reference
gui.menus.HelpMenu Class Reference
Public Member Functions
HelpMenu ()
Static Public Attributes
static final String BASIC_COMMANDS_URL
static final String EXTENDED_COMMANDS_URL
static final int HELP_PAGE_WIDTH = 800
static final int HELP_PAGE_HEIGHT = 600
Protected Member Functions
void displayHelpPage (String url)
Detailed Description
Sets up a help menu with several different options. The getting started menu item displays an HTML page that tells the user
Author
Austin Kyker
Definition at line 22 of file HelpMenu.java.
Constructor & Destructor Documentation
gui.menus.HelpMenu.HelpMenu ()
Definition at line 32 of file HelpMenu.java.
References gui.mainclasses.TextGenerator.BASIC_COMMANDS, gui.mainclasses.TextGenerator.COMPLEX_COMMANDS, gui.menus.HelpMenu.displayHelpPage(), gui.mainclasses.TextGenerator.get(), gui.mainclasses.TextGenerator.GETTING_STARTED, and gui.mainclasses.TextGenerator.HELP.
Member Function Documentation
void gui.menus.HelpMenu.displayHelpPage (String url) protected
Definition at line 63 of file HelpMenu.java.
Referenced by gui.menus.HelpMenu.HelpMenu().
Member Data Documentation
final String gui.menus.HelpMenu.BASIC_COMMANDS_URL static
Initial value:
=
            "http://www.cs.duke.edu/courses/compsci308/current/assign/03_slogo/commands.php"
Definition at line 24 of file HelpMenu.java.
final String gui.menus.HelpMenu.EXTENDED_COMMANDS_URL static
Initial value:
=
            "http://www.cs.duke.edu/courses/compsci308/current/assign/03_slogo/commands2.php"
Definition at line 26 of file HelpMenu.java.
final int gui.menus.HelpMenu.HELP_PAGE_HEIGHT = 600 static
Definition at line 30 of file HelpMenu.java.
final int gui.menus.HelpMenu.HELP_PAGE_WIDTH = 800 static
Definition at line 29 of file HelpMenu.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/menus/HelpMenu.java