slogo_team10: XML.XMLParser Class Reference
XML.XMLParser Class Reference
Public Member Functions
XMLParser (Stage aStage) throws Exception
void startElement (String uri, String localName, String elementName, Attributes attributes) throws SAXException
Package Attributes
Stage stage
SAXParserFactory docFactory = SAXParserFactory.newInstance()
SAXParser saxParser = docFactory.newSAXParser()
Queue< DrawableObject > objectQueue = new LinkedList<DrawableObject>()
String parent
String type
String name
Map< String, String > rawParameters = new HashMap<>()
Private Member Functions
void parseFile () throws SAXException, IOException
Static Private Member Functions
static void configureFileChooser (FileChooser fileChooser)
Private Attributes
FileChooser chooser = new FileChooser()
Detailed Description
Definition at line 19 of file XMLParser.java.
Constructor & Destructor Documentation
XML.XMLParser.XMLParser (Stage aStage) throws Exception
Definition at line 32 of file XMLParser.java.
References XML.XMLParser.configureFileChooser(), and XML.XMLParser.parseFile().
Member Function Documentation
static void XML.XMLParser.configureFileChooser (FileChooser fileChooser) static private
Definition at line 38 of file XMLParser.java.
Referenced by XML.XMLParser.XMLParser().
void XML.XMLParser.parseFile () throws SAXException, IOException private
Definition at line 49 of file XMLParser.java.
Referenced by XML.XMLParser.XMLParser().
void XML.XMLParser.startElement (String uri, String localName, String elementName, Attributes attributes) throws SAXException
Definition at line 61 of file XMLParser.java.
Member Data Documentation
FileChooser XML.XMLParser.chooser = new FileChooser() private
Definition at line 21 of file XMLParser.java.
SAXParserFactory XML.XMLParser.docFactory = SAXParserFactory.newInstance() package
Definition at line 22 of file XMLParser.java.
String XML.XMLParser.name package
Definition at line 29 of file XMLParser.java.
Queue<DrawableObject> XML.XMLParser.objectQueue = new LinkedList<DrawableObject>() package
Definition at line 25 of file XMLParser.java.
String XML.XMLParser.parent package
Definition at line 27 of file XMLParser.java.
Map<String, String> XML.XMLParser.rawParameters = new HashMap<>() package
Definition at line 30 of file XMLParser.java.
SAXParser XML.XMLParser.saxParser = docFactory.newSAXParser() package
Definition at line 23 of file XMLParser.java.
Stage XML.XMLParser.stage package
Definition at line 20 of file XMLParser.java.
String XML.XMLParser.type package
Definition at line 28 of file XMLParser.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/XML/XMLParser.java