slogo_team10: XML.readers.SavedWorkspaceXMLReader Class Reference
XML.readers.SavedWorkspaceXMLReader Class Reference
Public Member Functions
SavedWorkspaceXMLReader (File file) throws ParserConfigurationException, FileNotFoundException, SAXException, IOException
WorkspacePenCommands getInitialPenCommands ()
WorkspaceScreenParameters getScreenParameters ()
ObservableList< WorkspaceVariable > getWorkspaceVariables ()
ObservableList< DisplayedUserCommand > getUserDefinedCommands ()
ObservableList< String > getSavedCommands ()
ObservableList< String > getStringListFromElements (String elementName)
WorkspaceDataHolder getWorkspaceDataHolder ()
Static Public Attributes
static final String COMMAND = "command"
static final String SCREEN = "screen"
static final String COLOR = "color"
static final String TOGGLE_GRID = "toggleGrid"
static final String TRUE = "true"
static final String PIXELS = "pixels"
static final String USER_DEFINED_CMDS = "userdefinedcommands"
static final String NAME = "name"
static final String WORKSPACE = "workspace"
static final String WORKSPACE_VAR = "workspacevariable"
static final String VARIABLE = "variable"
static final String VALUE = "value"
static final String SAVED_COMMANDS = "savedcommands"
static final String STATUS = "status"
static final String GREEN = "g"
static final String RED = "r"
static final String BLUE = "b"
static final String PEN = "pen"
static final String SET_PEN_SIZE = "setpensize "
static final String PARAMS = "params"
Private Attributes
Element myRoot
Static Private Attributes
static final String SET_FIRST_PALETTE_INDEX = "setpalette 0 "
static final String SET_PEN_COLOR = "setpencolor 0"
Detailed Description
The purpose of this class is to read workspace configurations from an xml file.
Author
Austin Kyker
Definition at line 28 of file SavedWorkspaceXMLReader.java.
Constructor & Destructor Documentation
XML.readers.SavedWorkspaceXMLReader.SavedWorkspaceXMLReader (File file) throws ParserConfigurationException, FileNotFoundException, SAXException, IOException
Gets the root element of the file.
Parameters
file
Exceptions
ParserConfigurationException
FileNotFoundException
SAXException
IOException
Definition at line 63 of file SavedWorkspaceXMLReader.java.
Member Function Documentation
WorkspacePenCommands XML.readers.SavedWorkspaceXMLReader.getInitialPenCommands ()
Retrieves the initial pen parameters from the xml file and creates a list of commands that will create these parameters.
Returns
List of commands
Definition at line 76 of file SavedWorkspaceXMLReader.java.
References XML.workspaceparams.WorkspacePenCommands.addCommand().
Referenced by gui.menus.FileMenu.FileMenu().
ObservableList<String> XML.readers.SavedWorkspaceXMLReader.getSavedCommands ()
Retrieves a list of saved commands from the XML File.
Returns
Definition at line 140 of file SavedWorkspaceXMLReader.java.
References XML.readers.SavedWorkspaceXMLReader.getStringListFromElements().
Referenced by XML.readers.SavedWorkspaceXMLReader.getWorkspaceDataHolder().
WorkspaceScreenParameters XML.readers.SavedWorkspaceXMLReader.getScreenParameters ()
Retrieves the parameters for the screen from the xml file.
Returns
Definition at line 94 of file SavedWorkspaceXMLReader.java.
References XML.workspaceparams.WorkspaceScreenParameters.put().
Referenced by gui.menus.FileMenu.FileMenu().
ObservableList<String> XML.readers.SavedWorkspaceXMLReader.getStringListFromElements (String elementName)
Helper function to get a list from a node list in an xml file.
Parameters
elementName
Returns
Definition at line 149 of file SavedWorkspaceXMLReader.java.
Referenced by XML.readers.SavedWorkspaceXMLReader.getSavedCommands().
ObservableList<DisplayedUserCommand> XML.readers.SavedWorkspaceXMLReader.getUserDefinedCommands ()
Retrieves a list of user defined commands from the xml file.
Returns
Definition at line 122 of file SavedWorkspaceXMLReader.java.
Referenced by gui.menus.FileMenu.FileMenu(), and XML.readers.SavedWorkspaceXMLReader.getWorkspaceDataHolder().
WorkspaceDataHolder XML.readers.SavedWorkspaceXMLReader.getWorkspaceDataHolder ()
A workspace data holder that holds all of the information parsed from the xml file.
Returns
A workspace data holder
Definition at line 164 of file SavedWorkspaceXMLReader.java.
References XML.readers.SavedWorkspaceXMLReader.getSavedCommands(), XML.readers.SavedWorkspaceXMLReader.getUserDefinedCommands(), and XML.readers.SavedWorkspaceXMLReader.getWorkspaceVariables().
Referenced by gui.menus.FileMenu.FileMenu().
ObservableList<WorkspaceVariable> XML.readers.SavedWorkspaceXMLReader.getWorkspaceVariables ()
Retrieves a list of workspace variables from the xml file.
Returns
Definition at line 106 of file SavedWorkspaceXMLReader.java.
Referenced by gui.menus.FileMenu.FileMenu(), and XML.readers.SavedWorkspaceXMLReader.getWorkspaceDataHolder().
Member Data Documentation
final String XML.readers.SavedWorkspaceXMLReader.BLUE = "b" static
Definition at line 48 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.COLOR = "color" static
Definition at line 34 of file SavedWorkspaceXMLReader.java.
Referenced by gui.componentdrawers.TurtleScreenDrawer.getScreenParams(), and XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.COMMAND = "command" static
Definition at line 32 of file SavedWorkspaceXMLReader.java.
Referenced by XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.GREEN = "g" static
Definition at line 46 of file SavedWorkspaceXMLReader.java.
Element XML.readers.SavedWorkspaceXMLReader.myRoot private
Definition at line 53 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.NAME = "name" static
Definition at line 39 of file SavedWorkspaceXMLReader.java.
Referenced by XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.PARAMS = "params" static
Definition at line 51 of file SavedWorkspaceXMLReader.java.
Referenced by XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.PEN = "pen" static
Definition at line 49 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.PIXELS = "pixels" static
Definition at line 37 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.RED = "r" static
Definition at line 47 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.SAVED_COMMANDS = "savedcommands" static
Definition at line 44 of file SavedWorkspaceXMLReader.java.
Referenced by XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.SCREEN = "screen" static
Definition at line 33 of file SavedWorkspaceXMLReader.java.
Referenced by XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.SET_FIRST_PALETTE_INDEX = "setpalette 0 " static private
Definition at line 30 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.SET_PEN_COLOR = "setpencolor 0" static private
Definition at line 31 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.SET_PEN_SIZE = "setpensize " static
Definition at line 50 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.STATUS = "status" static
Definition at line 45 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.TOGGLE_GRID = "toggleGrid" static
Definition at line 35 of file SavedWorkspaceXMLReader.java.
Referenced by gui.componentdrawers.TurtleScreenDrawer.getScreenParams(), and XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.TRUE = "true" static
Definition at line 36 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.USER_DEFINED_CMDS = "userdefinedcommands" static
Definition at line 38 of file SavedWorkspaceXMLReader.java.
Referenced by XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.VALUE = "value" static
Definition at line 43 of file SavedWorkspaceXMLReader.java.
Referenced by XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.VARIABLE = "variable" static
Definition at line 42 of file SavedWorkspaceXMLReader.java.
final String XML.readers.SavedWorkspaceXMLReader.WORKSPACE = "workspace" static
Definition at line 40 of file SavedWorkspaceXMLReader.java.
Referenced by XML.writers.SavedWorkspaceXMLWriter.writeFile().
final String XML.readers.SavedWorkspaceXMLReader.WORKSPACE_VAR = "workspacevariable" static
Definition at line 41 of file SavedWorkspaceXMLReader.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/XML/readers/SavedWorkspaceXMLReader.java