slogo_team10: tests.commandTests.inputlessCommandTests.HomeTests Class Reference
tests.commandTests.inputlessCommandTests.HomeTests Class Reference
Public Member Functions
void BasicHomeTest () throws SLOGOException
void HomeAfterMovingAndRotatingPenDownTest () throws SLOGOException
void HomeAfterMovingAndRotatingPenUpTest () throws SLOGOException
Public Member Functions inherited from tests.commandTests.CommandTester
void setUp () throws Exception
void setUpTranslator (String language) throws IOException
void setUpStateBeforeTesting (String language) throws IOException
void setUpCommands (String input)
void resetTesterVariables ()
CommandParser createCommand () throws RunTimeNullPointerException, CompileTimeParsingException
Additional Inherited Members
Protected Attributes inherited from tests.commandTests.CommandTester
WorkspaceState workspace
Iterator< String > commands
Queue< DrawableObject > objectQueue = new LinkedList<DrawableObject>()
Detailed Description
Definition at line 13 of file HomeTests.java.
Member Function Documentation
void tests.commandTests.inputlessCommandTests.HomeTests.BasicHomeTest () throws SLOGOException
Definition at line 15 of file HomeTests.java.
References tests.commandTests.CommandTester.commands, tests.commandTests.CommandTester.createCommand(), gui.factories.LineFactory.DESTINATION, drawableobject.DrawableObject.getParameters(), drawableobject.DrawableObject.getParent(), drawableobject.DrawableObject.getType(), gui.factories.turtlefactory.TurtleFactory.HEADING, gui.factories.turtlefactory.TurtleFactory.LOCATION, tests.commandTests.CommandTester.objectQueue, gui.factories.LineFactory.ORIGIN, gui.factories.turtlefactory.TurtleFactory.PARENT, gui.factories.LineFactory.PARENT, commandParsing.CommandParser.parse(), tests.commandTests.CommandTester.resetTesterVariables(), tests.commandTests.CommandTester.setUpCommands(), gui.factories.turtlefactory.TurtleFactory.TYPE, and gui.factories.LineFactory.TYPE.
void tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenDownTest () throws SLOGOException
Definition at line 39 of file HomeTests.java.
References tests.commandTests.CommandTester.commands, tests.commandTests.CommandTester.createCommand(), gui.factories.LineFactory.DESTINATION, drawableobject.DrawableObject.getParameters(), drawableobject.DrawableObject.getParent(), drawableobject.DrawableObject.getType(), gui.factories.turtlefactory.TurtleFactory.HEADING, gui.factories.turtlefactory.TurtleFactory.LOCATION, tests.commandTests.CommandTester.objectQueue, gui.factories.LineFactory.ORIGIN, gui.factories.turtlefactory.TurtleFactory.PARENT, gui.factories.LineFactory.PARENT, commandParsing.CommandParser.parse(), tests.commandTests.CommandTester.resetTesterVariables(), tests.commandTests.CommandTester.setUpCommands(), gui.factories.turtlefactory.TurtleFactory.TYPE, and gui.factories.LineFactory.TYPE.
void tests.commandTests.inputlessCommandTests.HomeTests.HomeAfterMovingAndRotatingPenUpTest () throws SLOGOException
Definition at line 69 of file HomeTests.java.
References tests.commandTests.CommandTester.commands, tests.commandTests.CommandTester.createCommand(), drawableobject.DrawableObject.getParameters(), drawableobject.DrawableObject.getParent(), drawableobject.DrawableObject.getType(), gui.factories.turtlefactory.TurtleFactory.HEADING, gui.factories.turtlefactory.TurtleFactory.LOCATION, tests.commandTests.CommandTester.objectQueue, gui.factories.turtlefactory.TurtleFactory.PARENT, commandParsing.CommandParser.parse(), tests.commandTests.CommandTester.resetTesterVariables(), tests.commandTests.CommandTester.setUpCommands(), and gui.factories.turtlefactory.TurtleFactory.TYPE.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/tests/commandTests/inputlessCommandTests/HomeTests.java