slogo_team10: workspaceState.Shape Class Reference
workspaceState.Shape Class Reference
Public Member Functions
Shape (String path)
String getPath ()
boolean equals (Object o)
Private Attributes
String URI
Detailed Description
This class is the Shape class that contains all of the information for each Shape.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 10 of file Shape.java.
Constructor & Destructor Documentation
workspaceState.Shape.Shape (String path)
Definition at line 13 of file Shape.java.
Referenced by workspaceState.Shape.equals().
Member Function Documentation
boolean workspaceState.Shape.equals (Object o)
Definition at line 22 of file Shape.java.
References workspaceState.Shape.Shape(), and workspaceState.Shape.URI.
String workspaceState.Shape.getPath ()
Definition at line 17 of file Shape.java.
References workspaceState.Shape.URI.
Referenced by commandParsing.drawableObectGenerationInterfaces.ShapePaletteUpdateGenerator.generateDrawableObjectRepresentingShapePaletteUpdate(), commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtle(), tests.commandTests.colorCommandTests.GetShapeTests.GetShapeTest(), and workspaceState.Turtle.Turtle().
Member Data Documentation
String workspaceState.Shape.URI private
Definition at line 11 of file Shape.java.
Referenced by workspaceState.Shape.equals(), and workspaceState.Shape.getPath().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/workspaceState/Shape.java