slogo_team10: gui.componentdrawers.ComponentDrawer Class Reference
gui.componentdrawers.ComponentDrawer Class Reference abstract
Public Member Functions
ComponentDrawer (String name)
void drawShape (Node[] node)
String getName ()
Static Public Attributes
static final String TABPANE_LABEL = "tabPane"
Private Attributes
String myName
Detailed Description
Class represents a component of the GUI e.g. GridDrawer. Each of these components contains at least one feature.
Author
akyker20, allankiplagat
Definition at line 15 of file ComponentDrawer.java.
Constructor & Destructor Documentation
gui.componentdrawers.ComponentDrawer.ComponentDrawer (String name)
Definition at line 20 of file ComponentDrawer.java.
Member Function Documentation
void gui.componentdrawers.ComponentDrawer.drawShape (Node[] node)
Draws a shape in this component
Parameters
node
Definition at line 30 of file ComponentDrawer.java.
Referenced by gui.buttonfeatures.ButtonFeature.ButtonFeature(), gui.nonbuttonfeatures.ColorPickerFeature.ColorPickerFeature(), gui.componentdrawers.CommandLineDrawer.CommandLineDrawer(), gui.nonbuttonfeatures.CommandLineFeature.CommandLineFeature(), gui.mainclasses.DrawableObjectParser.parseDrawableObject(), gui.nonbuttonfeatures.pen.PenChoiceBox.PenChoiceBox(), gui.nonbuttonfeatures.pen.PenThicknessSliderFeature.PenThicknessSliderFeature(), gui.componentdrawers.PreviousCommandsDrawer.PreviousCommandsDrawer(), gui.nonbuttonfeatures.PreviousCommandsFeature.PreviousCommandsFeature(), and gui.componentdrawers.WorkspaceVariablesDrawer.WorkspaceVariablesDrawer().
String gui.componentdrawers.ComponentDrawer.getName ()
Returns the name of the component assigned by the constructor This method will be used in the DrawableObjectParser class to parse the correct component in which to draw a shape
Returns
Definition at line 42 of file ComponentDrawer.java.
References gui.componentdrawers.ComponentDrawer.myName.
Member Data Documentation
String gui.componentdrawers.ComponentDrawer.myName private
Definition at line 17 of file ComponentDrawer.java.
Referenced by gui.componentdrawers.ComponentDrawer.getName().
final String gui.componentdrawers.ComponentDrawer.TABPANE_LABEL = "tabPane" static
Definition at line 18 of file ComponentDrawer.java.
Referenced by gui.componentdrawers.optionsholder.OptionsHolderDrawer.OptionsHolderDrawer(), and gui.componentdrawers.significantcommands.SignificantCommandsDrawer.SignificantCommandsDrawer().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/componentdrawers/ComponentDrawer.java