slogo_team10: gui.componentdrawers.ComponentBuilder Class Reference
gui.componentdrawers.ComponentBuilder Class Reference
Static Public Member Functions
static Map< String, ComponentDrawer > build (BorderPane pane, TurtleNodes turtleNodes)
Static Public Attributes
static final String SCREEN_DRAWER = "ScreenDrawer"
static final String MENU_DRAWER = "MenuDrawer"
static final String COMMAND_LINE_DRAWER = "CommandLineDrawer"
static final String BUTTON_HOLDER_DRAWER = "ButtonHolderDrawer"
static final String PREVIOUS_COMMANDS = "previousCommandsDrawer"
static final String WORKSPACE_VARIABLES = "workspaceVariablesDrawer"
static final String WORKSPACE_COMMANDS = "workspaceCommandDrawer"
static final String SIGNIFICANT_COMMANDS_DRAWER = "significantCommandsDrawer"
static final String ERROR_DRAWER = "errorDrawer"
static final int PADDING = 10
Static Private Member Functions
static void buildRightComponents (BorderPane pane, Map< String, ComponentDrawer > drawerMap)
static void buildLeftComponents (BorderPane pane, Map< String, ComponentDrawer > drawerMap)
static void addComponentsToBox (Map< String, ComponentDrawer > drawerMap, String[] components, VBox vBox)
static Map< String, ComponentDrawer > createComponentsDrawerMap (TurtleNodes turtleNodes)
Static Private Attributes
static String[] myLeftContainerElements
static String[] myRightContainerElements
Detailed Description
This class is responsible for building all of the components. The components are large areas of the screen that house different components.
Author
akyker20
Definition at line 21 of file ComponentBuilder.java.
Member Function Documentation
static void gui.componentdrawers.ComponentBuilder.addComponentsToBox (Map< String, ComponentDrawer > drawerMap, String[] components, VBox vBox) static private
A helper method to make code DRYer
Parameters
drawerMap
components
vBox
Definition at line 84 of file ComponentBuilder.java.
Referenced by gui.componentdrawers.ComponentBuilder.buildLeftComponents(), and gui.componentdrawers.ComponentBuilder.buildRightComponents().
static Map<String, ComponentDrawer> gui.componentdrawers.ComponentBuilder.build (BorderPane pane, TurtleNodes turtleNodes) static
Definition at line 43 of file ComponentBuilder.java.
References gui.componentdrawers.ComponentBuilder.buildLeftComponents(), gui.componentdrawers.ComponentBuilder.buildRightComponents(), and gui.componentdrawers.ComponentBuilder.createComponentsDrawerMap().
Referenced by gui.mainclasses.workspace.Workspace.Workspace().
static void gui.componentdrawers.ComponentBuilder.buildLeftComponents (BorderPane pane, Map< String, ComponentDrawer > drawerMap) static private
Adds the components that will be on the left side of the screen to the borderpane.
Parameters
pane
drawerMap
Definition at line 70 of file ComponentBuilder.java.
References gui.componentdrawers.ComponentBuilder.addComponentsToBox().
Referenced by gui.componentdrawers.ComponentBuilder.build().
static void gui.componentdrawers.ComponentBuilder.buildRightComponents (BorderPane pane, Map< String, ComponentDrawer > drawerMap) static private
Adds the components that will be on the right side of the screen to the borderpane.
Parameters
pane
drawerMap
Definition at line 56 of file ComponentBuilder.java.
References gui.componentdrawers.ComponentBuilder.addComponentsToBox().
Referenced by gui.componentdrawers.ComponentBuilder.build().
static Map<String, ComponentDrawer> gui.componentdrawers.ComponentBuilder.createComponentsDrawerMap (TurtleNodes turtleNodes) static private
Returns a map that maps the name of the component drawer to the component drawer itself.
Parameters
turtleNodes
Returns
Definition at line 98 of file ComponentBuilder.java.
Referenced by gui.componentdrawers.ComponentBuilder.build().
Member Data Documentation
final String gui.componentdrawers.ComponentBuilder.BUTTON_HOLDER_DRAWER = "ButtonHolderDrawer" static
Definition at line 26 of file ComponentBuilder.java.
Referenced by gui.mainclasses.FeatureBuilder.init().
final String gui.componentdrawers.ComponentBuilder.COMMAND_LINE_DRAWER = "CommandLineDrawer" static
Definition at line 25 of file ComponentBuilder.java.
Referenced by gui.mainclasses.FeatureBuilder.init().
final String gui.componentdrawers.ComponentBuilder.ERROR_DRAWER = "errorDrawer" static
Definition at line 31 of file ComponentBuilder.java.
Referenced by gui.mainclasses.FeatureBuilder.init().
final String gui.componentdrawers.ComponentBuilder.MENU_DRAWER = "MenuDrawer" static
Definition at line 24 of file ComponentBuilder.java.
String [] gui.componentdrawers.ComponentBuilder.myLeftContainerElements static private
Initial value:
= new String[] { SCREEN_DRAWER,
                                                                     PREVIOUS_COMMANDS,
                                                                     COMMAND_LINE_DRAWER,
                                                                     ERROR_DRAWER }
Definition at line 34 of file ComponentBuilder.java.
String [] gui.componentdrawers.ComponentBuilder.myRightContainerElements static private
Initial value:
= new String[] { WORKSPACE_VARIABLES,
                                                                      SIGNIFICANT_COMMANDS_DRAWER,
                                                                      BUTTON_HOLDER_DRAWER }
Definition at line 39 of file ComponentBuilder.java.
final int gui.componentdrawers.ComponentBuilder.PADDING = 10 static
Definition at line 32 of file ComponentBuilder.java.
final String gui.componentdrawers.ComponentBuilder.PREVIOUS_COMMANDS = "previousCommandsDrawer" static
Definition at line 27 of file ComponentBuilder.java.
Referenced by gui.mainclasses.FeatureBuilder.init().
final String gui.componentdrawers.ComponentBuilder.SCREEN_DRAWER = "ScreenDrawer" static
Definition at line 23 of file ComponentBuilder.java.
Referenced by tests.commandTests.inputlessCommandTests.ClearScreenTests.ClearScreeenTest(), gui.mainclasses.FeatureBuilder.init(), tests.commandTests.colorCommandTests.SetBackgroundTests.SetBackgroundTest(), and gui.mainclasses.workspace.Workspace.Workspace().
final String gui.componentdrawers.ComponentBuilder.SIGNIFICANT_COMMANDS_DRAWER = "significantCommandsDrawer" static
Definition at line 30 of file ComponentBuilder.java.
Referenced by gui.mainclasses.FeatureBuilder.init().
final String gui.componentdrawers.ComponentBuilder.WORKSPACE_COMMANDS = "workspaceCommandDrawer" static
Definition at line 29 of file ComponentBuilder.java.
final String gui.componentdrawers.ComponentBuilder.WORKSPACE_VARIABLES = "workspaceVariablesDrawer" static
Definition at line 28 of file ComponentBuilder.java.
Referenced by gui.mainclasses.FeatureBuilder.init().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/componentdrawers/ComponentBuilder.java