slogo_team10: commandParsing.drawableObectGenerationInterfaces.TurtleGenerator Interface Reference
commandParsing.drawableObectGenerationInterfaces.TurtleGenerator Interface Reference
Public Member Functions
default DrawableObject generateDrawableObjectRepresentingTurtle (Turtle turtle)
default DrawableObject generateDrawableObjectRepresentingTurtleDeletion (Turtle turtle)
Detailed Description
This class generates the actual Turtle drawableObjects to give to the GUI.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 16 of file TurtleGenerator.java.
Member Function Documentation
default DrawableObject commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtle (Turtle turtle)
Definition at line 17 of file TurtleGenerator.java.
References gui.factories.turtlefactory.TurtleFactory.DELETION_FLAG, workspaceState.Location.generateLocationString(), workspaceState.Turtle.getHeading(), workspaceState.Turtle.getID(), workspaceState.Turtle.getLocation(), workspaceState.Turtle.getOpacity(), workspaceState.Shape.getPath(), workspaceState.Turtle.getShape(), gui.factories.turtlefactory.TurtleFactory.HEADING, gui.factories.turtlefactory.TurtleFactory.IMAGE_PATH, gui.factories.turtlefactory.TurtleFactory.LOCATION, gui.factories.turtlefactory.TurtleFactory.OPACITY, gui.factories.turtlefactory.TurtleFactory.PARENT, gui.factories.turtlefactory.TurtleFactory.TURTLE_ID, and gui.factories.turtlefactory.TurtleFactory.TYPE.
Referenced by commandParsing.structuralCommandParsing.MultipleTurtleCommand.makeAndActivateGivenTurtles(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetHeading.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.Rotate.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetShape.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.MoveToLocation.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.SetTowards.operateOnComponents(), commandParsing.turtleCommandParsing.turtleMovement.Move.operateOnComponents(), commandParsing.turtleCommandParsing.turtleAttributeSetters.HideTurtle.parse(), commandParsing.turtleCommandParsing.turtleAttributeSetters.ShowTurtle.parse(), commandParsing.turtleCommandParsing.MakeTurtle.parse(), and commandParsing.turtleCommandParsing.Stamp.parse().
default DrawableObject commandParsing.drawableObectGenerationInterfaces.TurtleGenerator.generateDrawableObjectRepresentingTurtleDeletion (Turtle turtle)
Definition at line 33 of file TurtleGenerator.java.
References gui.factories.turtlefactory.TurtleFactory.DELETION_FLAG, workspaceState.Turtle.getID(), gui.factories.turtlefactory.TurtleFactory.PARENT, gui.factories.turtlefactory.TurtleFactory.TURTLE_ID, and gui.factories.turtlefactory.TurtleFactory.TYPE.
Referenced by commandParsing.turtleCommandParsing.ClearStamps.parse().
The documentation for this interface was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/commandParsing/drawableObectGenerationInterfaces/TurtleGenerator.java