slogo_team10: gui.variableslist.WorkspaceVariable Class Reference
gui.variableslist.WorkspaceVariable Class Reference
Public Member Functions
WorkspaceVariable (String name, double value)
String getMyName ()
void setMyName (String myName)
double getMyValue ()
void setMyValue (double myValue)
void addValue (double value)
Private Attributes
String myName
double myValue
Detailed Description
Class is used to represent variables displayed on the GUI. This class is necessary to create a tableview of workspace variables.
Author
akyker20, allankiplagat
Definition at line 9 of file WorkspaceVariable.java.
Constructor & Destructor Documentation
gui.variableslist.WorkspaceVariable.WorkspaceVariable (String name, double value)
Definition at line 14 of file WorkspaceVariable.java.
Member Function Documentation
void gui.variableslist.WorkspaceVariable.addValue (double value)
Definition at line 39 of file WorkspaceVariable.java.
Referenced by workspaceState.UserDefinedVariableCollection.storeVariable().
String gui.variableslist.WorkspaceVariable.getMyName ()
Definition at line 19 of file WorkspaceVariable.java.
References gui.variableslist.WorkspaceVariable.myName.
Referenced by gui.nonbuttonfeatures.tableviews.variables.EditingCell.createTextField(), and commandParsing.drawableObectGenerationInterfaces.UserDefinedVariableGenerator.generateDrawableObjectRepresentingVariable().
double gui.variableslist.WorkspaceVariable.getMyValue ()
Definition at line 27 of file WorkspaceVariable.java.
References gui.variableslist.WorkspaceVariable.myValue.
Referenced by commandParsing.drawableObectGenerationInterfaces.UserDefinedVariableGenerator.generateDrawableObjectRepresentingVariable().
void gui.variableslist.WorkspaceVariable.setMyName (String myName)
Definition at line 23 of file WorkspaceVariable.java.
References gui.variableslist.WorkspaceVariable.myName.
void gui.variableslist.WorkspaceVariable.setMyValue (double myValue)
Necessary to make the value editable.
Parameters
myValue
Definition at line 35 of file WorkspaceVariable.java.
References gui.variableslist.WorkspaceVariable.myValue.
Member Data Documentation
String gui.variableslist.WorkspaceVariable.myName private
Definition at line 11 of file WorkspaceVariable.java.
Referenced by gui.variableslist.WorkspaceVariable.getMyName(), and gui.variableslist.WorkspaceVariable.setMyName().
double gui.variableslist.WorkspaceVariable.myValue private
Definition at line 12 of file WorkspaceVariable.java.
Referenced by gui.variableslist.WorkspaceVariable.getMyValue(), and gui.variableslist.WorkspaceVariable.setMyValue().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/variableslist/WorkspaceVariable.java