slogo_team10: gui.componentdrawers.CommandLineDrawer Class Reference
gui.componentdrawers.CommandLineDrawer Class Reference
Public Member Functions
CommandLineDrawer (String name)
void setCommandLine (TextArea t)
String getCurrentCommand ()
void setCommandLine (String s)
Public Member Functions inherited from gui.componentdrawers.ComponentDrawer
ComponentDrawer (String name)
void drawShape (Node[] node)
String getName ()
Private Attributes
TextArea myCommandLine
Additional Inherited Members
Static Public Attributes inherited from gui.componentdrawers.ComponentDrawer
static final String TABPANE_LABEL = "tabPane"
Detailed Description
The command line drawer is the component responsible for the command line feature.
Author
akyker20
Definition at line 15 of file CommandLineDrawer.java.
Constructor & Destructor Documentation
gui.componentdrawers.CommandLineDrawer.CommandLineDrawer (String name)
Definition at line 19 of file CommandLineDrawer.java.
References gui.mainclasses.TextGenerator.COMMAND_LINE, gui.componentdrawers.ComponentDrawer.drawShape(), gui.mainclasses.TextGenerator.get(), gui.componentdrawers.TurtleScreenDrawer.GRID_WIDTH_RATIO, and gui.mainclasses.StageInitializer.SCREEN_WIDTH.
Member Function Documentation
String gui.componentdrawers.CommandLineDrawer.getCurrentCommand ()
Returns the current text in the command line, called from the SaveCommandButtonFeature. That feature needs the current input value so it can pass it to the back-end to be saved.
Returns
Definition at line 42 of file CommandLineDrawer.java.
Referenced by gui.buttonfeatures.SaveCommandButtonFeature.saveCommand().
void gui.componentdrawers.CommandLineDrawer.setCommandLine (TextArea t)
Provides this drawer with access to the command line text field so that certain features can get access to the current text value of the field.
Parameters
t
Definition at line 32 of file CommandLineDrawer.java.
Referenced by gui.nonbuttonfeatures.CommandLineFeature.CommandLineFeature(), gui.nonbuttonfeatures.PreviousCommandsFeature.displayPreviousCommandInCommandLineOnDblClick(), and gui.nonbuttonfeatures.SavedCommandsFeature.SavedCommandsFeature().
void gui.componentdrawers.CommandLineDrawer.setCommandLine (String s)
Sets the text of the command line text field to be the input string. This is called when a previous command is clicked (PreviousCommandFeature)
Parameters
s
Definition at line 52 of file CommandLineDrawer.java.
Member Data Documentation
TextArea gui.componentdrawers.CommandLineDrawer.myCommandLine private
Definition at line 17 of file CommandLineDrawer.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/componentdrawers/CommandLineDrawer.java