slogo_team10: tests.screenWrapTests.TurtleScreenWrapTests Class Reference
tests.screenWrapTests.TurtleScreenWrapTests Class Reference
Public Member Functions
void exitTopRightDiagonally ()
void exitTopLeftDiagonally ()
void exitBottomRightDiagonally ()
void exitBottomLeftDiagonally ()
void exitRightTopDiagonally ()
void exitRightBOttomDiagonally ()
void exitLeftTopDiagonally ()
void exitLeftBottomDiagonally ()
void exitRightHorizontally ()
void exitLeftHorizontally ()
void exitTopVertically ()
void exitBottomVertically ()
Static Public Attributes
static final float XMAX = TurtleScreenWrap.XMAX
static final float YMAX = TurtleScreenWrap.YMAX
static final double THRESH = 0.00001
Detailed Description
Definition at line 11 of file TurtleScreenWrapTests.java.
Member Function Documentation
void tests.screenWrapTests.TurtleScreenWrapTests.exitBottomLeftDiagonally ()
Definition at line 75 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.YMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitBottomRightDiagonally ()
Definition at line 56 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.YMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitBottomVertically ()
Definition at line 227 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.YMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitLeftBottomDiagonally ()
Definition at line 151 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.XMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitLeftHorizontally ()
Definition at line 189 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.XMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitLeftTopDiagonally ()
Definition at line 132 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.XMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitRightBOttomDiagonally ()
Definition at line 113 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.XMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitRightHorizontally ()
Definition at line 170 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.XMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitRightTopDiagonally ()
Definition at line 94 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.XMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitTopLeftDiagonally ()
Definition at line 36 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.YMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitTopRightDiagonally ()
Definition at line 17 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.YMAX.
void tests.screenWrapTests.TurtleScreenWrapTests.exitTopVertically ()
Definition at line 208 of file TurtleScreenWrapTests.java.
References gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair(), tests.screenWrapTests.TurtleScreenWrapTests.THRESH, and tests.screenWrapTests.TurtleScreenWrapTests.YMAX.
Member Data Documentation
final double tests.screenWrapTests.TurtleScreenWrapTests.THRESH = 0.00001 static
Definition at line 14 of file TurtleScreenWrapTests.java.
Referenced by tests.screenWrapTests.TurtleScreenWrapTests.exitBottomLeftDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitBottomRightDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitBottomVertically(), tests.screenWrapTests.TurtleScreenWrapTests.exitLeftBottomDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitLeftHorizontally(), tests.screenWrapTests.TurtleScreenWrapTests.exitLeftTopDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitRightBOttomDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitRightHorizontally(), tests.screenWrapTests.TurtleScreenWrapTests.exitRightTopDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitTopLeftDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitTopRightDiagonally(), and tests.screenWrapTests.TurtleScreenWrapTests.exitTopVertically().
final float tests.screenWrapTests.TurtleScreenWrapTests.XMAX = TurtleScreenWrap.XMAX static
Definition at line 12 of file TurtleScreenWrapTests.java.
Referenced by tests.screenWrapTests.TurtleScreenWrapTests.exitLeftBottomDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitLeftHorizontally(), tests.screenWrapTests.TurtleScreenWrapTests.exitLeftTopDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitRightBOttomDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitRightHorizontally(), and tests.screenWrapTests.TurtleScreenWrapTests.exitRightTopDiagonally().
final float tests.screenWrapTests.TurtleScreenWrapTests.YMAX = TurtleScreenWrap.YMAX static
Definition at line 13 of file TurtleScreenWrapTests.java.
Referenced by tests.screenWrapTests.TurtleScreenWrapTests.exitBottomLeftDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitBottomRightDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitBottomVertically(), tests.screenWrapTests.TurtleScreenWrapTests.exitTopLeftDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitTopRightDiagonally(), and tests.screenWrapTests.TurtleScreenWrapTests.exitTopVertically().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/tests/screenWrapTests/TurtleScreenWrapTests.java