slogo_team10: gui.turtlescreenwrap.TurtleScreenWrap Class Reference
gui.turtlescreenwrap.TurtleScreenWrap Class Reference
Static Public Member Functions
static List< Point2DPair > fragmentPoint2DPair (Point2DPair tesselatedPointPair)
static List< Point2DPair > getFragments (Point2DPair pointPair, String exitEdge, float gradient, float maxDeltaX, float maxDeltaY)
static String getExitEdge (Point2DPair pointPair, float gradient, float maxDeltaY, String xmovement, String ymovement)
static float getMaxDeltaY (Point2DPair pointPair, String ymovement)
static float getMaxDeltaX (Point2DPair pointPair, String xmovement)
static String getYmovement (Point2DPair pointPair)
static String getXmovement (Point2DPair pointPair)
static float getGradient (Point2DPair pointPair)
Static Public Attributes
static final float XMAX = (float) TurtleScreenDrawer.GRID_WIDTH / 2
static final float YMAX = (float) TurtleScreenDrawer.GRID_HEIGHT / 2
static final String XPOS_MOVE = "XPositive move"
static final String XNEG_MOVE = "XNegative move"
static final String XZERO_MOVE = "XZero move"
static final String YPOS_MOVE = "YPositive move"
static final String YNEG_MOVE = "YNegative move"
static final String YZERO_MOVE = "YZero move"
static final String TOP_EDGE = "TopEdge"
static final String BOTTOM_EDGE = "BottomEdge"
static final String LEFT_EDGE = "LeftEdge"
static final String RIGHT_EDGE = "RightEdge"
Detailed Description
Class applies wrapping around algorithm to a Point2DPair object
Author
allankiplagat
Definition at line 13 of file TurtleScreenWrap.java.
Member Function Documentation
static List<Point2DPair> gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair (Point2DPair tesselatedPointPair) static
Method takes in a Point2DPair (that contains an origin and destination Point2D) and returns the corresponding sequence of sub-Point2DPairs to be displayed on the screen with wrap-around applied
Parameters
pointPair
Returns
Definition at line 37 of file TurtleScreenWrap.java.
References gui.turtlescreenwrap.TesselationMapper.checkOffScreen(), gui.turtlescreenwrap.Point2DPair.dest, gui.turtlescreenwrap.VerticalTurtleScreenWrap.fragmentPoint2DPair(), gui.turtlescreenwrap.HorizontalTurtleScreenWrap.fragmentPoint2DPair(), gui.turtlescreenwrap.TurtleScreenWrap.getExitEdge(), gui.turtlescreenwrap.TurtleScreenWrap.getFragments(), gui.turtlescreenwrap.TurtleScreenWrap.getGradient(), gui.turtlescreenwrap.TurtleScreenWrap.getMaxDeltaX(), gui.turtlescreenwrap.TurtleScreenWrap.getMaxDeltaY(), gui.turtlescreenwrap.TurtleScreenWrap.getXmovement(), gui.turtlescreenwrap.TurtleScreenWrap.getYmovement(), gui.turtlescreenwrap.TesselationMapper.map(), and gui.turtlescreenwrap.Point2DPair.origin.
Referenced by tests.screenWrapTests.TurtleScreenWrapTests.exitBottomLeftDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitBottomRightDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitBottomVertically(), tests.screenWrapTests.TurtleScreenWrapTests.exitLeftBottomDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitLeftHorizontally(), tests.screenWrapTests.TurtleScreenWrapTests.exitLeftTopDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitRightBOttomDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitRightHorizontally(), tests.screenWrapTests.TurtleScreenWrapTests.exitRightTopDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitTopLeftDiagonally(), tests.screenWrapTests.TurtleScreenWrapTests.exitTopRightDiagonally(), and tests.screenWrapTests.TurtleScreenWrapTests.exitTopVertically().
static String gui.turtlescreenwrap.TurtleScreenWrap.getExitEdge (Point2DPair pointPair, float gradient, float maxDeltaY, String xmovement, String ymovement) static
Definition at line 113 of file TurtleScreenWrap.java.
References gui.turtlescreenwrap.TurtleScreenWrap.BOTTOM_EDGE, gui.turtlescreenwrap.TesselationMapper.checkOffScreen(), gui.turtlescreenwrap.TurtleScreenWrap.LEFT_EDGE, gui.turtlescreenwrap.Point2DPair.origin, gui.turtlescreenwrap.TurtleScreenWrap.RIGHT_EDGE, and gui.turtlescreenwrap.TurtleScreenWrap.TOP_EDGE.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair().
static List<Point2DPair> gui.turtlescreenwrap.TurtleScreenWrap.getFragments (Point2DPair pointPair, String exitEdge, float gradient, float maxDeltaX, float maxDeltaY) static
Definition at line 79 of file TurtleScreenWrap.java.
References gui.turtlescreenwrap.Point2DPair.dest, and gui.turtlescreenwrap.Point2DPair.origin.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair().
static float gui.turtlescreenwrap.TurtleScreenWrap.getGradient (Point2DPair pointPair) static
Method gets the gradient of the line joining the points in a pointPair Returns 0.0 if the line is vertical (infinite gradient)
Parameters
pointPair
isVerticalLine
Returns
Definition at line 186 of file TurtleScreenWrap.java.
References gui.turtlescreenwrap.Point2DPair.dest, and gui.turtlescreenwrap.Point2DPair.origin.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair().
static float gui.turtlescreenwrap.TurtleScreenWrap.getMaxDeltaX (Point2DPair pointPair, String xmovement) static
Definition at line 151 of file TurtleScreenWrap.java.
References gui.turtlescreenwrap.Point2DPair.origin.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair().
static float gui.turtlescreenwrap.TurtleScreenWrap.getMaxDeltaY (Point2DPair pointPair, String ymovement) static
Definition at line 143 of file TurtleScreenWrap.java.
References gui.turtlescreenwrap.Point2DPair.origin, and gui.turtlescreenwrap.TurtleScreenWrap.YMAX.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair().
static String gui.turtlescreenwrap.TurtleScreenWrap.getXmovement (Point2DPair pointPair) static
Definition at line 168 of file TurtleScreenWrap.java.
References gui.turtlescreenwrap.Point2DPair.dest, gui.turtlescreenwrap.Point2DPair.origin, gui.turtlescreenwrap.TurtleScreenWrap.XNEG_MOVE, gui.turtlescreenwrap.TurtleScreenWrap.XPOS_MOVE, and gui.turtlescreenwrap.TurtleScreenWrap.XZERO_MOVE.
Referenced by gui.turtlescreenwrap.HorizontalTurtleScreenWrap.fragmentPoint2DPair(), and gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair().
static String gui.turtlescreenwrap.TurtleScreenWrap.getYmovement (Point2DPair pointPair) static
Definition at line 159 of file TurtleScreenWrap.java.
References gui.turtlescreenwrap.Point2DPair.dest, gui.turtlescreenwrap.Point2DPair.origin, gui.turtlescreenwrap.TurtleScreenWrap.YNEG_MOVE, gui.turtlescreenwrap.TurtleScreenWrap.YPOS_MOVE, and gui.turtlescreenwrap.TurtleScreenWrap.YZERO_MOVE.
Referenced by gui.turtlescreenwrap.VerticalTurtleScreenWrap.fragmentPoint2DPair(), and gui.turtlescreenwrap.TurtleScreenWrap.fragmentPoint2DPair().
Member Data Documentation
final String gui.turtlescreenwrap.TurtleScreenWrap.BOTTOM_EDGE = "BottomEdge" static
Definition at line 25 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.getExitEdge().
final String gui.turtlescreenwrap.TurtleScreenWrap.LEFT_EDGE = "LeftEdge" static
Definition at line 26 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.getExitEdge().
final String gui.turtlescreenwrap.TurtleScreenWrap.RIGHT_EDGE = "RightEdge" static
Definition at line 27 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.getExitEdge().
final String gui.turtlescreenwrap.TurtleScreenWrap.TOP_EDGE = "TopEdge" static
Definition at line 24 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.getExitEdge().
final float gui.turtlescreenwrap.TurtleScreenWrap.XMAX = (float) TurtleScreenDrawer.GRID_WIDTH / 2 static
Definition at line 14 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.HorizontalTurtleScreenWrap.fragmentPoint2DPair().
final String gui.turtlescreenwrap.TurtleScreenWrap.XNEG_MOVE = "XNegative move" static
Definition at line 18 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.getXmovement().
final String gui.turtlescreenwrap.TurtleScreenWrap.XPOS_MOVE = "XPositive move" static
Definition at line 17 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.HorizontalTurtleScreenWrap.fragmentPoint2DPair(), and gui.turtlescreenwrap.TurtleScreenWrap.getXmovement().
final String gui.turtlescreenwrap.TurtleScreenWrap.XZERO_MOVE = "XZero move" static
Definition at line 19 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.getXmovement().
final float gui.turtlescreenwrap.TurtleScreenWrap.YMAX = (float) TurtleScreenDrawer.GRID_HEIGHT / 2 static
Definition at line 15 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.VerticalTurtleScreenWrap.fragmentPoint2DPair(), and gui.turtlescreenwrap.TurtleScreenWrap.getMaxDeltaY().
final String gui.turtlescreenwrap.TurtleScreenWrap.YNEG_MOVE = "YNegative move" static
Definition at line 21 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.getYmovement().
final String gui.turtlescreenwrap.TurtleScreenWrap.YPOS_MOVE = "YPositive move" static
Definition at line 20 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.VerticalTurtleScreenWrap.fragmentPoint2DPair(), and gui.turtlescreenwrap.TurtleScreenWrap.getYmovement().
final String gui.turtlescreenwrap.TurtleScreenWrap.YZERO_MOVE = "YZero move" static
Definition at line 22 of file TurtleScreenWrap.java.
Referenced by gui.turtlescreenwrap.TurtleScreenWrap.getYmovement().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/turtlescreenwrap/TurtleScreenWrap.java