slogo_team10: translator.Translator Class Reference
translator.Translator Class Reference
Public Member Functions
Translator (String language) throws LanguageFileNotFoundException, PropertyFileAccessException
void createMappingsGivenLanguage (String language) throws LanguageFileNotFoundException, PropertyFileAccessException
Iterator< String > translate (String commands)
List< String > translateToList (String string)
String reverseTranslate (List< String > strings)
boolean matchesVariablePattern (String str)
boolean matchesConstantPattern (String str)
boolean matchesCommandPattern (String str)
boolean matchesListStartPattern (String str)
boolean matchesListEndPattern (String str)
boolean matchesGroupStartPattern (String str)
boolean matchesGroupEndPattern (String str)
Private Member Functions
void mapLanguageToClassPath ()
void buildDictionaryOfCommandsToEnglish (String language)
void buildMapOfCommandPaths () throws LanguageFileNotFoundException, PropertyFileAccessException
void createReverseMapping ()
Static Private Member Functions
static String findCommandName (String command)
static String clipPathName (String command)
Private Attributes
Map< String, String > dictionaryLanguageToEnglish = new HashMap<String, String>()
Map< String, String > dictionaryOfClassNameToPath = new HashMap<String, String>()
Map< String, String > dictionaryOfLanguageToClassPath = new HashMap<String, String>()
Map< String, String > syntaxDictionary = new HashMap<String, String>()
Map< String, String > reverseMapping = new HashMap<String,String>()
Static Private Attributes
static final String CONSTANT = "Constant"
static final String VARIABLE = "Variable"
static final String USER_DEFINED_COMMAND = "UserInstruction"
static final String JAR_NAME = "SLOGO.jar"
static final String COMMAND_PACKAGE_NAME = "commandParsing"
Detailed Description
This file deals with translating the commands in different languages to Strings that our parser can actually work with and deal with.
Author
Stanley Yuan, Steve Kuznetsov
Definition at line 28 of file Translator.java.
Constructor & Destructor Documentation
translator.Translator.Translator (String language) throws LanguageFileNotFoundException, PropertyFileAccessException
Definition at line 42 of file Translator.java.
References translator.Translator.createMappingsGivenLanguage().
Member Function Documentation
void translator.Translator.buildDictionaryOfCommandsToEnglish (String language) private
Definition at line 107 of file Translator.java.
Referenced by translator.Translator.createMappingsGivenLanguage().
void translator.Translator.buildMapOfCommandPaths () throws LanguageFileNotFoundException, PropertyFileAccessException private
Definition at line 146 of file Translator.java.
References translator.Translator.clipPathName(), and translator.Translator.findCommandName().
Referenced by translator.Translator.createMappingsGivenLanguage().
static String translator.Translator.clipPathName (String command) static private
Definition at line 195 of file Translator.java.
Referenced by translator.Translator.buildMapOfCommandPaths().
void translator.Translator.createMappingsGivenLanguage (String language) throws LanguageFileNotFoundException, PropertyFileAccessException
Creating a few different maps, it creates a mapping of the language to what we actually need. It takes in a language as a String.
Parameters
language
Exceptions
LanguageFileNotFoundException
PropertyFileAccessException
Definition at line 54 of file Translator.java.
References translator.Translator.buildDictionaryOfCommandsToEnglish(), translator.Translator.buildMapOfCommandPaths(), translator.Translator.createReverseMapping(), and translator.Translator.mapLanguageToClassPath().
Referenced by commandParsing.SetLanguage.parse(), tests.commandTests.CommandTester.setUpTranslator(), and translator.Translator.Translator().
void translator.Translator.createReverseMapping () private
Definition at line 179 of file Translator.java.
Referenced by translator.Translator.createMappingsGivenLanguage().
static String translator.Translator.findCommandName (String command) static private
Definition at line 190 of file Translator.java.
Referenced by translator.Translator.buildMapOfCommandPaths().
void translator.Translator.mapLanguageToClassPath () private
Definition at line 101 of file Translator.java.
Referenced by translator.Translator.createMappingsGivenLanguage().
boolean translator.Translator.matchesCommandPattern (String str)
Definition at line 207 of file Translator.java.
Referenced by commandParsing.CommandParser.isStringParsableAsCommand(), translator.Translator.translateToList(), and tests.TranslatorTests.TranslatorRegExTest().
boolean translator.Translator.matchesConstantPattern (String str)
Definition at line 203 of file Translator.java.
Referenced by translator.Translator.translateToList(), and tests.TranslatorTests.TranslatorRegExTest().
boolean translator.Translator.matchesGroupEndPattern (String str)
Definition at line 223 of file Translator.java.
boolean translator.Translator.matchesGroupStartPattern (String str)
Definition at line 219 of file Translator.java.
boolean translator.Translator.matchesListEndPattern (String str)
Definition at line 215 of file Translator.java.
Referenced by commandParsing.structuralCommandParsing.StructuralCommand.checkForClosingBrace(), commandParsing.structuralCommandParsing.StructuralCommand.extractCommandsBetweenBraces(), and commandParsing.structuralCommandParsing.StructuralCommand.findBrace().
boolean translator.Translator.matchesListStartPattern (String str)
Definition at line 211 of file Translator.java.
Referenced by commandParsing.structuralCommandParsing.StructuralCommand.checkForOpeningBrace(), commandParsing.structuralCommandParsing.StructuralCommand.extractCommandsBetweenBraces(), and commandParsing.structuralCommandParsing.StructuralCommand.findBrace().
boolean translator.Translator.matchesVariablePattern (String str)
Definition at line 199 of file Translator.java.
Referenced by commandParsing.structuralCommandParsing.DoTimes.initializeLoopVariableParameters(), commandParsing.structuralCommandParsing.For.initializeLoopVariableParameters(), commandParsing.variableCommandParsing.MakeVariable.parse(), translator.Translator.translateToList(), and tests.TranslatorTests.TranslatorRegExTest().
String translator.Translator.reverseTranslate (List< String > strings)
Definition at line 89 of file Translator.java.
Referenced by commandParsing.drawableObectGenerationInterfaces.UserDefinedCommandGenerator.generateDrawableObjectRepresentingCommand().
Iterator<String> translator.Translator.translate (String commands)
Definition at line 61 of file Translator.java.
References translator.Translator.translateToList().
Referenced by tests.TranslatorTests.ChineseTranslationTest(), tests.TranslatorTests.EnglishTranslationTest(), tests.TranslatorTests.FrenchTranslationTest(), tests.TranslatorTests.ItalianTranslationTest(), Control.SlogoControl.parseCommandString(), tests.TranslatorTests.PortugueseTranslationTest(), tests.TranslatorTests.RussianTranslationTest(), and tests.commandTests.CommandTester.setUpCommands().
List<String> translator.Translator.translateToList (String string)
Definition at line 65 of file Translator.java.
References translator.Translator.matchesCommandPattern(), translator.Translator.matchesConstantPattern(), and translator.Translator.matchesVariablePattern().
Referenced by tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTest(), tests.commandTests.userDefinedCommandTests.MakeUserInstructionTests.MakeCommandTestWithPreviousVariables(), and translator.Translator.translate().
Member Data Documentation
final String translator.Translator.COMMAND_PACKAGE_NAME = "commandParsing" static private
Definition at line 34 of file Translator.java.
final String translator.Translator.CONSTANT = "Constant" static private
Definition at line 30 of file Translator.java.
Map<String, String> translator.Translator.dictionaryLanguageToEnglish = new HashMap<String, String>() private
Definition at line 35 of file Translator.java.
Map<String, String> translator.Translator.dictionaryOfClassNameToPath = new HashMap<String, String>() private
Definition at line 36 of file Translator.java.
Map<String, String> translator.Translator.dictionaryOfLanguageToClassPath = new HashMap<String, String>() private
Definition at line 37 of file Translator.java.
final String translator.Translator.JAR_NAME = "SLOGO.jar" static private
Definition at line 33 of file Translator.java.
Map<String, String> translator.Translator.reverseMapping = new HashMap<String,String>() private
Definition at line 39 of file Translator.java.
Map<String, String> translator.Translator.syntaxDictionary = new HashMap<String, String>() private
Definition at line 38 of file Translator.java.
final String translator.Translator.USER_DEFINED_COMMAND = "UserInstruction" static private
Definition at line 32 of file Translator.java.
final String translator.Translator.VARIABLE = "Variable" static private
Definition at line 31 of file Translator.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/translator/Translator.java