slogo_team10: gui.mainclasses.FeatureBuilder Class Reference
gui.mainclasses.FeatureBuilder Class Reference
Static Public Member Functions
static void init (Workspace workspace, Map< String, ComponentDrawer > drawerMap, WorkspaceScreenParameters screenParameters, WorkspaceDataHolder dataHolder)
Detailed Description
The purpose of this class is to initialize all of the features, both button features and non-button features that will be displayed to the user.
Author
Austin Kyker
Definition at line 51 of file FeatureBuilder.java.
Member Function Documentation
static void gui.mainclasses.FeatureBuilder.init (Workspace workspace, Map< String, ComponentDrawer > drawerMap, WorkspaceScreenParameters screenParameters, WorkspaceDataHolder dataHolder) static
Definition at line 53 of file FeatureBuilder.java.
References gui.componentdrawers.optionsholder.OptionsHolderDrawer.addTabs(), gui.componentdrawers.significantcommands.SignificantCommandsDrawer.addTabs(), gui.componentdrawers.ComponentBuilder.BUTTON_HOLDER_DRAWER, gui.componentdrawers.ComponentBuilder.COMMAND_LINE_DRAWER, gui.componentdrawers.ComponentBuilder.ERROR_DRAWER, gui.mainclasses.workspace.WorkspaceDataHolder.getMyColorIndexList(), gui.mainclasses.workspace.WorkspaceDataHolder.getMyImageIndexList(), gui.mainclasses.workspace.WorkspaceDataHolder.getMyPreviousCommandsList(), gui.mainclasses.workspace.WorkspaceDataHolder.getMySavedCommandsList(), gui.mainclasses.workspace.WorkspaceDataHolder.getMyVariablesList(), gui.componentdrawers.ComponentBuilder.PREVIOUS_COMMANDS, gui.componentdrawers.ComponentBuilder.SCREEN_DRAWER, gui.componentdrawers.ComponentBuilder.SIGNIFICANT_COMMANDS_DRAWER, and gui.componentdrawers.ComponentBuilder.WORKSPACE_VARIABLES.
Referenced by gui.mainclasses.workspace.Workspace.Workspace().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/mainclasses/FeatureBuilder.java