slogo_team10: gui.mainclasses.GUIController Class Reference
gui.mainclasses.GUIController Class Reference
Public Member Functions
GUIController (Stage stage, SlogoGraphics control)
void drawDrawableObjects (Queue< DrawableObject > objectQueue)
WorkspaceManager getWorkspaceManager ()
Private Member Functions
void moveActiveTurtlesInActiveWorkspace (KeyEvent event)
Private Attributes
BorderPane myPane
WorkspaceManager myWorkspaceManager
Detailed Description
Class controls the GUI: initializes the scene and sets up the component drawers, object factories, and features; depends on a SlogoGraphics control object
Author
allankiplagat, akyker20
Definition at line 20 of file GUIController.java.
Constructor & Destructor Documentation
gui.mainclasses.GUIController.GUIController (Stage stage, SlogoGraphics control)
Parameters
stage
control
Definition at line 29 of file GUIController.java.
References gui.menus.MainMenuInitializer.init(), gui.mainclasses.StageInitializer.init(), and gui.mainclasses.GUIController.moveActiveTurtlesInActiveWorkspace().
Member Function Documentation
void gui.mainclasses.GUIController.drawDrawableObjects (Queue< DrawableObject > objectQueue)
Method to convert a DrawableObject queue into shapes that can be drawn on the screen
Parameters
objectQueue
Definition at line 46 of file GUIController.java.
References gui.mainclasses.workspace.WorkspaceManager.getActiveWorkspace(), and gui.mainclasses.workspace.Workspace.parseDrawableObject().
Referenced by Control.SlogoControl.drawDrawableObjects().
WorkspaceManager gui.mainclasses.GUIController.getWorkspaceManager ()
Definition at line 52 of file GUIController.java.
References gui.mainclasses.GUIController.myWorkspaceManager.
Referenced by Control.SlogoControl.parseCommandString().
void gui.mainclasses.GUIController.moveActiveTurtlesInActiveWorkspace (KeyEvent event) private
Definition at line 37 of file GUIController.java.
References gui.mainclasses.workspace.WorkspaceManager.getActiveWorkspace(), and gui.mainclasses.workspace.Workspace.moveActiveTurtles().
Referenced by gui.mainclasses.GUIController.GUIController().
Member Data Documentation
BorderPane gui.mainclasses.GUIController.myPane private
Definition at line 21 of file GUIController.java.
WorkspaceManager gui.mainclasses.GUIController.myWorkspaceManager private
Definition at line 22 of file GUIController.java.
Referenced by gui.mainclasses.GUIController.getWorkspaceManager().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team10/repository/src/gui/mainclasses/GUIController.java